hyrise/hyrise

DEPENDENCIES.md, README.md
=> Add demo script to readme and update dependencies

Jenkinsfile, scripts/compare_coverage.sh, scripts/coverage.sh
=> Add information on how coverage has changed to PRs

scripts/compare_coverage.sh, src/lib/operators/delete.cpp, src/lib/operators/update.cpp, src/lib/operators/validate.cpp, src/lib/sql/sql_to_ast_translator.cpp, src/lib/storage/chunk.cpp, src/lib/storage/chunk.hpp, src/test/sql/sqlite_testrunner/sqlite_testrunner.tables, src/test/sql/sqlite_testrunner/sqlite_testrunner_queries.sql
=> Enable SQL DML Tests in Test Runner

src/lib/storage/value_column.hpp
This PR updates a few comments in `ValueColumn.hpp` for better understanding of `operator[]`, `get()`, `values()` and `null_values()`.
=> Update ValueColumn comments

src/lib/optimizer/strategy/join_detection_rule.cpp, src/test/optimizer/strategy/join_detection_rule_test.cpp
Since god only knows when we'll be able to discard the JoinDetection rule, let's keep it healthy
=> Fix JoinDetection when CrossJoin is someone's right child

src/lib/operators/join_sort_merge.cpp, src/lib/operators/table_scan.cpp, src/lib/operators/table_scan.hpp, src/lib/optimizer/abstract_syntax_tree/aggregate_node.cpp, src/lib/optimizer/abstract_syntax_tree/ast_to_operator_translator.cpp, src/lib/optimizer/abstract_syntax_tree/projection_node.cpp, src/lib/storage/chunk.cpp, src/lib/storage/chunk.hpp, src/lib/types.hpp, src/test/operators/table_scan_test.cpp, src/test/optimizer/ast_to_operator_translator_test.cpp, src/test/optimizer/strategy/predicate_reordering_test.cpp, src/test/optimizer/table_statistics_test.cpp
=> Fix TableScan's between implementation

src/lib/operators/insert.cpp, src/lib/operators/projection.cpp, src/lib/optimizer/abstract_syntax_tree/ast_to_operator_translator.cpp, src/lib/storage/value_column.cpp, src/test/operators/insert_test.cpp, src/test/tables/float_with_null.tbl
This PR is part of #13. We can now insert null values.
=> Insert null values

Jenkinsfile, scripts/coverage.sh
=> Make coverage.sh build the coverage build

src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.hpp, src/lib/optimizer/abstract_syntax_tree/union_node.cpp, src/test/optimizer/abstract_syntax_tree/union_node_test.cpp
=> Fix some UnionNode Tests

src/lib/optimizer/abstract_syntax_tree/predicate_node.cpp
=> Describe PredicateNode::description better

src/lib/storage/storage_manager.cpp, src/test/base_test.hpp, src/test/concurrency/transaction_context_test.cpp, src/test/logical_query_plan/aggregate_node_test.cpp, src/test/logical_query_plan/delete_node_test.cpp, src/test/logical_query_plan/join_node_test.cpp, src/test/logical_query_plan/logical_query_plan_test.cpp, src/test/logical_query_plan/projection_node_test.cpp, src/test/logical_query_plan/stored_table_node_test.cpp, src/test/operators/import_binary_test.cpp, src/test/operators/union_positions_test.cpp, src/test/optimizer/ast_to_operator_translator_test.cpp, src/test/optimizer/strategy/strategy_base_test.hpp, src/test/scheduler/scheduler_test.cpp, src/test/sql/sql_base_test.hpp, src/test/sql/sql_parse_tree_cache_test.cpp, src/test/sql/sql_query_operator_test.cpp, src/test/sql/sql_query_plan_cache_test.cpp, src/test/storage/numa_placement_test.cpp, src/test/storage/reference_column_test.cpp, src/test/tpc/tpcc_ref_test.cpp, src/test/tpc/tpch_test.cpp
=> Fix StorageManager::add_table / teardown of tests

DEPENDENCIES.md, Dockerfile, Jenkinsfile, scripts/coverage.sh, src/test/operators/aggregate_test.cpp
This generates coverage diffs (looks like [this](https://ares.epic.hpi.uni-potsdam.de/jenkins/job/Hyrise/job/hyrise/job/mrks%252Fpycobertura-reduce-coverage/3/artifact/coverage_diff.html)).
fixes #481
=> pycobertura

src/benchmarklib/tpch/tpch_queries.cpp, src/bin/playground.cpp, src/lib/constant_mappings.cpp, src/lib/operators/table_scan.cpp, src/lib/operators/table_scan/like_table_scan_impl.cpp, src/lib/operators/table_scan/like_table_scan_impl.hpp, src/lib/optimizer/table_statistics.cpp, src/lib/sql/sql_translator.cpp, src/lib/types.hpp, src/test/operators/table_scan_like_test.cpp, src/test/sql/sqlite_testrunner/sqlite_wrapper.cpp, src/test/tables/int_string_like_not_starting.tbl
=> Implement NOT LIKE

src/lib/concurrency/transaction_manager.cpp, src/lib/concurrency/transaction_manager.hpp, src/lib/operators/insert.cpp, src/test/tasks/chunk_compression_task_test.cpp
=> Allow compression of chunks with aborted inserts

src/lib/storage/numa_placement_manager.cpp, src/lib/storage/numa_placement_manager.hpp, src/lib/storage/storage_manager.hpp, src/lib/utils/boost_default_memory_resource.cpp, src/lib/utils/pausable_loop_thread.cpp, src/lib/utils/pausable_loop_thread.hpp, src/test/base_test.hpp, src/test/storage/numa_placement_test.cpp, src/test/storage/storage_manager_test.cpp
=> Fix order of NUMA manager and test teardown

src/lib/operators/abstract_join_operator.hpp, src/lib/operators/sort.cpp, src/lib/operators/validate.cpp
=> Clarify when Validate can be used

src/benchmark/operators/sql_benchmark.cpp, src/lib/operators/index_scan.cpp, src/lib/storage/numa_placement_manager.cpp, src/lib/tasks/migration_preparation_task.cpp, src/test/operators/index_scan_test.cpp
=> Don't run NUMA placement if we only have one node

src/lib/logical_query_plan/abstract_lqp_node.cpp, src/test/sql/sql_translator_test.cpp
This fixes #571 for me. However @Bouncner mentioned a segfault, so this might not be complete yet?
=> Change DebugAssert to Assert when accessing invalid column name.

src/lib/operators/limit.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_queries.sql
=> Fix limit after projection

src/lib/operators/delete.cpp, src/lib/optimizer/table_statistics.cpp, src/lib/optimizer/table_statistics.hpp, src/lib/storage/table.cpp, src/lib/storage/table.hpp, src/test/operators/delete_test.cpp, src/test/operators/update_test.cpp
=> Move invalid row count to TableStatistics

src/lib/operators/projection.cpp, src/test/operators/projection_test.cpp
=> Catch division by zero

src/bin/console/console.cpp
=> Fix Console not throwing error when trying to script dirname

src/benchmark/operators/sql_benchmark.cpp, src/lib/sql/abstract_cache.hpp, src/lib/sql/gdfs_cache.hpp, src/lib/sql/gds_cache.hpp, src/lib/sql/lru_cache.hpp, src/lib/sql/lru_k_cache.hpp, src/lib/sql/random_cache.hpp, src/lib/sql/sql_query_cache.hpp, src/test/sql/sql_basic_cache_test.cpp, src/test/sql/sql_prepare_execute_test.cpp, src/test/sql/sql_query_operator_test.cpp, src/test/sql/sql_query_plan_cache_test.cpp, src/test/sql/sql_query_plan_test.cpp
Adds resize method and fixes #619
=> Add query plan cache resize() and fix memory access in random_cache

src/lib/logical_query_plan/abstract_lqp_node.cpp, src/lib/logical_query_plan/lqp_translator.cpp, src/lib/logical_query_plan/mock_node.cpp, src/lib/logical_query_plan/union_node.cpp, src/lib/operators/abstract_operator.cpp, src/lib/operators/abstract_read_write_operator.cpp, src/lib/operators/import_binary.cpp, src/lib/operators/maintenance/create_view.cpp, src/lib/operators/maintenance/drop_view.cpp, src/lib/operators/projection.cpp, src/lib/operators/table_scan/is_null_table_scan_impl.cpp, src/lib/operators/table_scan/single_column_table_scan_impl.cpp, src/lib/operators/table_scan/single_column_table_scan_impl.hpp, src/lib/operators/validate.cpp, src/lib/scheduler/operator_task.cpp, src/lib/sql/sql_translator.cpp, src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_nodes.cpp, src/lib/storage/iterables/reference_column_iterable.hpp, src/lib/storage/reference_column.cpp, src/lib/storage/table.cpp, src/lib/storage/table.hpp, src/lib/utils/assert.hpp, src/test/optimizer/strategy/predicate_reordering_test.cpp
This allows us to omit these "make the compiler happy" return statements.
=> Make Fail() [[noreturn]]

src/lib/planviz/abstract_visualizer.hpp
Fixes #565.
graphviz layouting is not perfect, but the query from #565 is now readable, so this should do it. I have no idea why the box is so big around the text though...
PS: I am aware that 50 is a rather arbitrary line width but I tried a few and it looked good on my machine.
=> Wrap long lines in visualizer

src/lib/operators/projection.cpp, src/lib/storage/chunk.cpp, src/lib/storage/chunk.hpp
=> Remove Chunk::use_mvcc_columns_from()

Jenkinsfile, src/test/operators/physical_query_plan_test.cpp
fixes #646 and https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/organizations/jenkins/Hyrise%2Fhyrise/detail/max%2Fremove_dictionary_compression_class/14/pipeline/71
=> Improve test isolation in physical_query_plan_test.cpp

src/lib/CMakeLists.txt, src/lib/logical_query_plan/abstract_lqp_node.cpp, src/lib/logical_query_plan/abstract_lqp_node.hpp, src/lib/operators/abstract_operator.cpp, src/lib/operators/abstract_operator.hpp, src/lib/operators/abstract_read_write_operator.hpp, src/lib/operators/delete.cpp, src/lib/operators/insert.cpp, src/lib/utils/print_directed_acyclic_graph.hpp, src/test/concurrency/transaction_context_test.cpp, src/test/operators/physical_query_plan_test.cpp
Introduces an utility function to perform the printing of DAG-like structures such as the LQP and PQP (soon to include JoinPlans)
=> Print Acyclic Directed Graphs

src/test/sql/sql_translator_test.cpp
=> Use int64_t instead of long

src/lib/operators/jit_operator/jit_types.hpp, src/lib/operators/table_scan/like_table_scan_impl.cpp
Follow up on #709 to incorporate feedback from @mjendruk and @lawben
=> JIT: PR feedback 2.1

src/lib/CMakeLists.txt, src/lib/operators/abstract_operator.cpp, src/lib/planviz/sql_query_plan_visualizer.cpp, src/lib/utils/format_duration.cpp, src/lib/utils/format_duration.hpp
In AbstractOperator::print() and SQLQueryPlanVisualizer. Much win.
=> Format duration

src/lib/CMakeLists.txt, src/lib/operators/projection.cpp, src/lib/operators/projection.hpp, src/lib/storage/column_iterables.hpp, src/lib/storage/deprecated_dictionary_column.cpp, src/lib/storage/deprecated_dictionary_column.hpp, src/lib/storage/materialize.hpp, src/lib/storage/reference_column.hpp, src/lib/storage/value_column.cpp, src/lib/storage/value_column.hpp, src/test/CMakeLists.txt, src/test/storage/encoding_test.hpp, src/test/storage/materialize_test.cpp
=> Column type independent materialize()

src/benchmarklib/tpch/tpch_queries.cpp, src/benchmarklib/tpch/tpch_queries.hpp
Deactivated for now due to lack of functionality.
Closes #688.
=> Add TPCH 22 query

src/benchmark/operators/sql_benchmark.cpp, src/benchmark/table_generator.hpp, src/test/sql/sqlite_testrunner/sqlite_testrunner.tables
=> Fix query in SQLBenchmark

src/lib/planviz/lqp_visualizer.cpp, src/lib/planviz/lqp_visualizer.hpp, src/lib/planviz/sql_query_plan_visualizer.cpp, src/lib/planviz/sql_query_plan_visualizer.hpp
Before edges where drawn multiple times
=> Fix PQP/LQP Visualizers for diamond shapes

src/lib/planviz/abstract_visualizer.hpp
I have seen a lot of people who save the visualization in a file. On the transparent background, it is hard to read.
=> Make visualization background black

src/lib/optimizer/base_column_statistics.cpp, src/lib/optimizer/base_column_statistics.hpp, src/lib/optimizer/column_statistics.cpp, src/lib/optimizer/table_statistics.cpp, src/lib/optimizer/table_statistics.hpp, src/test/optimizer/strategy/predicate_reordering_test.cpp, src/test/optimizer/table_statistics_test.cpp
Please just give this your approval and don't look at the TableStatistics code in general, it's horrifying
=>  TableStatistics: TableType and column DataType 

src/test/operators/physical_query_plan_test.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner.tables, src/test/sql/sqlite_testrunner/sqlite_testrunner_queries.sql, src/test/tables/sqlite/id_int_int_int_100.tbl
=> Fix SqliterRunner queries

src/benchmark/tpch_benchmark.cpp
Visualize PQPs and LQPs for TPCH queries. Comes in handy for me, might be useful to you.
=> TPCHBenchmark --visualize option

cmake/EmbedLLVM.cmake
=> Portable include path for JIT EmbedLLVM

CMakeLists.txt
See https://stackoverflow.com/a/30468391
=> [JIT Internal] Correct clang compiler flag of --export-dynamic to -export_dynamic

src/bin/console/console.cpp
=> Disable pagination if TERM is not set

cmake/FindPQ.cmake
=> Fix libpq include on OSX

src/test/CMakeLists.txt, src/test/server/server_test_runner.cpp
Closes #852.
Maybe this also helps with #853, but that is a different matter. We will need to keep a lookout for that.
=> Move server_test_runner to systemTest

scripts/coverage.sh, src/lib/utils/numa_memory_resource.cpp, src/test/statistics/statistics_import_export_test.cpp, src/test/utils/numa_memory_resource_test.cpp
=> Fix NUMA test, improve isolation

src/lib/planviz/lqp_visualizer.hpp, src/lib/planviz/sql_query_plan_visualizer.hpp
=> Add defaults to visualizer constructor

src/benchmark/CMakeLists.txt
=> Rename hyriseOperatorBenchmark to hyriseMicroBenchmarks

src/lib/sql/random_cache.hpp
This should fix #922. @FabianWiebe could you double check that with your sanitizer?
=> Fix RandomCache's eviction bug

CMakeLists.txt
=> Fix non-NUMA-builds

CMakeLists.txt, Jenkinsfile, src/lib/statistics/chunk_statistics/chunk_column_statistics.cpp, src/lib/statistics/chunk_statistics/chunk_column_statistics.hpp, src/lib/storage/chunk.cpp, src/lib/storage/chunk.hpp, src/lib/storage/chunk_encoder.cpp
=> Fix unencoded TPCH Benchmarks

scripts/coverage.sh
Changed the tool to get coverage percentage. The tool introduced in #953 didn't have a working option to limit the files for coverage calculation.
=> Fixed coverage percentage calculation

Jenkinsfile, install.sh
* Jenkins: never cancel master builds 
* install.sh: Warn on unsupported OS, closes #989
=> Small jenkins and install.sh improvements

src/test/operators/aggregate_test.cpp
1. I have no idea what `test_output` did with that set of ColumnIDs, except randomly scanning on Columns. How did that make sense? I changed the function to perform just a single scan to produce the reference table.
2. I have no clue why this never came up in memcheck-CI
Anyway: Valgrind just locally informed me of a uninitialised variable in
```c++
-      for (const auto& agg : aggregates) {
-        ref_columns.insert(*agg.column);
-      }
```
and sure enough, a test introduced two months ago (@mrks) hands in a std::nullopt here, from which 
`*agg.column` tries to retrieve a value.
```c++
TEST_F(OperatorsAggregateTest, TwoAggregateEmptyTable) {
auto filtered = std::make_shared<TableScan>(_table_wrapper_1_2, ColumnID{0}, PredicateCondition::LessThan, 0);
filtered->execute(); …
```
=> Fix AggregateTest

src/bin/console/console.cpp
=> Fix execution times in visualization

Jenkinsfile
This should fix the current matser fail
=> Fix test isolation on Jenkins

src/lib/operators/print.cpp, src/lib/operators/print.hpp, src/test/operators/print_test.cpp
I found a local branch that tried to tackle the after-closing discussion of #553 .
This + two previously untested methods.
=> Slightly improved testing of print operator

src/lib/CMakeLists.txt, src/lib/sql/sql_pipeline_statement.cpp
=> Fix always creating new dtrace header file

src/bin/console/console.cpp
Fixes #1101 
...and also some refactoring because I found the code hard to read.
=> Fix crash in console when visualizing with anything to visualize

src/bin/console/console.cpp
As suggsted by @lanice, up to discussion
After #1102 is merged.
=> Allow visualize {exec, pqp} in console

src/lib/scheduler/abstract_task.hpp
=> Make AbstractTask members atomic to silence TSAN

src/lib/scheduler/abstract_task.cpp
=> Try fix dtrace

src/lib/statistics/table_statistics.cpp, src/test/statistics/table_statistics_test.cpp
=> Fix search&replace error

src/lib/CMakeLists.txt
=> Fix dtrace provider file generation.

src/lib/statistics/column_statistics.cpp, src/test/statistics/column_statistics_test.cpp
=> Fix two-column scan statistics

cmake/FindFS.cmake, src/test/CMakeLists.txt, third_party/CMakeLists.txt
Hyrise wouldn't build anymore after `brew upgrade`.
=> Some adaptions for llvm7 under macOS

src/lib/operators/jit_operator/jit_operations.hpp, src/test/operators/jit_operator/jit_operations_test.cpp
=> Make jit (NOT) LIKE case sensitive

third_party/tpch-dbgen/dss.h
=> "Repair" pagination

src/bin/console/console.cpp, src/bin/console/console.hpp
Tests should be added as part of #1103.
=> Add functionality to load and export binary files in console

src/lib/logical_query_plan/show_columns_node.cpp, src/lib/logical_query_plan/show_columns_node.hpp, src/test/logical_query_plan/show_columns_node_test.cpp, src/test/logical_query_plan/show_tables_node_test.cpp, src/test/sql/sql_translator_test.cpp
Fixes #1137
Tests preventing this type of bug will either come with the console tests or if we ever implement SQL to Table tests again.
=> Fix SHOW COLUMNS

src/lib/scheduler/abstract_task.cpp, src/lib/utils/tracing/probes.hpp
I want to get some FullCI runs because we are unable to reproduce the issue on any of our other servers.
=> Try fixing TSan false positive

Jenkinsfile, src/bin/console/console.cpp
Small changes needed for a new CI server:
* The new docker needs privileged mode for NUMA
* 50GB ramdisk for ccache
* Don't run clang-tidy on `src/test` as we ignore that folder anyway
=> Prepare new CI

src/lib/sql/sql_pipeline.cpp, src/lib/sql/sql_pipeline_statement.cpp, src/lib/sql/sql_pipeline_statement.hpp, src/test/sql/sql_pipeline_statement_test.cpp, src/test/sql/sql_pipeline_test.cpp
=> Rename 'optimize' time to 'lqp translate' time

src/lib/operators/print.cpp, src/test/operators/print_test.cpp
Fixes #1219.
Shall I wait for #1209 and merge the changes when #1209 is in the master?
=> Improve print testing

src/lib/storage/dictionary_segment.cpp, src/lib/storage/dictionary_segment.hpp, src/lib/storage/dictionary_segment/attribute_vector_iterable.hpp, src/lib/storage/dictionary_segment/dictionary_segment_iterable.hpp, src/lib/storage/fixed_string_dictionary_segment.cpp, src/lib/storage/fixed_string_dictionary_segment.hpp, src/lib/storage/frame_of_reference/frame_of_reference_encoder.hpp, src/lib/storage/frame_of_reference/frame_of_reference_iterable.hpp, src/lib/storage/frame_of_reference_segment.cpp, src/lib/storage/frame_of_reference_segment.hpp, src/lib/storage/index/group_key/composite_group_key_index.cpp, src/lib/storage/vector_compression/base_compressed_vector.hpp, src/lib/storage/vector_compression/base_vector_compressor.hpp, src/lib/storage/vector_compression/fixed_size_byte_aligned/fixed_size_byte_aligned_compressor.cpp, src/lib/storage/vector_compression/fixed_size_byte_aligned/fixed_size_byte_aligned_compressor.hpp, src/lib/storage/vector_compression/fixed_size_byte_aligned/fixed_size_byte_aligned_vector.hpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_compressor.cpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_compressor.hpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_decompressor.cpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_decompressor.hpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_vector.cpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_vector.hpp, src/lib/storage/vector_compression/vector_compression.cpp, src/lib/storage/vector_compression/vector_compression.hpp, src/test/storage/compressed_vector_test.cpp, src/test/storage/simd_bp128_test.cpp
Vector compression -> compressor/decompressor
Segments -> encoder/decoder
fixes #1168
=> Disambiguate decoder/decompressor

src/test/storage/btree_index_test.cpp
Ye olde documentation got out of sync with the code.
refs #1271 #1266
=> Fix assertion description in btree_index_text.cpp

src/lib/all_parameter_variant.cpp, src/lib/all_parameter_variant.hpp, src/test/lib/all_parameter_variant_test.cpp
=> Remove LQPColumnReference from AllParameterVariant

src/benchmarklib/benchmark_runner.cpp
=> Fix visualization

src/lib/import_export/csv_meta.cpp, src/test/csv/null_literal.csv, src/test/csv/null_literal.csv.json, src/test/operators/import_csv_test.cpp
=> Expose reject_null_strings to CSV JSON meta

src/benchmark/file_based_benchmark.cpp
=> Fix chunk size for file-based benchmarks

src/bin/console/console.cpp, src/lib/import_export/csv_parser.cpp, src/test/csv/float_int_empty.csv.json, src/test/operators/import_csv_test.cpp, src/test/tables/float_int_empty.tbl
=> Allow import of empty CSV

README.md
=> Add Codefactor

cmake/FindFS.cmake
=> Fix FindFS library for gcc-8

src/test/CMakeLists.txt, src/test/base_test.hpp, src/test/expression/expression_test.cpp, src/test/expression/lqp_select_expression_test.cpp, src/test/expression/pqp_select_expression_test.cpp, src/test/logical_query_plan/delete_node_test.cpp, src/test/logical_query_plan/jit_aware_lqp_translator_test.cpp, src/test/logical_query_plan/logical_query_plan_test.cpp, src/test/logical_query_plan/lqp_find_subplan_mismatch_test.cpp, src/test/logical_query_plan/lqp_translator_test.cpp, src/test/logical_query_plan/lqp_utils_test.cpp, src/test/logical_query_plan/predicate_node_test.cpp, src/test/logical_query_plan/sort_node_test.cpp, src/test/operators/update_test.cpp, src/test/optimizer/join_graph_builder_test.cpp, src/test/optimizer/lqp_translator_test.cpp, src/test/sql/sql_identifier_resolver_test.cpp, src/test/sql/sql_translator_test.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
=> Remove unnecessary TearDowns, doc BaseTest tear down

Jenkinsfile
Hopefully, this finally fixes the permission issue on Jenkins...
=> Fix check for PR

src/lib/import_export/csv_parser.cpp, src/lib/import_export/csv_parser.hpp
The is not the "fast" CSV parser you are looking for. But it reduces the loading time of a 600MB CSV into memory from 1,7s to 0,4s.
The actual parsing still takes ~20s for this file.
=> Faster CSV loading

src/test/server/server_test_runner.cpp
I am fed up with retriggering Jenkins all the time. If anybody has a better solution (actual fix/proper santitizer ignore) available SOON, come forward.
=> Disable ServerTestRunner

resources/test_data/sqlite_testrunner_queries.sql, src/lib/expression/evaluation/expression_evaluator.cpp, src/test/expression/expression_evaluator_to_pos_list_test.cpp, src/test/logical_query_plan/lqp_utils_test.cpp
=> Fix EvaluateToPosList for uncorrelated EXISTS

src/benchmark/file_based_benchmark.cpp, src/benchmark/join_order_benchmark.cpp, src/benchmark/tpch_benchmark.cpp, src/benchmarklib/abstract_table_generator.cpp, src/benchmarklib/benchmark_config.cpp, src/benchmarklib/benchmark_config.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/benchmark_table_encoder.cpp, src/benchmarklib/benchmark_table_encoder.hpp, src/benchmarklib/cli_config_parser.cpp, src/benchmarklib/cli_config_parser.hpp, src/benchmarklib/file_based_table_generator.cpp, src/benchmarklib/tpcc/tpcc_table_generator.cpp, src/lib/operators/table_scan.cpp
=> Benchmarks: Remove --verbose, remove JSON from output, shorten --help

src/benchmarklib/abstract_table_generator.cpp
=> Fix logging whether tables were encoded or not during Benchmark setup

src/bin/CMakeLists.txt, src/lib/CMakeLists.txt, src/plugins/CMakeLists.txt
=> Proper libHyrise linking for plugins

src/lib/operators/join_sort_merge/radix_cluster_sort.hpp
=> Fix ASAN issue in sort-merge join

resources/tpch_validation_queries.sql
Fixes #1411. If we decide to merge this, I will add a note to https://github.com/hyrise/hyrise/wiki/TPCH as well.
=> Add TPC-H example query file

src/benchmark/CMakeLists.txt, src/bin/CMakeLists.txt, src/lib/CMakeLists.txt, src/lib/utils/pausable_loop_thread.hpp
See #1461 which was not modifiabl.
=> Include all symbols when linking against libHyrise

src/benchmarklib/tpch/tpch_query_generator.cpp
=> Fixes incorrect parameter generation for TPCH 22

scripts/compare_benchmarks.py
=> Compare Benchmarks: Handle mismatching names gracefully

src/lib/constant_mappings.cpp, src/test/logical_query_plan/sort_node_test.cpp
This is currently part of #1394, but since its kinda unrelated, I thought it'd be easier to split this off into a separate PR.
=> Add missing Ascending/DescendingNullsLast to order_by_mode_to_string

src/lib/optimizer/strategy/chunk_pruning_rule.cpp, src/lib/optimizer/strategy/chunk_pruning_rule.hpp, src/test/optimizer/strategy/chunk_pruning_test.cpp
=> Allow ChunkPruningRule to prune past non-filtering operators 

src/lib/storage/dictionary_segment/attribute_vector_iterable.hpp, src/lib/storage/dictionary_segment/dictionary_segment_iterable.hpp, src/lib/storage/frame_of_reference/frame_of_reference_iterable.hpp, src/lib/storage/lz4/lz4_iterable.hpp, src/lib/storage/reference_segment/reference_segment_iterable.hpp, src/lib/storage/run_length_segment/run_length_segment_iterable.hpp, src/lib/storage/segment_iterables/any_segment_iterator.hpp, src/lib/storage/segment_iterables/base_segment_iterators.hpp, src/lib/storage/value_segment/null_value_vector_iterable.hpp, src/lib/storage/value_segment/value_segment_iterable.hpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_iterator.cpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_iterator.hpp, src/test/storage/segment_iterators_test.cpp
While working at #1394, we noticed that it would be nice to be able to rewind segment iterators. This PR makes all iterators rewindable.
=> Rewindable segment iterators

resources/test_data/sqlite_testrunner_queries.sql
Fix #1527
#1541 has very probably fixed it.
=> Add test queries verifying that #1527 was fixed

cmake/git_watcher.cmake
=> Fix make clean

src/benchmark/file_based_benchmark.cpp, src/benchmark/join_order_benchmark.cpp, src/lib/utils/check_table_equal.cpp
=> Better documentation for --table_path option

src/bin/server.cpp, src/lib/server/server_session.cpp, src/lib/utils/assert.hpp, src/test/server/server_session_test.cpp, src/test/statistics/chunk_statistics/counting_quotient_filter_test.cpp
=> Print file/line info for Fail()

src/lib/logical_query_plan/drop_table_node.cpp, src/lib/logical_query_plan/drop_table_node.hpp, src/lib/logical_query_plan/drop_view_node.cpp, src/lib/logical_query_plan/drop_view_node.hpp, src/lib/logical_query_plan/lqp_translator.cpp, src/lib/operators/maintenance/drop_table.cpp, src/lib/operators/maintenance/drop_table.hpp, src/lib/operators/maintenance/drop_view.cpp, src/lib/operators/maintenance/drop_view.hpp, src/lib/sql/sql_translator.cpp, src/test/logical_query_plan/drop_table_node_test.cpp, src/test/logical_query_plan/drop_view_node_test.cpp, src/test/logical_query_plan/lqp_translator_test.cpp, src/test/operators/maintenance/drop_table_test.cpp, src/test/operators/maintenance/drop_view_test.cpp, src/test/sql/sql_translator_test.cpp
=> Add IF EXISTS support for DROP TABLE and DROP VIEW

src/lib/statistics/column_statistics.cpp, src/lib/statistics/table_statistics.cpp
=> Add new Between modes to ColumnStatistics

src/benchmark/join_order_benchmark.cpp, src/benchmarklib/abstract_table_generator.cpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/benchmark_runner.hpp, src/lib/utils/sqlite_wrapper.cpp, src/lib/utils/sqlite_wrapper.hpp
=> Use indexes for SQLite verification of join order benchmark

src/benchmarklib/tpch/tpch_query_generator.cpp
=> TPC-H 6: Calculate discount only once

src/lib/operators/print.cpp, src/lib/operators/print.hpp, src/test/operators/print_test.cpp, src/test/operators/table_scan_test.cpp
=> Print: Remove handling of empty chunks

src/lib/storage/dictionary_segment.cpp, src/lib/storage/dictionary_segment.hpp
fixes #1471 if everyone is happy
=> Clarify INVALID_VALUE_ID

src/lib/expression/function_expression.cpp, src/test/expression/expression_test.cpp
=> Remove Space after Comma in SUBSTR Column

src/lib/utils/check_table_equal.cpp, src/test/CMakeLists.txt, src/test/lib/utils/verify_tables_test.cpp
=> Verification: Case Insensitive Column Name Comparison

.gitmodules, DEPENDENCIES.md, src/CMakeLists.txt
Close hyrise-mp/hyrise#48
This PR adds the queries for verification against TPC-DS's standard answer set.
=> Add filled query templates

src/lib/statistics/cardinality_estimator.cpp, src/test/statistics/cardinality_estimator_test.cpp
=> Handle StaticTableNode in Cardinality Estimator

src/benchmarklib/benchmark_sql_executor.cpp
=> Visualize multiple LQPs/PQPs in one file

src/benchmarklib/abstract_benchmark_item_runner.cpp, src/benchmarklib/abstract_benchmark_item_runner.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp, src/benchmarklib/tpch/tpch_benchmark_item_runner.hpp, src/test/tpc/tpch_test.cpp
=> TPC-H: Fix prepared statements

src/lib/operators/join_sort_merge.cpp
Fix a message in the assert of the JoinSortMerge.
=> Fix assert message

scripts/benchmark_multithreaded.py
=> Fix benchmark_multithreaded.py

src/lib/logical_query_plan/alias_node.cpp, src/lib/logical_query_plan/create_view_node.cpp, src/test/logical_query_plan/create_view_node_test.cpp
=> Make CreateViewNode debug info more informative

src/lib/logical_query_plan/create_view_node.cpp
Only a temporary fix until #1748 is resolved.
=> Fix the master

third_party/CMakeLists.txt
fixes #1674. Don't get me started on Apple's build environment.
=> Mac: Fix build environment for jemalloc

src/test/operators/index_scan_test.cpp
=> Fix Union operator in index scan test

src/benchmarklib/abstract_table_generator.cpp, src/lib/optimizer/strategy/index_scan_rule.cpp, src/test/optimizer/strategy/index_scan_rule_test.cpp
Fixes #1762 
Test was added which reveals the failure.
=> Column pruning sensitive index scan

src/lib/storage/lz4_segment/lz4_segment_iterable.hpp, src/test/storage/segment_iterators_test.cpp
=> Add tests for random access iterators

resources/benchmark/tpcds/query_blacklist.cfg
=> Disable TPC-DS Q85

.gitmodules, src/benchmark/tpcds_benchmark.cpp
=> Move TPC-DS query submodule to resources

resources/benchmark/tpcds/query_blacklist.cfg
~~Close hyrise-mp/hyrise/issues/63~~ --> Now in #1826 due to avoid weird merge conflict in submodule
~~Close hyrise-mp/hyrise/issues/67~~ --> same
**Changes**
- Execute six more queries, which became possible by https://github.com/hyrise/hyrise/pull/1693.
- ~~Update reference to submodule~~
=> Remove executable queries from blacklist

scripts/setup_imdb.py
=> Update md5 hash of IMDB data

src/lib/expression/expression_utils.hpp, src/lib/sql/sql_identifier_resolver.cpp, src/lib/sql/sql_identifier_resolver.hpp, src/lib/sql/sql_translator.cpp, src/test/sql/sql_identifier_resolver_test.cpp, src/test/sql/sql_translator_test.cpp
fixes #1771
fixes #1820
fixes #1799
=> Two expression resolution fixes in SQLTranslator

src/test/logical_query_plan/lqp_translator_test.cpp
=> Sub-Plan Memoization Test

src/test/optimizer/strategy/in_expression_rewrite_rule_test.cpp
=> Make DisjunctionStrategy test deterministic

src/lib/optimizer/optimizer.cpp, src/lib/storage/storage_manager.cpp
Previously it sounded like the JOR was introducing semi joins
=> Improve doc wording in Optimizer and StorageManager

Jenkinsfile, resources/benchmark/tpcds/query_blacklist.cfg, src/benchmarklib/benchmark_runner.cpp, src/lib/statistics/statistics_objects/min_max_filter.cpp, src/test/statistics/statistics_objects/min_max_filter_test.cpp
=> Fix TPC-DS 91, blacklist 88, add to CI

resources/benchmark/tpcds/query_blacklist.cfg, resources/test_data/sqlite_testrunner_queries.sql, resources/test_data/tbl/sqlite/mixed_types_100.tbl, src/lib/statistics/cardinality_estimator.cpp
=> Fix column vs column on strings

scripts/test/hyriseBenchmarkJoinOrder_test.py, src/benchmarklib/benchmark_runner.cpp, src/lib/scheduler/abstract_task.cpp, src/lib/statistics/statistics_objects/range_filter.cpp
=> Fix empty RangeFilter

scripts/test/hyriseBenchmarkTPCH_test.py, src/benchmarklib/benchmark_config.cpp, src/benchmarklib/benchmark_config.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/cli_config_parser.cpp
=> Benchmark: make --runs default to infinity

src/test/server/server_test_runner.cpp
=> Test SQL COPY import end-to-end

src/lib/optimizer/strategy/chunk_pruning_rule.cpp, src/lib/statistics/statistics_objects/min_max_filter.cpp, src/lib/statistics/statistics_objects/min_max_filter.hpp, src/lib/statistics/statistics_objects/range_filter.cpp, src/lib/statistics/statistics_objects/range_filter.hpp
Mostly improves the documentation, only minor code changes.
fixes #1701
@Bouncner, I added two questions - could you address those as part of your review, please?
=> Minor refactorings for RangeFilter and MinMaxFilter

README.md, src/lib/CMakeLists.txt, src/lib/operators/delete.hpp, src/lib/operators/index_scan.hpp, src/lib/operators/insert.hpp, src/lib/operators/join_index.hpp, src/lib/operators/join_nested_loop.hpp, src/lib/operators/table_scan/abstract_table_scan_impl.hpp, src/lib/operators/table_scan/sorted_segment_search.hpp, src/lib/operators/union_positions.hpp, src/lib/resolve_type.hpp, src/lib/storage/lz4_segment.hpp, src/lib/storage/pos_lists/row_id_pos_list.cpp, src/lib/storage/pos_lists/row_id_pos_list.hpp, src/lib/storage/reference_segment.hpp, src/lib/storage/segment_access_counter.hpp, src/lib/storage/segment_iterables/base_segment_iterators.hpp, src/lib/storage/segment_iterate.hpp, src/lib/storage/split_pos_list_by_chunk_id.hpp, src/plugins/mvcc_delete_plugin.cpp, src/test/lib/entire_chunk_pos_list_test.cpp
Renames the RowIdPosList file, renames minor variables, and adds the SmartPosList team to the contributors. These changes were originally part of #2026.
This PR replaces #2076, which cannot be built until leogeier accepts the Hyrise team membership.
=> [DYOD] Smart Position List: Finalize smart PosList

src/lib/server/server.cpp, src/lib/server/server.hpp, src/test/server/server_test_runner.cpp
=> Fix ServerTestRunner

resources/.tsan-ignore.txt, resources/.ubsan-blacklist.txt, src/lib/CMakeLists.txt, third_party/CMakeLists.txt
=> Fix ubsan/tsan on Mac

src/bin/console/console.cpp, src/bin/console/pagination.cpp, src/bin/console/pagination.hpp
closes #2106.
adds horizontal scrolling in console.
=> Console: Horizontal Scrolling

src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp, src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.hpp, src/lib/optimizer/join_ordering/dp_ccp.hpp, src/lib/optimizer/join_ordering/greedy_operator_ordering.hpp, src/lib/optimizer/strategy/join_ordering_rule.hpp, src/lib/optimizer/strategy/join_predicate_ordering_rule.hpp
=> Clarify join predicate order

scripts/setup_imdb.py
https://archive.org/details/imdb_20200624
=> Move the JOB's IMDB files from a private dropbox to the archive

scripts/setup_imdb.py
I made a mistake while zipping the files. The new, corrected version has a different hash. Sorry for spamming.
=> Fix IMDB file hash

src/lib/storage/segment_access_counter.cpp
Really small optimization that I just thought of while writing about it. The code speaks for itself. I won't add any benchmarks as the counters are too fast for any meaningful benchmarks. Still, we should not do unnecessary work.
=> Add segment accessor shortcut

scripts/plot_performance_over_time.py
=> Fix exception in plot_performance_over_time.py

Jenkinsfile
=> Adjust CI stage to generate TPC-H Q15 query plans

scripts/plot_operator_breakdown.py, src/lib/operators/abstract_operator.cpp
=> plot_operator_breakdown: Remove relative share, fix warning

Jenkinsfile
Forgot that the master has no PR info :/
Also, by using a different user, I want to verify that non-Hyrise-Members cannot immediately have their code executed by Jenkins.
=> Fix Jenkins 2.0

src/lib/operators/table_scan/column_vs_column_table_scan_impl.cpp, src/lib/storage/reference_segment/reference_segment_iterable.hpp
=> Kill SingleChunkIterator

scripts/benchmark_all.sh
Fixing titles in the output and added the used scale factor to all TPC-H results.
=> Fix titles in GitHub output of benchmark_all.sh

src/lib/utils/sqlite_add_indices.cpp
=> Better error message for --verify

src/lib/operators/abstract_read_write_operator.cpp, src/test/lib/operators/delete_test.cpp
=> Fix OperatorsDeleteTest.UseTransactionContextAfterCommit

Jenkinsfile
Fixes
> Error response from daemon: toomanyrequests: You have reached your pull rate limit.
> You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
=> Jenkinsfile: Use credentials for docker.com

scripts/setup_imdb.py
I also updated the JSON files describing the schema of the IMDB tables. Some `nullable` declarations were not correct.
=> Update imdb data link and md5 hash

src/lib/sql/sql_translator.cpp, src/test/lib/sql/sql_translator_test.cpp
This PR upgrades the SQL parser to the latest version, which requires some changes in the SQL translator.
=> Upgrade SQL-parser version

src/benchmark/micro_benchmark_basic_fixture.cpp, src/benchmark/operators/aggregate_benchmark.cpp, src/benchmark/operators/join_aggregate_benchmark.cpp, src/benchmark/operators/join_benchmark.cpp, src/benchmark/operators/sort_benchmark.cpp, src/benchmark/operators/table_scan_benchmark.cpp, src/benchmark/operators/table_scan_sorted_benchmark.cpp, src/benchmark/operators/union_positions_benchmark.cpp, src/benchmark/tpch_data_micro_benchmark.cpp
=> Fix hyriseMicroBenchmarks

src/lib/logical_query_plan/enable_make_for_lqp_node.hpp
Improve code readability & Doc.
=> Refactor EnableMakeForLQPNode

CONTRIBUTING.md
Add note to contributor guidelines.
PS: there have been discussion about lang-tidy rules, but to my knowledge there are no rules available yet.
=> Guidelines: prefer pre-increment

README.md
It's sad to leave the team of the best database of the world. Keep it up!
=> Jan's Retirement

src/benchmark/CMakeLists.txt
Recent discussions showed that the modified comment is unclear, which is to be improved with this nano PR.
=> Google Benchmark as System Lib: Clarify Comment

CONTRIBUTING.md
=> DYOD preparation: Fix style of style guide

scripts/test/hyriseServer_test.py, src/benchmarklib/tpcc/procedures/abstract_tpcc_procedure.cpp, src/benchmarklib/tpcc/procedures/tpcc_stock_level.cpp
=> Align TPC-C's Stock-Level with the standard's example procedure

scripts/setup_imdb.py
Fixes the problem described in #2667.
Alternatively, the `imdb_data` folder could be removed from the zip-file.
What are your opinions on this?
=> Exchange `imdb_data.zip` and change its host

src/lib/operators/sort.cpp
Implemented parts of the review of the DYOD 2025 seminar feedback for group 1
=> [DYOD 2025] implement Group 1 review [WIP]
