Jenkinsfile, src/CMakeLists.txt, src/lib/CMakeLists.txt
For safety, Jenkins should also check if the non-NUMA version works. Instead of doubling its efforts, it should be enough to just compile and run the sanitized clang-release build. That should catch most problems.
=> Make Jenkins build a non-NUMA version

Jenkinsfile, src/CMakeLists.txt
We are using __FILE__ in our DebugAsserts. Since Jenkins always creates a new path for everything, we should ignore those changes.
=> Make ccache fast again

src/bin/CMakeLists.txt, src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.cpp, src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.hpp, src/lib/optimizer/abstract_syntax_tree/aggregate_node.cpp, src/lib/optimizer/abstract_syntax_tree/aggregate_node.hpp, src/lib/optimizer/abstract_syntax_tree/ast_root_node.cpp, src/lib/optimizer/abstract_syntax_tree/delete_node.cpp, src/lib/optimizer/abstract_syntax_tree/dummy_table_node.cpp, src/lib/optimizer/abstract_syntax_tree/insert_node.cpp, src/lib/optimizer/abstract_syntax_tree/join_node.cpp, src/lib/optimizer/abstract_syntax_tree/join_node.hpp, src/lib/optimizer/abstract_syntax_tree/limit_node.cpp, src/lib/optimizer/abstract_syntax_tree/mock_table_node.cpp, src/lib/optimizer/abstract_syntax_tree/mock_table_node.hpp, src/lib/optimizer/abstract_syntax_tree/predicate_node.cpp, src/lib/optimizer/abstract_syntax_tree/projection_node.cpp, src/lib/optimizer/abstract_syntax_tree/projection_node.hpp, src/lib/optimizer/abstract_syntax_tree/show_columns_node.cpp, src/lib/optimizer/abstract_syntax_tree/show_tables_node.cpp, src/lib/optimizer/abstract_syntax_tree/sort_node.cpp, src/lib/optimizer/abstract_syntax_tree/stored_table_node.cpp, src/lib/optimizer/abstract_syntax_tree/stored_table_node.hpp, src/lib/optimizer/abstract_syntax_tree/update_node.cpp, src/lib/optimizer/abstract_syntax_tree/validate_node.cpp
Because YOU are not good at dealing with ColumnIDs
```
[Sort] revenue (Descending)
\_[Projection] revenue, nation.n_name
\_[Aggregate] SUM(lineitem.l_extendedprice * (1 - lineitem.l_discount)) AS "revenue" GROUP BY [nation.n_name]
\_[Predicate] orders.o_orderdate < 1995-01-01
\_[Predicate] orders.o_orderdate >= 1994-01-01
\_[Predicate] region.r_name = ASIA
\_[Predicate] nation.n_regionkey = region.r_regionkey
\_[Predicate] supplier.s_nationkey = nation.n_nationkey
\_[Predicate] customer.c_nationkey = supplier.s_nationkey
\_[Predicate] lineitem.l_suppkey = supplier.s_suppkey
\_[Predicate] lineitem.l_orderkey = orders.o_orderkey
\_[Predicate] customer.c_custkey = orders.o_custkey
\_[Cross Join]
\_[Cross Join]
|  \_[Cross Join]
|  |  \_[Cross Join]
|  |  |  \_[Cross Join]
|  |  |  | …
```
=> Make AST printing support column names

src/lib/operators/abstract_operator.cpp, src/lib/scheduler/operator_task.cpp
If the TX is already gone, no operator should be executed. This also fixes #76 because the second update will not be executed.
=> Don't start operator if Tx already failed

src/benchmarklib/benchmark_utilities/abstract_benchmark_table_generator.hpp, src/lib/import_export/csv_parser.cpp, src/lib/operators/import_binary.cpp, src/lib/operators/update.cpp, src/lib/storage/chunk.cpp, src/lib/storage/chunk.hpp, src/lib/storage/table.cpp
Because noone likes to read code with boolean params. Also, Chunk had too many constructors.
=> Chunk: Use enum class instead of boolean parameter

Jenkinsfile
We should use the debug build to generate the coverage reports. Otherwise, some tests done by `DebugAssert` are not part of the result.
Also, removes the non-coverage gcc-debug from the Jenkins builds. I don't think that it will find anything not caught by gcc-debug+coverage. No point in wasting CPU time here.
=> Switch coverage to debug build

src/bin/CMakeLists.txt, src/bin/playground.cpp
Doing a few playground experiments this always came in useful (if you need TPCH queries, for example) and shouldn't hurt.
=> Link playground with hyriseBenchmarkLib

src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
During #318, the changes to SqliteTestrunner @mrks made in #412 got reverted by mistake.
This restores the changes together with the transaction management introduced in #318
=> Revert changes inadvertently made to sqlite_testrunner.

src/test/storage/adaptive_radix_tree_index_test.cpp
The master does not  build under macOS with clang-5. [std::random_shuffle](http://en.cppreference.com/w/cpp/algorithm/random_shuffle) as used [here](https://github.com/hyrise/hyrise/blob/master/src/test/storage/adaptive_radix_tree_index_test.cpp) was removed in C++17 and replaced by `std::shuffle`. 
Even more important: why did this not come up on the CI?
=> Use shuffle (new signature) instead of random_shuffle

src/lib/import_export/csv_parser.cpp
There are two reasons for this: Error messages are shown during test execution which pollutes the terminal. More important, the general Hyrise error paradigm is to fail loud and early and not handling error cases while informing the user. However, the current implementation throws an exception anyways. 
One could argue that a crash during the import of the last rows of a large CSV file might be annoying for the user, but the current approach does also throw. Handling such problems could be the task of the console at some point.
=> Remove CSV parser's error message, only throw exception.

src/lib/operators/table_scan/like_table_scan_impl.cpp, src/lib/operators/table_scan/like_table_scan_impl.hpp, src/test/operators/table_scan_like_test.cpp
Currently, the TableScan supports this:
`SELECT * FROM t WHERE a LIKE 'hau[fs]en'`.
This is not part of the SQL standard and only supported by SQL Server. Since this would not work with the sqlite test, this PR removes that behavior. Also, it removes code that will not be used anyway.
The correct way to do this in an SQL query would be `REGEXP`, not `LIKE`.
=> Remove non-standard LIKE behavior

src/lib/optimizer/abstract_syntax_tree/dummy_table_node.cpp, src/lib/optimizer/abstract_syntax_tree/dummy_table_node.hpp, src/lib/optimizer/abstract_syntax_tree/union_node.cpp, src/test/CMakeLists.txt, src/test/optimizer/abstract_syntax_tree/abstract_syntax_tree_test.cpp, src/test/optimizer/abstract_syntax_tree/aggregate_node_test.cpp, src/test/optimizer/abstract_syntax_tree/delete_node_test.cpp, src/test/optimizer/abstract_syntax_tree/dummy_table_node_test.cpp, src/test/optimizer/abstract_syntax_tree/insert_node_test.cpp, src/test/optimizer/abstract_syntax_tree/join_node_test.cpp, src/test/optimizer/abstract_syntax_tree/limit_node_test.cpp, src/test/optimizer/abstract_syntax_tree/mock_node_test.cpp, src/test/optimizer/abstract_syntax_tree/predicate_node_test.cpp, src/test/optimizer/abstract_syntax_tree/projection_node_test.cpp, src/test/optimizer/abstract_syntax_tree/show_columns_node_test.cpp, src/test/optimizer/abstract_syntax_tree/show_tables_node_test.cpp, src/test/optimizer/abstract_syntax_tree/sort_node_test.cpp, src/test/optimizer/abstract_syntax_tree/stored_table_node_test.cpp, src/test/optimizer/abstract_syntax_tree/union_node_test.cpp, src/test/optimizer/abstract_syntax_tree/update_node_test.cpp, src/test/optimizer/abstract_syntax_tree/validate_node_test.cpp, src/test/optimizer/ast_to_operator_translator_test.cpp
I noticed that the AST Node classes were lacking test coverage so this PR will fix that.
As a result, the overall test coverage should reach 90.1% which means a green badge.
Note: `DummyTableNode` had most of its virtual methods removed because they are not needed.
=> More Test Coverage for AST Nodes (green badge inside)

src/bin/playground.cpp, src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.cpp, src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.hpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_queries.sql
Fix #444
Fix #328
`SELECT a, b, MAX(c), AVG(d) FROM groupby_int_2gb_2agg GROUP BY a, b HAVING MAX(c) > 457 OR MAX(c) = 1234 OR b = 12345;`
now gets printed as
```
[0] [Projection] MAX(groupby_int_2gb_2agg.c), AVG(groupby_int_2gb_2agg.d), groupby_int_2gb_2agg.a, groupby_int_2gb_2agg.b
\_[1] [UnionNode] Mode: UnionPositions
\_[2] [UnionNode] Mode: UnionPositions
|  \_[3] [Predicate] groupby_int_2gb_2agg.a > 457
|  |  \_[4] [Aggregate] MAX(groupby_int_2gb_2agg.c), AVG(groupby_int_2gb_2agg.d) GROUP BY [groupby_int_2gb_2agg.a, groupby_int_2gb_2agg.b]
|  |     \_[5] [StoredTable] Name: 'groupby_int_2gb_2agg'
|  \_[3] [Predicate] groupby_int_2gb_2agg.a = 1234
|     \_Recurring Node --> [4]
\_[2] [Predicate] AVG(groupby_int_2gb_2agg.d) = 12345
\_Recurring Node --> [4]
```
=>  AST printing and multiple parents; OR in HAVING

src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.cpp, src/lib/optimizer/abstract_syntax_tree/abstract_ast_node.hpp, src/test/optimizer/abstract_syntax_tree/abstract_syntax_tree_test.cpp
Usually fast-forward merging works. This time, it did not.
=> FIX THE MASTER, FAAAAST

src/lib/operators/index_column_scan.cpp, src/lib/storage/base_column.hpp, src/lib/storage/dictionary_column.cpp, src/lib/storage/value_column.cpp
Addresses @mrks comment in #13. We will just not support null values in `Difference` and `IndexColumnScan` for now.
closes #13
=> Add asserts for unsupported null values operations

src/lib/operators/join_nested_loop.cpp, src/lib/operators/join_sort_merge.cpp, src/lib/operators/join_sort_merge/column_materializer.hpp, src/test/operators/join_equi_test.cpp, src/test/operators/join_full_test.cpp, src/test/operators/join_null_test.cpp, src/test/tables/joinoperators/int_float_with_null_self_join.tbl
This PR tries to fix some of the errors mentioned in #306 and #314.
=> Fix some join errors 

src/lib/strong_typedef.hpp
It was brought up in the seminar that `numeric_limits` behaves weirdly for strong typedefs:
```
std::cout << std::numeric_limits<opossum::ChunkID>::min() << std::endl;
std::cout << std::numeric_limits<opossum::ChunkID>::max() << std::endl;
```
No idea what the standards committee was thinking when they made all of those methods return 0 for unknown types. This PR fixes that for strong typedefs.
If you now call methods of `numeric_limits` that the strong typedef does not forward, you will now get an error:
```
/Users/markus/Projekte/Opossum/Git/src/bin/playground.cpp: In function 'int main()':
/Users/markus/Projekte/Opossum/Git/src/bin/playground.cpp:8:55: error: 'lowest' is not a member of 'std::numeric_limits<opossum::ChunkID>'
std::cout << std::numeric_limits<opossum::ChunkID>::lowest() …
```
=> Fix numeric_limits for strong typedefs

src/benchmark/tpcc/delivery_benchmark.cpp, src/benchmarklib/tpcc/new_order.cpp, src/benchmarklib/tpcc/order_status.cpp, src/benchmarklib/tpcc/readme.md, src/benchmarklib/tpcc/tpcc_table_generator.cpp, src/scripts/tpcc_sqlite_driver.py, src/test/tpc/tpcc_ref_test.cpp
Until now, we used `ORDER-LINE` and `NEW-ORDER` as names for these TPCC tables. Some parts of the TPCC documentation use these names, but the reference implementation and documentation of statement level uses a naming version with underlines. Thereby, we can avoid to set the table names in quotes.
=> Use underline for order_line and new_order

src/benchmark/tpcc/delivery_benchmark.cpp
A call to the SortOperator utilized the old value for maximum chunk sizes `0` which leads to a failing benchmark because of this [assert](https://github.com/hyrise/hyrise/blob/master/src/lib/storage/table.cpp#L52)
=> Fix TPCC benchmark

src/lib/operators/join_sort_merge/column_materializer.hpp
The title says it all. All columns are materialized using iterables. `DictionaryColumn` has its own specialization.
=> Use iterables in sort merge join

src/lib/scheduler/abstract_task.cpp, src/lib/scheduler/abstract_task.hpp
There is no reason for this method to be public.
=> Make AbstractTask::_mark_as_scheduled private

src/lib/types.hpp
In one of the `pmr_concurrent_vector` constructors the size is not passed on. Instead an empty vector will be created. This PR fixes that.
=> Pass correct size to in pmr_concurrent_vector

src/lib/operators/join_hash.cpp, src/lib/types.hpp, src/test/operators/join_null_test.cpp
Also changed the temporary structure from `pmr_vector` to a regular vector. Since it is very temporary, there is no need for the NUMA overhead. First touch should be fine.
=> Fix HashJoin miscounting NULL rows, fixes #538

src/lib/operators/print.cpp, src/lib/operators/print.hpp, src/test/operators/print_test.cpp
We now truncate strings that are longer than a certain max width in `Print`.
Now:
```
=== Columns
|c_custkey|            c_name|           c_address|
|      int|            string|              string|
=== Chunk 0 ===
|        1|Customer#000000001|   IVhzIApeRb ot,c,E|
|        2|Customer#000000002|XSTf4,NCwDVaWNe6t...|
|        3|Customer#000000003|        MG9kdTD2WBHm|
|        4|Customer#000000004|         XxVSJsLAGtn|
|        5|Customer#000000005|KvpyuHCplrB84WgAi...|
|        6|Customer#000000006|sKZz0CsnMD7mp4Xd0...|
|        7|Customer#000000007|TcGe5gaZNgVePxU5k...|
|        8|Customer#000000008|I0B10bB0AymmC, 0P...|
|        9|Customer#000000009|xKiAFTjUsCuxfeleN...|
```
Before:
```
=== Columns
|c_custkey|            c_name|           c_address|
|      int|            string| …
```
=> Truncate long strings in Print

third_party/tpch-dbgen/bm_utils.c
The new `dbgen` wants to include `malloc.h`, but this header does not exist on macOS. Instead, the regular malloc from `stdlib.h` will be used.
=> Fix malloc include for macOS

src/test/sql/sqlite_testrunner/sqlite_wrapper.cpp
When loading a .tbl file into SQLite, the SQLiteWrapper treated a null value in a string_null column as string, not as null.
=> Fix SQLiteWrapper interpreting 'null' in string_null columns

src/lib/storage/chunk.hpp, src/lib/tasks/migration_preparation_task.cpp
This method is unused and might be confusing.
=> Remove Chunk::byte_size()

src/lib/operators/export_binary.cpp, src/test/testing_assert.cpp
#397 
This mainly changes the `check_table_equal() `method in `testing_assert.cpp`. It normalizes the error output after table comparison to:
- print both tables with colored highlights of mismatching cells if applicable
- print the type of error, and the actual and expected value
The highlights in the printed tables are two-fold. The first one is a "<<<<<" preceding the row(s) where the error occured, this makes it easy to locate the row with searching. The second one is a coloring of the affected cell and the row number as well, this makes it easy to spot when scrolling through the output.
This also gets rid of the problem @mrzzzrm mentioned, that a failing EXPECT_TABLE_EQ causes all following EXPECT_TABLE_EQ in the same test to print as well.
I'll attach some example images how it …
=> 397 Improve EXPECT_TABLE_EQ error output

src/lib/operators/difference.cpp, src/lib/operators/difference.hpp, src/lib/storage/base_column.hpp, src/lib/storage/dictionary_column.cpp, src/lib/storage/dictionary_column.hpp, src/lib/storage/reference_column.cpp, src/lib/storage/reference_column.hpp, src/lib/storage/value_column.cpp, src/lib/storage/value_column.hpp
addresses #599 
I left `Difference` basically untouched.
Note: Since `BaseColumn::write_string_representation` was a virtual method, it was just as fast as the subscript operator. I replaced this method with a call to `base_column[]` + a few more lines.
=> Remove BaseColumn::write_string_representation

src/lib/operators/index_scan.hpp, src/lib/operators/table_scan.cpp, src/lib/operators/table_scan.hpp, src/test/operators/table_scan_test.cpp
This adds the counterpart of IndexScan::set_included_chunk_ids. With this PR it is now possible to scan certain chunks using an index and all others with `TableScan`.
related #73
=> Add TableScan::set_excluded_chunk_ids

src/lib/logical_query_plan/lqp_translator.cpp, src/lib/logical_query_plan/lqp_translator.hpp, src/test/CMakeLists.txt, src/test/optimizer/lqp_translator_test.cpp
```c++
+  /**
+   * Translate a node (i.e. call `_translate_by_node_type`) only if it hasn't been translated before, otherwise just
+   * retrieve it from cache
+   *
+   * Without this caching, translating this kind of LQP
+   *
+   *    _____union____
+   *   /              \
+   *  predicate_a     predicate_b
+   *  \                /
+   *   \__predicate_c_/
+   *          |
+   *     table_int_float2
+   *
+   * would result in multiple operators created from predicate_c and thus in performance drops
+   */
```
Before:
```json
{
"benchmarks": [
{
"cpu_time": 15483563407,
"items_per_second": 0.0645846128463745,
"iterations": 1,
"name": "TPC-H 7",
"real_time": 15483563407,
"time_unit": "ns"
}
],
"context": {
"benchmark_mode": "IndividualQueries",
"build_type": "release",
"chunk_size": …
```
=> Improve translation of diamond shapes in LQP

src/bin/console/console.cpp
Doesn't show "All previous statements have been committed" if there is only a single statement.
=> Fix console error message for single statement queries

src/bin/playground.cpp
I type this in EVERY TIME I do something in the playground, so might just have it on master. 
Include types.hpp so the namespace is actually defined and I have a `#include` line to duplicate and adapt to other includes I might need.
=> Playground using namespace opossum

src/lib/operators/abstract_operator.hpp
An include is missing in abstract_operator.hpp
=> Fix build on macOS

src/lib/CMakeLists.txt, src/lib/optimizer/optimizer.cpp, src/lib/optimizer/optimizer.hpp, src/lib/optimizer/strategy/rule_batch.cpp, src/lib/optimizer/strategy/rule_batch.hpp, src/test/CMakeLists.txt, src/test/optimizer/optimizer_test.cpp
A RuleBatch can either be iterative, i.e. it executes the Rules until they stop changing the LQP, or execute their rules just once.
Details (per-batch `max_num_iterations`, batch names...) might be tweaked once actual batches arrive, but this should provide the template for those who wish to work with rule batches
=> RuleBatches

src/benchmarklib/tpch/tpch_db_generator.hpp
Calling `TpchDbGenerator(0.1f)` without an explicit `chunk_size` fails because it passes on a default size of 0, which causes an assert to fail in the table constructor.
=> Change default TpchDbGenerator chunk size

src/lib/operators/join_hash.cpp
I needed an example on how we will use profilers in the master's project to improve performance. This gets rid of repeated indirection through smart pointers and improves TPC-H performacne by 19,6%.
=> Hash-Join: Make histogram creation faster

src/benchmarklib/tpch/tpch_queries.cpp, src/lib/sql/sql_pipeline.cpp, src/test/sql/sql_translator_test.cpp
Updates sql-parser to include newest fixes and adapts a test which relied on an old column order, which has changed with the latest parser bug fix.
Fixes #580.
=> Fix column order in multi-table FROM

src/lib/logical_query_plan/abstract_lqp_node.cpp, src/lib/logical_query_plan/predicate_node.cpp
After introducing the ~`NamedColumnReference`~ `LQPColumnReference`-refactoring into our branch pushing predicates into the right subtree of a join stopped working.
This was due to the fact that finding a column ID (during the statistics computation, for instance) is essentially computing an offset:
static_cast<ColumnID>(std::distance(output_column_references.begin(), iter));
See `abstract_lqp_node.cpp:309`. The output column references still contained the result columns of the join despite the nodes had been rewired. For the right hand side this means those indices may be out of the range for the underlying nodes of the predicate when operating on stale state.
The solution is to clear the output column references upon child change to have them recomputed on the correct children node. …
=> Fix set child

src/benchmark/tpch_benchmark.cpp, src/lib/CMakeLists.txt, src/lib/logical_query_plan/join_node.cpp, src/lib/logical_query_plan/lqp_translator.cpp, src/lib/logical_query_plan/lqp_translator.hpp, src/lib/logical_query_plan/predicate_node.cpp, src/lib/logical_query_plan/predicate_node.hpp, src/lib/operators/index_scan.cpp, src/lib/operators/index_scan.hpp, src/lib/operators/join_nested_loop.cpp, src/lib/operators/join_sort_merge.cpp, src/lib/operators/table_scan.hpp, src/lib/optimizer/column_statistics.cpp, src/lib/optimizer/column_statistics.hpp, src/lib/optimizer/optimizer.cpp, src/lib/optimizer/strategy/index_scan_rule.cpp, src/lib/optimizer/strategy/index_scan_rule.hpp, src/lib/sql/sql_translator.cpp, src/lib/storage/index/index_info.hpp, src/lib/storage/table.cpp, src/lib/storage/table.hpp, src/test/CMakeLists.txt, src/test/optimizer/column_statistics_test.cpp, src/test/optimizer/lqp_translator_test.cpp, src/test/optimizer/strategy/index_scan_rule_test.cpp, src/test/optimizer/table_statistics_join_test.cpp, src/test/optimizer/table_statistics_test.cpp
This adds an optimizer rule to enable the translation of PredicateNodes to IndexScans. We do need IndexScans for one of the seminar topics as well as for other experiments. It is a first basic attempt, we did not include fancy cost models or made use of all the flexibility the chunk layout provides. 
There is an enum with the infamous name `ScanType` added to PredicateNodes. Currently this only holds `TableScan` and `IndexScan`. Later, it might contain further types ,e.g., `JITScan` or `AVX512Scan`.
There are a few things to note:
- This only works with single-column GroupKey indexes
- In case multiple indexes are present on a column of a chunk, there is no mechanism for deciding which index to use
- PredicateNodes can only be translated to IndexScans if their direct child is a …
=> Add optimizer rule to create IndexScans

src/lib/logical_query_plan/mock_node.cpp, src/lib/optimizer/table_statistics.cpp, src/lib/optimizer/table_statistics.hpp, src/test/optimizer/table_statistics_test.cpp
The `TableStatistics` lazily generates `ColumnStatistics` currently *only* when querying them with a predicate. This adds the missing lazy initialization logic to the method `TableStatistics::column_statistics()`, **making it non-const**. I also renamed it to `TableStatistics::get_all_column_statistics()` to emphasize that it returns *all* column statistics and not a specific one.
This ignores other shortcomings and is to be seen as a quickfix to a bug.
=> Fix omitted lazy column statistics initialization

src/lib/storage/chunk.cpp, src/lib/storage/chunk.hpp, src/test/storage/chunk_test.cpp
This adds a method to remove an existing index from a chunk. This functionality is needed for the *self-driving database* project.
Possible discussion topics:
- Argument: I picked `std::shared_ptr<BaseIndex>` because that is also the parameter returned from `Chunk::get_index`.
- Naming: I chose *remove* index over *drop* index as this is an operation on a storage container.
- Testing: I did not find any tests for the index operations of `Chunk`.
=> Add method to remove an index from a chunk

src/lib/sql/sql_translator.cpp, src/lib/sql/sql_translator.hpp, src/test/sql/sql_translator_test.cpp
Implement Hyrise part for https://github.com/hyrise/sql-parser/pull/79:
> Extend parser to handle aliases with column renames as found in SQL '92, named "correlation name" and "derived column list", respectively.
Above PR is not yet merged in sql-parser, but we currently anticipate this will be the case without further major (read: API-breaking) changes.
This PR checks for column renames inside alias definitions and creates a new projection node containing expressions with the corresponding aliases.
Furthermore this PR accounts for minor API changes not connected to table aliases such as the recent removals / renames of different join types which were not integrated to Hyrise at the point in time when work on aliases with column renames began.
=> Alias with Column Renames

src/lib/sql/sql_translator.cpp, src/test/sql/sql_translator_test.cpp
fixes #631. Now throws a "Insert: Column type mismatch" error in `SQLTranslator` when trying to `INSERT` values into columns of a different type.
=> Add Asserts to SQLTranslator when INSERTing mismatch type values

src/lib/operators/abstract_operator.cpp, src/lib/operators/abstract_operator.hpp, src/lib/operators/abstract_read_write_operator.cpp, src/lib/operators/abstract_read_write_operator.hpp, src/lib/operators/delete.cpp, src/lib/operators/delete.hpp, src/lib/operators/insert.cpp, src/lib/operators/insert.hpp, src/lib/operators/update.cpp, src/lib/operators/update.hpp, src/lib/sql/sql_pipeline.cpp, src/lib/sql/sql_pipeline.hpp, src/lib/sql/sql_pipeline_statement.cpp, src/lib/sql/sql_pipeline_statement.hpp, src/lib/sql/sql_query_cache.hpp, src/test/sql/sql_pipeline_statement_test.cpp, src/test/sql/sql_pipeline_test.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp
This PR adds PQP caching to the `SQLPipeline`. A given SQL string is split into the single statements and then passed to the corresponding `SQLPipelineStatement`. If `get_query_plan()` is called, the pipeline checks whether a PQP exists for the given statement string. If so, the `SQLQueryPlan` is recreated. 
EDIT: on second thought, this will not deal with #304 directly. There seems to be quite a few places that need to be changed to use SQLPipeline, so it makes sense to do that in a separate PR.
=> Add query cache to pipeline

src/lib/logical_query_plan/abstract_lqp_node.cpp, src/lib/logical_query_plan/abstract_lqp_node.hpp
fixes #625
This is as untested as the rest of `deep_copy` is. We have an issue for that: #689
=> Allow deep copy of diamond LQPs

src/lib/logical_query_plan/join_node.cpp, src/test/logical_query_plan/join_node_test.cpp
Semi and anti join only return the columns of the left input table. 
The output_column_references() returned the columns of both tables, though.
This pull request fixes the output_column_references of semi and anti joins and tests the new implementation.
=> semi and anti join node output column references fix

src/lib/constant_mappings.cpp, src/lib/constant_mappings.hpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_decompressor.hpp, src/test/operators/physical_query_plan_test.cpp, src/test/storage/compressed_vector_test.cpp, src/test/storage/encoded_column_test.cpp
There was a bug causing an integer overflow in the SIMD-BP128 decompressor, which wasn’t tested and slipped through review. I added a test and fixed the bug (and refactored the tests a bit). The real change is in `simd_bp128_decompressor.hpp:89`
Thanks @apopiak for his help.
The changes are described further in the comments.
=> Fix SIMD-BP128 decompressor

src/benchmarklib/benchmark_utilities/random_generator.hpp, src/benchmarklib/tpcc/tpcc_random_generator.hpp, src/lib/utils/assert.hpp, src/test/gtest_main.cpp
This reduced runtime of TPCH-5 (with somewhat ordered Joins) from 1s to 0.25s in Debug mode.
I should probably dig deeper as to what the hell we're doing in these debug messages, but stopped at `AbstractOperator::get_output()` which was actually taking milliseconds on a `TableScan`
```c++
// returns the result of the operator
std::shared_ptr<const Table> AbstractOperator::get_output() const {
DebugAssert(
[&]() {
if (_output == nullptr) return true;
if (_output->chunk_count() <= ChunkID{1}) return true;
for (auto chunk_id = ChunkID{0}; chunk_id < _output->chunk_count(); ++chunk_id) {
if (_output->get_chunk(chunk_id)->size() < 1) return true;
}
return true;
}(),
"Empty chunk returned from operator " + description());
DebugAssert(!_output || _output->row_count() == 0 || …
```
=> Only evaluate Assert msg on failure

src/lib/utils/format_bytes.cpp
Current master did not build on MacOS (clang 5.0.1) due to missing include.
=> Add missing sstream include

src/lib/import_export/csv_parser.hpp, src/lib/import_export/csv_writer.cpp, src/lib/import_export/csv_writer.hpp, src/lib/operators/export_csv.cpp, src/lib/operators/export_csv.hpp, src/lib/operators/import_csv.hpp, src/lib/storage/materialize.hpp, src/test/operators/export_csv_test.cpp
Adds support for all encoded column types to `ExportCsv`. This is one step towards the removal of `DeprecatedDictionaryColumn`.
The previous implementation used the visitor pattern to access values in columns. I replaced it with a call to `operator[]` since that can never be slower and is probably faster in some situations. Consider the code below. First of all. In order to get to the `handle_column` methods, two virtual methods have to be called, `visit` on the column and `handle_column`. Even if the visitor can then directly access the data (such as for `ValueColumn`), It is still going to be slower than just one virtual method call. In case of the `ReferenceColumn`, things get worse. Here, it does really call the subscript operator so the number of virtual method calls per element …
=> Support encoding types in csv exporter

Jenkinsfile
Having the sanitizer is a good thing and has found a bug or two in the past. However, compiling the sanitizer builds takes way longer than the regular builds. I think it is sufficient to only run the sanitizer for the master.
=> CI: Only build sanitizer for master

src/lib/operators/pqp_expression.cpp, src/lib/operators/pqp_expression.hpp, src/lib/operators/projection.cpp, src/lib/operators/projection.hpp, src/test/operators/recreation_test.cpp, src/test/sql/sql_pipeline_statement_test.cpp
This PR fixes #777. The subselect operator is now also recreated.
=> Recreate query plan for subselects

src/lib/storage/vector_compression/simd_bp128/simd_bp128_iterator.cpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_iterator.hpp
Iterators load one meta-block (2048 integers) at once instead of just one block (128 integers). This improves performance.
=> Improve performance of SIMD-BP128 iterator

src/lib/planviz/abstract_visualizer.hpp, src/lib/planviz/lqp_visualizer.cpp, src/lib/planviz/lqp_visualizer.hpp
Subqueries are now visualised in the LQP. PQP will come when I'm further down the line with correlated subqueries. But that will be a separate PR then.
Viz now:
The Projection has a "right" child, which is the subquery.
=> Visualise subqueries

src/benchmark/operators/product_benchmark.cpp, src/benchmark/operators/projection_benchmark.cpp, src/benchmark/operators/sort_benchmark.cpp
Apparently we had overlooked these benchmarks when we converted from max_chunk_size=0 to Chunk::MAX_SIZE a while ago.
=> Fix benchmarks that still used max_chunk_size=0 instead of Chunk::MAX_SIZE

src/benchmark/tpch_benchmark.cpp, src/benchmarklib/tpch/tpch_queries.cpp, src/benchmarklib/tpch/tpch_queries.hpp, src/test/tpc/tpch_test.cpp
Closes #791.
We can now access the queries by the correct index to query mapping without silly off by one confusion. All unused queries had to be commented because the compiler is not happy otherwise.
=> Change TPCH query array to map

src/bin/CMakeLists.txt, src/bin/console/console.cpp, src/bin/console/console.hpp
I added the functionality to print the current working directory to make it easier to use relative paths, e.g. to load tables and/or scripts.
=> Add pwd functionality to hyrise console

src/lib/import_export/csv_converter.hpp, src/lib/import_export/csv_meta.hpp, src/test/operators/import_csv_test.cpp
=> CsvParser allow unquoted null strings if specified in parse config

src/lib/sql/sql_pipeline.cpp, src/lib/sql/sql_pipeline.hpp, src/lib/sql/sql_pipeline_statement.cpp, src/test/sql/sql_pipeline_statement_test.cpp, src/test/sql/sql_pipeline_test.cpp, src/test/sql/sql_translator_test.cpp
The catch-rethrow code in `SQLPipeline(Statement)` was achieving very little for me except obscuring the real location of a throw when catching the unhandled Exception in the debugger. 
One `catch` tried to rollback a transaction if it threw an exception during runtime. Imo this goes against our design goal of not doing error recovery since just crashing on any kind of error allows for a much simpler code base. Hyrise is a research DB etc.
I altered `SQLPipeline::_failed_pipeline_statement` to point to an aborted statement, if any. That's the only scenario in which we're doing legitimate error recovery, everything else should be DB shutdown as by our design goals.
PR meant to be basis of a discussion, in person, if you like. @mrks @Bensk1 @lawben
=> Exception handlers are killing your call stacks

src/benchmarklib/tpch/tpch_queries.cpp, src/benchmarklib/tpch/tpch_queries.hpp, src/lib/sql/sql_translator.cpp, src/lib/sql/sql_translator.hpp, src/test/sql/sql_translator_test.cpp, src/test/tpc/tpch_test.cpp
A join condition may contain multiple conditions which may or may not contribute to matchmaking. By example:
SELECT * FROM A JOIN B ON A.a = B.a AND A.comment NOT LIKE 'special request';
As a result, given the expression tree, perform the following steps:
1. Flatten expression tree in order to get a list of conditions.
2. Inspect expression list in order to determine if it is a real join condition involving two column IDs from different tables or if it is a simple predicate (= which has at least one literal) which can be demoted in the left or right subtree.
3. For all simple predicates, append predicate nodes in the correct subtree.
=> Local Predicate Support for Joins

src/lib/concurrency/transaction_manager.cpp, src/lib/concurrency/transaction_manager.hpp
The method is a relict from the old TPC-C where we built operators by hand
=> Remove run_transaction

.gitignore, Jenkinsfile, README.md, scripts/coverage.sh, src/CMakeLists.txt, src/lib/abstract_expression.hpp, src/lib/logical_query_plan/abstract_lqp_node.hpp, src/lib/operators/insert.cpp, src/lib/operators/join_nested_loop.cpp, src/lib/optimizer/strategy/abstract_rule.hpp, src/lib/optimizer/table_statistics.hpp, src/lib/server/server_session.cpp
* For OS X, this uses LLVM's preferred way of getting coverage information, not the gcov compatibility one.
* It simplifies the coverage process, so that `./scripts/coverage.sh` is the only thing one has to do, thus fixes #617.
* Two smaller code fixes that I stumbled upon (missing virtual destructor, unnecessary `optional::value()`)
=> Fix Coverage for OS X + minor things

.gitignore, CMakeLists.txt, Jenkinsfile, README.md, scripts/coverage.sh, src/CMakeLists.txt, src/lib/abstract_expression.hpp, src/lib/logical_query_plan/abstract_lqp_node.hpp, src/lib/logical_query_plan/lqp_translator.hpp, src/lib/operators/insert.cpp, src/lib/operators/jit_operator/operators/jit_read_tuples.hpp, src/lib/operators/jit_operator/operators/jit_write_tuples.hpp, src/lib/operators/join_nested_loop.cpp, src/lib/optimizer/strategy/abstract_rule.hpp, src/lib/optimizer/table_statistics.hpp, src/lib/server/server_session.cpp
With llvm6 all classes with virtual functions need virtual destructors.
Master was merged to get Markus recent commit (https://github.com/hyrise/hyrise/commit/5fb4d4e5cacb9e2285f53e229e94b5cd10f44898) addressing missing v destructors.
I added the v destructors for new JIT classes and removed specified version info for llvm.
=> [JIT, for Johannes only] Addition to PR #711 to support LLVM6

src/CMakeLists.txt, src/lib/operators/abstract_operator.cpp, src/lib/operators/abstract_read_write_operator.cpp, src/lib/operators/get_table.cpp, src/lib/operators/get_table.hpp, src/lib/operators/maintenance/create_view.cpp, src/lib/operators/maintenance/drop_view.cpp, src/lib/operators/union_positions.cpp, src/lib/utils/format_duration.cpp, src/lib/utils/format_duration.hpp, src/test/CMakeLists.txt, src/test/operators/get_table_test.cpp, src/test/operators/index_scan_test.cpp, src/test/operators/insert_test.cpp, src/test/operators/projection_test.cpp, src/test/operators/recreation_test.cpp, src/test/operators/table_scan_like_test.cpp, src/test/operators/table_scan_test.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_queries.sql, src/test/storage/encoded_column_test.cpp, src/test/storage/table_test.cpp, src/test/utils/format_bytes_test.cpp, src/test/utils/format_duration_test.cpp, src/test/utils/numa_memory_resource_test.cpp
I could not focus on something complex, so I worked through the untested parts of the code, wrote tests and fixed some bugs on the way. Changes:
* Operators must return at least one column. Those that don’t “do” anything (e.g. CreateView) return a dummy column “OK”.
* Exceptions within operators are caught, the R/W operators are set as failed and then the exception is rethrown. This is because otherwise the unclean TX context will hide the actual problem (as I have just had with the insert). @mrzzzrm - you might have an opinion on this?
* fixed a bug in how durations were printed
* added a bunch of smaller tests
* changed table scan tests so that they test all encoding schemes
=> Bunch of smaller issues and tests

src/lib/storage/reference_column/reference_column_iterable.hpp
This caches the expensive call to `Chunk::get_column()`.
Maybe this could interfere with #793 .
=> Cache ChunkID and column in ReferenceColumnIterable

src/lib/statistics/column_statistics.cpp, src/test/statistics/column_statistics_test.cpp
Joining columns with non-overlapping range now have row count 0
Added a test for two columns with non-overlapping range.
Closes #865
=> Fix issue #865 - neg row count for non-overlapping ranges

src/test/operators/jit_operator/operators/jit_compute_test.cpp
Random generated numbers can cause int overflow during addition in JIT tests.
Switched to new random generators in JIT test to specify random number range.
Closes #867 .
=> Fix JIT tests - bug #867

src/lib/operators/get_table.cpp, src/lib/storage/table.cpp, src/lib/storage/table.hpp
We found a bug in the way `GetTable` currently appends existing chunks to a table.
To fix this we decided to add a new method to `Table` which takes existing chunks and appends them to the table.
=> Add method to append existing chunks to table

src/bin/console/console.cpp, src/lib/server/query_response_builder.cpp, src/lib/sql/sql_pipeline.cpp, src/lib/sql/sql_pipeline.hpp, src/lib/sql/sql_pipeline_statement.cpp, src/lib/sql/sql_pipeline_statement.hpp, src/test/sql/sql_pipeline_statement_test.cpp, src/test/sql/sql_pipeline_test.cpp
As per @timzimmermann's request: this PR adds explicit times for translation, optimization and compilation. Before, they were all in the compilation time.
In the console and server, you now get:
```
(TRANSLATE: 209 µs, OPTIMIZE: 19 µs, COMPILE: 89 µs, EXECUTE: 347 µs (wall time))
```
closes #885
=> Add more detailed timing to SQLPipeline

src/bin/console/console.cpp, src/lib/CMakeLists.txt, src/lib/server/query_response_builder.cpp, src/lib/sql/sql_pipeline.cpp, src/lib/sql/sql_pipeline.hpp, src/lib/sql/sql_pipeline_statement.cpp, src/lib/sql/sql_pipeline_statement.hpp, src/test/sql/sql_pipeline_statement_test.cpp, src/test/sql/sql_pipeline_test.cpp, src/test/sql/sql_query_plan_cache_test.cpp
This PR adds to #886 by moving all execution info into a struct. The struct has a nice `to_string()` which gives us:
```
Execution info: [PARSE: 8 µs, TRANSLATE: 163 µs, OPTIMIZE: 22 µs, COMPILE: 113 µs, EXECUTE: 172 µs (wall time) | QUERY PLAN CACHE HITS: 1/2 statement(s)]
```
=> Pipeline metrics

.asan-ignore.txt, .lsan-ignore.txt, Jenkinsfile, src/lib/operators/jit_operator/specialization/jit_code_specializer.hpp, src/lib/operators/jit_operator/specialization/jit_runtime_pointer.hpp, src/lib/operators/jit_operator/specialization/llvm_extensions.cpp
Added second sanitizer ignore file as the address sanitizer and leak sanitizer require different files.
Renamed .asan-ignore.txt to .lsan-ignore.txt as this file is passed to the leak sanitizer (LSan).
Jenkines now also considers the asan ignore file when executing the address sanitizer (ASan).
Undefined behavior sanitizer (UBSan) false positives could be disabled from within the source code and therefore do not require a separate ignore file.
New PR as PR #895 did not solve bug #892 .
Sanitizer tests are only executed by Jenkins on master branch.
To show that the changes will execute successfully on master branch, a demo branch fabian/bug/892/finally_fix_issue_sanitizer_jit_demo was branched of this fix with a modified Jenkins to enable sanitizer tests on the branch. Sanitizer tests run …
=> Fix santizer false positives for jit pointers #892

src/lib/CMakeLists.txt, src/lib/operators/jit_operator/jit_types.cpp, src/lib/operators/jit_operator/specialization/jit_code_specializer.cpp, src/lib/operators/jit_operator/specialization/jit_runtime_pointer.cpp, src/lib/operators/jit_operator/specialization/jit_runtime_pointer.hpp, src/lib/operators/jit_operator/specialization/llvm/InlineFunction.cpp, src/lib/operators/jit_operator/specialization/llvm/InlineFunction.diff, src/lib/operators/jit_operator/specialization/llvm_extensions.cpp, src/test/operators/jit_operator_wrapper_test.cpp
Removed null ptr issue in LLVM6 during execution of specialised jit code by clearing a `runtime_value_map` after inlining of each function.
The map caches the retrieved runtime values during function inlining. This lead to a problem when a function was inlined multiple times with different objects. The programme execution path depends on the context objects as they determine which path is taken at a condition or switch statement. Inlining and specialising a function with the wrong information can, therefore, cause as in our case the dereferenciation of null pointers.
The specialisation test case takes on my MacBook 276ms. I hope that is still acceptable as it is the only time that a query is actually specialised in the test cases.
Closes #911 .
=> Resolve null ptr issue in specialised operator code with LLVM6 (#911)

src/benchmark/CMakeLists.txt, src/benchmark/benchmark_playground.cpp
We found this pretty useful for our needs. Instead of settings it up temporarily every time, maybe it makes sense to have a benchmark playground - similar to the regular playground. Like http://quick-bench.com/ but you can use hyrise components.
The added benchmark content is just for illustrational purposes, showcasing a scenario in which it is important to prevent the compiler from optimizing out benchmarked code.
=> Benchmark Playground

src/lib/operators/table_scan.cpp, src/lib/operators/table_scan/base_single_column_table_scan_impl.cpp, src/lib/operators/table_scan/base_single_column_table_scan_impl.hpp, src/lib/operators/table_scan/base_table_scan_impl.hpp, src/lib/operators/table_scan/column_comparison_table_scan_impl.cpp, src/lib/operators/table_scan/column_comparison_table_scan_impl.hpp, src/lib/operators/table_scan/single_column_table_scan_impl.cpp, src/lib/operators/table_scan/single_column_table_scan_impl.hpp
Currently, TableScanImpls return a PosList by value. However, the TableScan needs them as `shared_ptr<PosList>` in order to build the output. Now, we avoid copying that PosList after scanning each chunk.
Don't expect any wonders to happen. This just bugged me a lot.
```
Benchmark | prev. iter/s | new iter/s | change                                                                       
-----------+--------------+------------+--------------
TPC-H 1   | 0            | 0          | +0% 
TPC-H 3   | 0            | 0          | +2% 
TPC-H 5   | 0            | 0          | +1% 
TPC-H 6   | 3            | 3          | +2% 
TPC-H 7   | 0            | 0          | -0% 
TPC-H 9   | 0            | 0          | +2% 
TPC-H 10  | 0            | 0          | +2% 
TPC-H 13  | 0            | 0          | …
```
=> TableScan: Don't copy PosLists

src/lib/logical_query_plan/jit_aware_lqp_translator.cpp, src/test/logical_query_plan/jit_aware_lqp_translator_test.cpp, src/test/operators/jit_operator/specialization/get_runtime_pointer_for_value_test.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp, src/test/tpc/tpch_test.cpp
This pr removes the table names from jit aggregate column names.
The issue is solved slightly different to the traditional hyrise aggregate operator as the column names should be known at translation time. The traditional hyrise operator takes the column name from the result of the previous operator which is not available during translation.
Code is also formatted.
=> Remove table names from jit aggregate column names

CMakeLists.txt, src/benchmarklib/benchmark_utils.cpp, src/lib/utils/performance_warning.hpp
First of all, LTO does not work right now. This is fixed with this PR. However, various benchmarks on different machines have shown that LTO does not have a significant advantage right now. Let's make it optional for now.
Also, this changes the performance warnings to `cerr`, so that we can get the JSON file of a benchmark by doing `./hyriseBenchmarkTPCH > bla.json` and call the compare script.
=> Fix LTO, then make it optional

src/lib/operators/join_hash.cpp
Previously, everything was in `JoinHashImpl<LeftType, RightType>`. The heavy-lifting subroutines such as `_probe` only used `<LeftType, HashedType>` or `<RightType, HashedType>`. Having them as class members means that they get instantiated per `<LeftType, RightType>` combination.
I moved them to their own functions outside of the templated class. I didn't really touch any code, so I wouldn't expect a thorough review.
```
clang -O0 alt: 0m42.911s 
clang -O0 neu: 0m9.610s
~78 % faster
clang -O3 alt: 1m41.671s
clang -O3 neu: 0m40.918s
~60 % faster
```
Also, this is a cool example for #915:
As you can see, the previous version (on top) and the new version spend roughly the same time instantiating `JoinHashImpl<int, int>`, but once all `RightType` versions are instantiated (first six lines in …
=> Make HashJoin build fast again

Jenkinsfile, scripts/current_branch_has_pull_request_label.py
Already, we do not execute all CI steps for PRs. This is to keep the CI build times and the load on the CI server low. Unfortunately, this means that we sometimes only see problems once we have merged the PR.
This introduces the GitHub Label `FullCI`. For PRs that do not have this tag, only selected CI steps are executed. Once you set `FullCI`, the same test suite as executed for the master is run. The idea is to only set that label once all changes have been done and all review comments have been addressed. This should be in your own interest, because now the build only takes around two minutes (if ccache has a good day).
Not setting `FullCI` does not keep you from getting a green tick, but only with `FullCI`, the PR is ready to be merged. Unfortunately, Jenkins is not (yet?) notified …
=> Selective CI

DEPENDENCIES.md, Dockerfile, Jenkinsfile, scripts/coverage.sh
#905 
Enables clang coverage on Linux (to test JIT files). Coverage diff will still be executed with gcc (and only on linux), since llvm does not have a usable export file type (https://llvm.org/docs/CommandGuide/llvm-cov.html#llvm-cov-report)
=> coverage with clang

src/lib/operators/join_hash.cpp
Currently, there are many jobs created during the Hash Join without any work load. In my setup (benchmark with scale factor 0.01, 100 runs) almost 55 % of the jobs scheduled during the build phase had nothing to do. The graphic below shows the distribution of partition sizes within this phase. A partition size ("value") of 0 means, the job has no workload.
=> Avoid jobs without work load in join hash

src/lib/concurrency/commit_context.cpp, src/test/server/server_test_runner.cpp
This finally fixes a race condition we had while committing. Now, our server should work as intended with many parallel connections :)
The test added should catch this. I'm aware, that this kind of testing is not super great but it is really hard to catch this bug in any other way. So if it fails in CI again, we know the problem is not fully dealt with.
For completeness, to reproduce in playground.cpp 
```cpp
#include <iostream>
#include <thread>
#include <chrono>
#include <future>
#include <memory>
#include "sql/sql_pipeline_builder.hpp"
#include "storage/storage_manager.hpp"
#include "types.hpp"
#include "utils/load_table.hpp"
#include "scheduler/current_scheduler.hpp"
#include "scheduler/node_queue_scheduler.hpp"
#include "scheduler/topology.hpp"
using namespace opossum;  // NOLINT
int …
```
=> Fix stupid race condition

scripts/lint.sh, src/lib/operators/join_mpsm/column_materializer_numa.hpp, src/test/logical_query_plan/union_node_test.cpp, src/test/operators/jit_operator_wrapper_test.cpp, src/test/server/server_session_test.cpp
For some reason, people included cpp files. Lint will no longer tolerate that. :rage:
Also, the hacky naming check in lint can go because clang-tidy is way better for that.
=> Fix included cpps

src/lib/operators/aggregate.cpp, src/lib/operators/join_hash.cpp, src/lib/utils/cuckoo_hashtable.hpp, src/test/utils/cuckoo_hashtable_test.cpp
> Nasty shared pointersss are bad. We need to kiiiilll them.
> *But th-they have always been good to us. We never lost an object.*
> Nooo, they just want our performanccce.
> *But what if someone else needs the elements from the hash table?*
> Nobody ever accesses them, preciousss. There is nothing shared about them.
> *And what do we do about the reallocations in the aggregate operator?*
> They are uselesssss as well.
Seriously though. This is not a good idea for a hash table that stores all entries internally:
```
void put(const T value, const RowID row_id) {
/// [...]
auto element =
std::make_shared<HashElement>(HashElement{value, std::make_shared<PosList>(pmr_vector<RowID>{row_id})});
place(element, 0, 0);
}
```
For the execution part of `hyriseBenchmarkTPCH`, this reduces the number …
=> Remove some shared_ptrs where they are not needed

src/test/sql/sqlite_testrunner/sqlite_wrapper.cpp
Fixes #984 
@mrzzzrm, the problem occured because:
The SQLiteWrapper divides the sql string into different queries by the semicolon, so
```
SELECT * FROM t;\n
```
would result in 2 queries, `SELECT * FROM t;`, and `\n`. The result table is determined by the last query executed, which in this case is `\n`. Therefore it just returned an empty table.
Update: Letting the `SQLPipeline` handle the splitting for us now.
=> Fix SQLiteWrapper returning empty table if last char is a newline

src/test/storage/numa_placement_test.cpp
I don't know why, but since the upgrade to Ubuntu 18.04, these fail every time for me now, even on master.
Before I hiding this in #882, I thought I'd create a separate PR for it.
=> Disable NUMAPlacementTest

Jenkinsfile
#981
Since shell statements within the pipeline are executed as root, the plugin hasn't had access to the subdirectories. Somehow this didn't through any errors...
=> Fix: Only index.html coverage file is generated

src/lib/operators/join_hash.cpp, src/lib/statistics/generate_column_statistics.cpp
* Some vector::reserve() in JoinHash 
```
Benchmark | prev. iter/s | new iter/s | change
-----------+--------------+------------+---------------
TPC-H 1   | 0.109        | 0.136      | +25%
TPC-H 3   | 1.501        | 1.652      | +10%
TPC-H 5   | 0.046        | 0.046      | +1%
TPC-H 6   | 5.12         | 5.104      | -0%
TPC-H 7   | 0.207        | 0.209      | +1%
TPC-H 9   | 0.035        | 0.036      | +2%
TPC-H 10  | 1.045        | 1.065      | +2%
TPC-H 13  | 0.593        | 0.877      | +48%
average   |              |            | +11%
```
=> vector::reserve() in JoinHash

src/lib/type_cast.hpp
...so you can run at least some tests in a debugger with break-on-exception enabled and do not constantly get interrupted every time `load_table()` is called.
Whenever you meet someone who thinks doing flow control with exceptions is fine, please CC me.
=> type_cast without throw

src/lib/operators/join_sort_merge.cpp
Avoid creating empty jobs in the sort merge join when partitions are empty. Only improves inner equi joins. #964
=> Avoid empty sort merge join jobs

scripts/lint.sh, src/lib/CMakeLists.txt, src/test/CMakeLists.txt, src/test/operators/table_scan_string_test.cpp, src/test/tables/int_string_like_equals.tbl, src/test/tables/int_string_like_less_than.tbl, src/test/tables/int_string_like_not_equals.tbl
* Make lint.sh complain about cpp/hpp files that cmake does not know about 
* Add missing cmake entries 
* Add string scan test (reusing the existing LIKE scan and adding equals/ne/lt) fixes #909
=> Some lint/cmake/test fixes

src/lib/expression/expression_utils.cpp, src/lib/expression/expression_utils.hpp, src/lib/optimizer/strategy/predicate_pushdown_rule.cpp, src/test/optimizer/strategy/predicate_pushdown_rule_test.cpp
Waiting for TPC-H 17 in the CI builds took waaaaay to long. We now push predicates through projections if they can be evaluated earlier. This keeps us from executing subselects that we don't actually need. refs #1012 
```
+-----------+---------+
| Benchmark | change  |
+-----------+---------+
| TPC-H 1   | +0%     |
| TPC-H 2   | +57286% |
| TPC-H 3   | +3%     |
| TPC-H 4   | +2482%  |
| TPC-H 5   | -9%     |
| TPC-H 6   | -8%     |
| TPC-H 7   | +2%     |
| TPC-H 8   | -28%    |
| TPC-H 9   | +1%     |
| TPC-H 10  | +6%     |
| TPC-H 11  | +5%     |
| TPC-H 12  | +0%     |
| TPC-H 13  | -1%     |
| TPC-H 14  | -2%     |
| TPC-H 15  | -2%     |
| TPC-H 16  | -5%     |
| TPC-H 17  | +97398% |
| TPC-H 18  | -1%     |
| TPC-H 19  | +0%     |
| TPC-H 20  | -1%     |
| TPC-H 21  | +4%     |
| …
```
=>  Push predicates through projections 

src/lib/planviz/abstract_visualizer.hpp, src/lib/planviz/lqp_visualizer.cpp
* Print the graph a bit denser
* Use \n instead of newline (makes it easier for other output formats)
* Use rectangles for LQPs, too, because parallelograms take too much space
* Use the LQP pointer address instead of contiguous ids for vertices, so that we can identify them across optimizer runs
=> Minor visualization tweaks

src/lib/optimizer/optimizer.cpp, src/lib/optimizer/strategy/predicate_pushdown_rule.cpp, src/test/optimizer/strategy/predicate_pushdown_rule_test.cpp
Missed one opportunity. Originally, wanted to optimize Query 21, but a gifted horse you don't look in the mouth.
```
+-----------+------------------+------+------------------+------+---------+---------------------------------+
| Benchmark | prev. iter/s     | runs | new iter/s       | runs | change  | p-value (significant if <0.001) |
+-----------+------------------+------+------------------+------+---------+---------------------------------+
| TPC-H 1   | 0.886854946613   | 54   | 0.824773132801   | 50   | -7%     |                          0.0000 |
| TPC-H 2   | 16.3936786652    | 984  | 28.3739929199    | 1000 | +73%    |     (run time too short) 0.0000 |
| TPC-H 3   | 12.8011140823    | 769  | 12.8205223083    | 770  | +0%     |                          0.5864 |
| TPC-H 4   | …
```
=> More aggressive predicate pushdown

src/lib/expression/aggregate_expression.cpp, src/lib/expression/aggregate_expression.hpp, src/test/expression/expression_evaluator_test.cpp, src/test/expression/expression_test.cpp, src/test/expression/lqp_select_expression_test.cpp
`Aggregates will return NULL when executed on an empty group - thus AggregateExpressions are always nullable`
Fixes this ...comment: https://github.com/hyrise/hyrise/issues/946#issuecomment-405103835
=> Fix AggregateExpression::is_nullable()

src/benchmarklib/tpch/tpch_queries.cpp, src/lib/statistics/column_statistics.cpp
Closes #1012
Query 6 breaks because of SQLite's float logic:
```
sqlite> SELECT 0.07 BETWEEN 0.05 AND 0.06 + 0.01;
0
sqlite> SELECT 0.07 BETWEEN 0.05 AND 0.07;
1
```
This is now doc'ed and a small offset was added to make sqlite include records with a discount of `0.7`
=> Bring TPC-H 6 closer to standardised version

scripts/run_benchmarks_over_commit_range.sh, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/benchmark_runner.hpp
This script runs a benchmark for all commits in a commit range, showing the development over time. Example output:
=> Multi-Benchmark script

src/lib/storage/fixed_string_dictionary_column/fixed_string_vector_iterator.hpp
Fixes #1043. `_chars == other._chars` compares each element in the vector.
The encoding took ~13 seconds with scale factor 0.1 and this encoding config:
```
{
"default": {
"encoding": "Dictionary"
},
"type": {
"string": {
"encoding": "FixedStringDictionary"
}
}
}
```
=> FixedStringDictionary: compare addresses

cmake/EmbedLLVM.cmake, cmake/FindFS.cmake, src/lib/storage/index/group_key/variable_length_key_base.cpp, src/lib/storage/proxy_chunk.cpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_compressor.cpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_iterator.cpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.cpp, src/test/operators/jit_operator/operators/jit_expression_test.cpp, src/test/storage/variable_length_key_base_test.cpp
Someone took the time to generalize some of the intel-specific code and add generic code for systems without SSE2. This makes it possible to run Hyrise on IBM Z machines. I'll tell you more about this on Wednesday.
Since the amount of changes is quite small, does not affect the architecture, and the introduced ifdefs only cover a couple of lines, I think we can bring it in.
This does not mean that we add "official" support for IBM Z. Not only do the binary tests (import/export) still fail, but since we do not have a CI machine, we cannot guarantee that things work.
=> Reduce level of IBM Z non-support

src/lib/storage/fixed_string_dictionary_column.cpp, src/lib/storage/fixed_string_dictionary_column/fixed_string_vector.cpp, src/lib/storage/fixed_string_dictionary_column/fixed_string_vector.hpp
There were too many string copies. fixes #1048
```
+-----------+------------------+------+------------------+------+--------+-----------------------------------------------+
| Benchmark | prev. iter/s     | runs | new iter/s       | runs | change |               p-value (significant if <0.001) |
+-----------+------------------+------+------------------+------+--------+-----------------------------------------------+
| TPC-H 1   | 2.22005701065    | 67   | 2.59907960892    | 78   | +17%   |                   (run time too short) 0.0000 |
| TPC-H 2   | 12.7983808517    | 384  | 13.1744680405    | 396  | +3%    |                   (run time too short) 0.1043 |
| TPC-H 3   | 13.7960586548    | 414  | 15.1589708328    | 455  | +10%   |                   (run time too short) 0.0000 |
| TPC-H 4 …
```
=> Improved FixedStringDict

src/benchmark/operators/join_benchmark.cpp, src/lib/operators/join_hash.cpp
New PR for the automated setting of radix bit counts for the hash join. fixes #1045
The reviews comments from PR #1049 should all be addressed.
TPC benchmark: `hyriseBenchmarkTPCH --scale 0.1 --time=720`
```
+-----------+---------------------+------+---------------------+------+---------+---------------------------------+
| Benchmark | prev. iter/s        | runs | new iter/s          | runs | change  | p-value (significant if <0.001) |
+-----------+---------------------+------+---------------------+------+---------+---------------------------------+
| TPC-H 1   | 2.72465515136719    | 1000 | 2.74556469917297    | 1000 | +1%     |                          0.0000 |
| TPC-H 2   | 21.2441997528076    | 1000 | 43.3155403137207    | 1000 | +104%   |     (run time too short) 0.0000 |
| TPC-H 3 …
```
=> Hash Join: variable radix bit counts

src/benchmark/tpch_benchmark.cpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/benchmark_utils.cpp
Adapt default benchmark settings (see #1059):
* use a default chunk size of 100,000 to ensure that executed benchmarks have tables with more than one chunk
* change the default time allowed per query (now 60s)
* change the default scale factor of TPC-H to 0.1 (still fast enough for testing but already yielding usable results)
* and since we are now so super fast: change the max iterations of a query to 10,000
=> Adapt default benchmark settings

src/test/base_test.hpp, src/test/gtest_main.cpp
The variable `test_data_path` is used for storing test data in specified directories to separate test instances from each other. It was a static variable until now which means that every test case had its own instance. Therefore, it was unset in test cases which relied on it being set.
=> Fix test_data_path variable declaration

src/test/CMakeLists.txt
I know this is a tiny change, but I believe it's unnecessary to link this here and it was starting to annoy me while watching make do its work.
=> Remove unnecessary linking of benchmarkingLib from hyriseTest

src/lib/operators/aggregate.cpp, src/lib/operators/join_sort_merge/column_materializer.hpp, src/lib/storage/dictionary_column/dictionary_column_iterable.hpp, src/lib/storage/index/group_key/group_key_index.cpp, src/lib/storage/vector_compression/fixed_size_byte_aligned/fixed_size_byte_aligned_vector.hpp
see commit descriptions for details.
```
+-----------+-----------------+------+------------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s    | runs | new iter/s       | runs | change | p-value (significant if <0.001) |
+-----------+-----------------+------+------------------+------+--------+---------------------------------+
| TPC-H 1   | 1.37261760235   | 83   | 1.41345322132    | 85   | +3%    |                          0.0000 |
| TPC-H 2   | 16.5763473511   | 995  | 20.17436409      | 1211 | +22%   |                          0.0000 |
| TPC-H 3   | 12.8522357941   | 772  | 12.9413614273    | 777  | +1%    |                          0.0017 |
| TPC-H 4   | 0.253401845694  | 16   | 0.252252727747   | 16   | -0%    |                          0.0001 |
| …
```
=> Performance improvements in Aggregate and FixedSizeByteAlignedVector

Jenkinsfile, src/benchmarklib/benchmark_runner.cpp
* Jenkins: run memcheck in parallel 
* Benchmark Runner: Print items/s in verbose mode so that I don't have to wait for all 22 queries
=> Alleviate Markus' impatience (memcheck in parallel, items/s in verbose mode)

src/lib/scheduler/abstract_task.cpp
=> Try explicit load for AbstractTask::_id in DTRACE macro

src/bin/console/console.cpp, src/bin/console/console.hpp, src/lib/logical_query_plan/show_tables_node.cpp, src/lib/logical_query_plan/show_tables_node.hpp
`generate` became `gentpcc`; `gentpch` was newly introduced. Removed some confusingly obvious out()put like "After TPC-C tables are generated, SQL queries can be executed".  
Fixes #1137
=> Console: gentpch command

src/lib/operators/join_hash.cpp, src/lib/type_cast.hpp
Currently, the join hash implicitly wraps the type into an AllTypeVariant. That is a bad thing. ;)
TPC-H 17, 20 and 22 are better because the performance regression from #1095 is gone. No idea why exactly those three queries have somewhat nondeterministic performance characteristics. Maybe that's because I keep forgetting to pin the execution to a single node?
```
Benchmark | prev. iter/s | new iter/s | change
-----------+--------------+------------+---------------
TPC-H 1   | 3.548        | 3.531      | -0%
TPC-H 2   | 85.881       | 99.25      | +16%
TPC-H 3   | 37.21        | 39.871     | +7%
TPC-H 4   | 0.512        | 0.521      | +2%
TPC-H 5   | 24.307       | 25.398     | +4%
TPC-H 6   | 59.488       | 60.878     | +2%
TPC-H 7   | 7.281        | 7.666      | +5%
TPC-H 8   | 32.221 …
```
=> Remove automatic AllTypeVariant conversion in type_cast

CMakeLists.txt, src/lib/CMakeLists.txt
There seems to be a problem with linking the boost container library after the update to macOS 10.14 and new cmake versions. If this passes FullCI, somebody should check it locally on a Mac with macOS 10.13 to avoid further fun.
=> macOS 10.14 and cmake 3.12.2 boost linkage problem

src/lib/utils/numa_memory_resource.cpp, src/lib/utils/numa_memory_resource.hpp
llvm7 was complaining about something in the code of cxxopts. 
In addition, I exchanged one of the deprecated boost headers.
=> Update cxxopts to newest version

src/lib/expression/evaluation/expression_evaluator.cpp, src/lib/expression/evaluation/expression_functors.hpp, src/lib/logical_query_plan/enable_make_for_lqp_node.hpp, src/lib/operators/aggregate.cpp, src/lib/operators/aggregate/aggregate_traits.hpp, src/lib/operators/jit_operator/jit_operations.hpp, src/lib/operators/jit_operator/operators/jit_aggregate.cpp, src/lib/operators/join_hash.cpp, src/lib/operators/join_mpsm/radix_cluster_sort_numa.hpp, src/lib/operators/join_sort_merge/radix_cluster_sort.hpp, src/lib/operators/table_scan/column_comparison_table_scan_impl.cpp, src/lib/resolve_type.hpp, src/lib/server/then_operator.hpp, src/lib/statistics/chunk_statistics/segment_statistics.cpp, src/lib/storage/dictionary_segment/dictionary_segment_iterable.hpp, src/lib/storage/index/group_key/variable_length_key_base.cpp, src/lib/storage/index/group_key/variable_length_key_store.hpp, src/lib/strong_typedef.hpp, src/lib/type_comparison.hpp, src/lib/utils/copyable_atomic.hpp, src/lib/utils/enum_constant.hpp, src/lib/utils/murmur_hash.hpp, src/test/base_test.hpp, src/test/operators/join_equi_test.cpp, src/test/statistics/chunk_statistics/range_filter_test.cpp
I was annoyed by our inconsistent use of various template helpers such as `std::enable_if` and `std::enable_if_t`.
So I set out to unify it, which worked in all but [one case](https://github.com/hyrise/hyrise/blob/master/src/lib/expression/evaluation/expression_evaluator.cpp#L825):
```c++
if constexpr (Functor::template supports<Result, LeftDataType, RightDataType>::value) {
...
}
```
I tried changing it to 
```c++
if constexpr (Functor::template supports_v<Result, LeftDataType, RightDataType>) {
...
}
```
after adding 
```c++
template <typename Result, typename ArgA, typename ArgB>
inline static constexpr bool supports_v = supports<Result, ArgA, ArgB>::value;
```
to all the structs defined in [expression_functors.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/expression/evaluat …
=> Standardize template stuff

src/benchmarklib/tpch/tpch_queries.cpp
As of now in TPC-H Q1, we select all dates before-equals the max shipdate generated by the tpch datagen: `      WHERE l_shipdate <= '1998-12-01'`
This means we have a filter that does not filter out any rows: 
The TPC-H specification uses this selection: `l_shipdate <= date '1998-12-01' - interval '[DELTA]' day (3)`
where DELTA is `is randomly selected within [60. 120].` (source: TPC-H spec 2.4.1.3)
The PR changes the selection value as if we would choose an interval of 90 days. This is similar to what HyPer did for their last VLDB paper.
The performance impact is neglectable since the filter returns now 5912 instead of 6004 rows on a scale factor of 0.001 (should scale linearly with larger scale factors). According to the specification, the 90 days interval should return 96% of the …
=> TPC-H Q1 date selection: filter on shipdate

src/plugins/CMakeLists.txt
=> Fix CMake warnings for empty add_library() call (#1147)

scripts/clang_tidy_wrapper.sh
@mrks Just a quick proposal to hard-code the clang-tidy version to use. Ubuntu 18.04, at least, doesn't install a `clang-tidy` executable/link at all, just `clang-tidy-*.0`
=> clang_tidy_wrapper: reference executable that actually exists.

src/lib/storage/vector_compression/simd_bp128/simd_bp128_compressor.cpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_compressor.hpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_iterator.hpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_packing.cpp
The SIMD-BP128 implementation was full of `#ifdef __SSE2__ #else`  switches to support non-SSE platforms.  These switches are unnecessary as the manually written SIMD code is not faster as code that is automatically vectorised by the compiler. I have checked that for TPC-H and might also take a look at a micro benchmark for this.
This PR removes the switches and platform-dependent code.
=> Removes SSE2-specific code from SIMD-BP128 implementation

src/lib/expression/expression_functional.hpp, src/lib/optimizer/strategy/chunk_pruning_rule.cpp, src/lib/statistics/chunk_statistics/histograms/abstract_histogram.cpp, src/test/expression/expression_evaluator_test.cpp, src/test/expression/expression_test.cpp, src/test/logical_query_plan/lqp_find_subplan_mismatch_test.cpp, src/test/operators/operator_scan_predicate_test.cpp, src/test/optimizer/lqp_translator_test.cpp, src/test/optimizer/strategy/chunk_pruning_test.cpp, src/test/sql/sql_translator_test.cpp
Merging #1154 on top of #1118 has revealed a missing implementation. Unfortunately, there were no merge conflicts, so the CI pass of #1154 was based on an outdated master. This PR fixes the result.
On a more general note: If we wanted to, we could prevent these situations by setting a Github setting that only allows us to merge if the PR is based on an up-to-date master. Obviously, this would mean that we would have to do more CI builds. As this is only the second time this has happened and gets caught as soon as the merged master is built, I don't think that doing so is necessary.
=> Fix Chunk Pruning for BETWEEN

.gitmodules, src/CMakeLists.txt, src/lib/operators/aggregate.cpp, src/lib/operators/join_hash.cpp
This PR changes the hash map usage in the `join_hash` operator from `std::unordered_map` to `ska::bytell_hash_map`.
The bytell map is interface compliant, but not yet with C++17. Consequently, we cannot use `emplace_back`.
```+-----------+--------------------+------+--------------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s       | runs | new iter/s         | runs | change | p-value (significant if <0.001) |
+-----------+--------------------+------+--------------------+------+--------+---------------------------------+
| TPC-H 1   | 2.87656950950623   | 173  | 2.83660435676575   | 171  | -1%    |                          0.0000 |
| TPC-H 2   | 101.251907348633   | 6076 | 88.3616485595703   | 5302 | -13%   |     (run time too short) 0.0000 |
| TPC-H …
```
=> Use alternative hash map in hash join.

src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/benchmark_utils.hpp
For years, we have preached that chunks are the superior main memory database storage layout concept. Until now, our benchmarks are executed with a single chunk of `MAX_CHUNK_SIZE`.  Recent experiments have shown that a chunk size of roughly 100,000 records achieves the best performance.
TPC-H performance for chunk size 100,000 compared to a single chunk of size `MAX_CHUNK_SIZE`:
Detailed analysis for different chunk sizes.
[queries.pdf](https://github.com/hyrise/hyrise/files/2460463/queries.pdf)
The large benefit for query 21 is explainable with a much better applicability of chunk pruning for the first correlated subquery:
=> Change default chunk size to 100,000 for benchmarks

src/lib/import_export/csv_parser.cpp, src/lib/import_export/csv_parser.hpp, src/lib/utils/load_table.cpp, src/lib/utils/load_table.hpp, src/test/CMakeLists.txt, src/test/lib/import_export/csv_parser_test.cpp, src/test/lib/utils/load_table_test.cpp
This PR adds functionality to parse the meta information in a tbl file / json file to create empty tables without loading the whole tbl/csv file.
I was using this during evaluation for my thesis and thought it might be useful for some other people in the future.
=> Add functionality to create empty tables from meta info

src/lib/expression/expression_functional.cpp, src/lib/expression/expression_functional.hpp, src/lib/logical_query_plan/show_tables_node.cpp, src/test/expression/expression_evaluator_test.cpp, src/test/expression/expression_test.cpp, src/test/expression/lqp_select_expression_test.cpp, src/test/expression/pqp_select_expression_test.cpp, src/test/logical_query_plan/aggregate_node_test.cpp, src/test/logical_query_plan/join_node_test.cpp, src/test/logical_query_plan/logical_query_plan_test.cpp, src/test/logical_query_plan/mock_node_test.cpp, src/test/operators/projection_test.cpp, src/test/optimizer/lqp_translator_test.cpp, src/test/optimizer/optimizer_test.cpp, src/test/optimizer/strategy/exists_reformulation_rule_test.cpp, src/test/optimizer/strategy/predicate_pushdown_rule_test.cpp, src/test/sql/sql_identifier_resolver_test.cpp, src/test/sql/sql_translator_test.cpp
C++ doesn't like the two functions having the same name:
https://stackoverflow.com/questions/29883977/ambiguous-name-lookup-with-using-directive/29883978
I ran into a compiler error while during a completely unrelated change and had to fix this.
=> Fix ambiguous names in expression_functional.hpp

scripts/compare_benchmarks.py, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/benchmark_utils.cpp, src/benchmarklib/benchmark_utils.hpp
This triggered a Floating Point Exception when a benchmark ran for 0 iterations in the given time.
Was considering setting the value to `-1.f` instead of `0.f`. Strong feelings anyone?
=> Prevent division by zero in BenchmarkRunner::_create_report().

src/lib/sql/sql_pipeline.cpp, src/lib/sql/sql_pipeline.hpp, src/lib/sql/sql_pipeline_statement.cpp, src/lib/sql/sql_pipeline_statement.hpp, src/lib/utils/format_duration.cpp, src/test/base_test.hpp, src/test/sql/sql_pipeline_statement_test.cpp, src/test/sql/sql_pipeline_test.cpp, src/test/utils/format_duration_test.cpp
If the CPU is too fast, the time spent in preparing a query might be less than a microsecond. Changing that to nanoseconds should solve the problem for this processor generation and the next. ;)
Also moves resetting the SQL plan cache to BaseTest. While this was never a problem, we should make sure that nothing ever lingers around there.
blocked by #1190
=> Change execution time from us to ns, fix format_duration

scripts/compare_benchmarks.py
As shown in #1198, we currently print nan due to a small error.
This change should fix that issue.
=> Fix nan issue in compare_benchmarks.py

scripts/format.sh
I noticed that we have ipp files but do not include them in the format script.
I also added an option to only format files that are staged in git, to speed up formatting as well as avoiding to change files one hasn't touched because of differences in clang-format versions.
=> Format ipp files and add functionality to only format git-staged files

scripts/format.sh, src/lib/expression/lqp_select_expression.cpp, src/lib/operators/join_hash.cpp, src/lib/operators/table_scan.cpp, src/test/lib/import_export/csv_parser_test.cpp, src/test/lib/utils/load_table_test.cpp, src/test/operators/table_scan_between_test.cpp
If you have already installed llvm 7 on OS X, you get a message complaining about an incompatible clang-format version. I have compared clang-format 6 and 7 and don't seem to get any format differences.
For this PR, I also executed `./scripts/format.sh all`.
=> Allow clang-format 7

src/lib/statistics/chunk_statistics/counting_quotient_filter.cpp, src/lib/statistics/chunk_statistics/counting_quotient_filter.hpp, src/test/statistics/chunk_statistics/counting_quotient_filter_test.cpp
Mismatching types broke the build on OS X. Also disables a test due to #1220.
=> Fix CQF compilation on OS X

src/lib/storage/reference_segment/reference_segment_iterable.hpp, src/test/storage/iterables_test.cpp
The Reference Segment Iterator should store its accessor by value instead of reference.
The issue was introduced with the smart poslists pr #1210 and found by executing the Jit operator reading two columns of the same type in parallel.
Fixes #1244
=> Reference Segment Iterator stores its accessor by Value - Fix bug #1244

scripts/lint.sh
- singleton.hpp showing up erroneously (#1247)
- Some checks not setting exit code properly
=> Fix lint.sh

src/lib/operators/union_positions.cpp, src/lib/operators/union_positions.hpp
Fix #1099
"Cluster" was the best term I could think of. Reasoning: The columns are clustered by the attribute that they reference the same Table/Column.
=> UnionPositions: Rename "Column Segments" to "Column Clusters"

src/lib/logical_query_plan/abstract_lqp_node.hpp, src/lib/logical_query_plan/lqp_utils.hpp, src/test/logical_query_plan/lqp_utils_test.cpp
Don't require the argument for `visit_lqp` to be an `shared_ptr<AbstractExpression>` anymore. Also, remove the template that is not needed.
Not as easy for `visit_expression` because of the reference wrapper.
fixes #1107.
=> Allow visit_lqp(xNode)

README.md, src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_index.cpp, src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_index.hpp, src/lib/storage/index/b_tree/b_tree_index.cpp, src/lib/storage/index/b_tree/b_tree_index.hpp, src/lib/storage/index/b_tree/b_tree_index_impl.cpp, src/lib/storage/index/b_tree/b_tree_index_impl.hpp, src/lib/storage/index/base_index.cpp, src/lib/storage/index/base_index.hpp, src/lib/storage/index/group_key/composite_group_key_index.cpp, src/lib/storage/index/group_key/composite_group_key_index.hpp, src/lib/storage/index/group_key/group_key_index.cpp, src/lib/storage/index/group_key/group_key_index.hpp, src/test/storage/btree_index_test.cpp, src/test/storage/group_key_index_test.cpp
In order to re-integrate the results of the self-driving PR #715 together with the new plugin architecture, here's the first round of changes: Indexes can now report their memory consumption and can estimate memory consumption for a hypothetical index.
This straightforward implementation modifies the index structures themselves and is not part of a plugin.
Not all indexes are completely supported (no support means runtime errors):
- Group Key Index: Supported
- Composite Group Key Index: Supported
- B-Tree Index: Reporting supported, estimation not supported
- Adaptive Radix Tree Index: Neither reporting nor estimation supported
=> [Self-Driving] Index memory consumption

src/bin/CMakeLists.txt, src/lib/CMakeLists.txt, src/lib/utils/load_table.cpp, src/lib/utils/load_table.hpp, src/lib/utils/string_utils.cpp, src/lib/utils/string_utils.hpp, src/test/CMakeLists.txt, src/test/sql/sqlite_testrunner/sqlite_wrapper.cpp, src/test/utils/string_utils_test.cpp
`_split()` was a global function starting with an underscore, which is against our conventions. I renamed it to `split_string_by_delimiter` and moved it to `utils/string_utils.hpp`
Also it being a template was unintuitive, imo.
=> _split() -> split_string_by_delimiter()

src/lib/sql/sql_pipeline_statement.cpp, src/lib/sql/sql_query_cache.hpp, src/test/base_test.hpp, src/test/sql/sql_pipeline_statement_test.cpp
One more PR based on #715 .
This adds caching of optimized LQPs in `SQLPipelineStatement`.
As discussed in the original PR, the LQP cache's type is `SQLQueryCache<std::shared_ptr<AbstractLQPNode>>` which is rather ugly. Would it make more sense to rename `SQLQueryCache` to something like `SingletonCache` and then using typedefs / `using` to map `SQLQueryCache<SQLQueryPlan>` back to its original name?
=> [Self-Driving] LQP cache

src/test/optimizer/join_graph_builder_test.cpp
In a JoinGraph with distinct components AB and C, the JoinGraphBuilder will create a cross-join edge between either AC or BC, depending on the hash function used by the stdlib. 
Alternatively, the JoinGraphBuilder could use a std::set over a std::unordered_set to become deterministic, but that would sacrifice perf for test readability.
=> Fix JoinGraphBuilderTest

src/test/storage/btree_index_test.cpp
Fixes #1266. This is not a defect in our or the btree code. Therefore, we could also try to find other test cases on other data types that don't trigger this mismatch, but I think strings are realistic and we should stick to that.
=> Fix btree size tests (#1266)

src/lib/sql/sql_pipeline.hpp, src/lib/sql/sql_pipeline_statement.hpp
Fix #1261 
Get rid of some commenting in SQLPipeline(Statement). The important comments will not be read if they are hidden inside overwhelming comment blocks of self-evident noise.
=> Trim down docs on SQLPipeline(Statement)

src/benchmark/tpch_benchmark.cpp, src/lib/expression/evaluation/expression_evaluator.cpp
Some TPC-H queries show a significant drop in performance when scaling up the number of used cores, such as TPC-H 7 and 19. In the ExpressionEvaluator, we use `_chunk->size()` as maximum of some for-loops. `Chunk::size()` in turn calls `Chunk::get_segment()`, which has an `std::atomic_load()`. That causes a major bottleneck the more threads simultaneously try to do that. Just replacing `_chunk->size()` with the `_output_row_count` that we have anyway gives us a small performance boost:
(nemea: `./build-release/hyriseBenchmarkTPCH --scale 1 --scheduler --clients 10 --cores 224`)
```
+-----------+-------------------+-------+--------------------+-------+---------+-----------------------------------------------+
| Benchmark | prev. iter/s      | runs  | new iter/s         | runs  | change  | …
```
=> Use cached chunk size in ExpressionEvaluator to fix multithreaded bottleneck

src/lib/operators/table_scan.cpp, src/lib/operators/validate.cpp, src/test/operators/validate_test.cpp
The single chunk guarantee of a `PosList` allows the use of a more efficient reference iterator on it as it does not have to retrieve the correct chunk for every `chunk_offset`.
`Tablescan` and `Validate` operator now make make full use of this guarantee:
If the `PosList` of the input segment has a single chunk guarantee, `Tablescan` and `Validate` also give the same guarantee for the new `PosList` in the output segment now.
In addition, the `Validate` operator considers the single chunk guarantee flag during MVCC evaluation now. This ensures that `get_scoped_mvcc_data_lock()` is only called once per chunk instead of for every `chunk_offset`.
Improved runtime by 10% for TPC-H with MVCC and scale factor 0.1:
=> Make full use of single chunk guarantee of PosLists in TableScan and Validate

src/lib/operators/abstract_join_operator.cpp, src/lib/operators/abstract_join_operator.hpp, src/lib/operators/join_hash.cpp, src/lib/operators/join_hash.hpp, src/lib/operators/join_index.cpp, src/lib/operators/join_index.hpp, src/lib/operators/join_mpsm.cpp, src/lib/operators/join_mpsm.hpp, src/lib/operators/join_nested_loop.cpp, src/lib/operators/join_nested_loop.hpp, src/lib/operators/join_sort_merge.cpp, src/lib/operators/join_sort_merge.hpp, src/lib/storage/table_column_definition.hpp, src/test/operators/join_test.hpp
The hopefully non-controversial part of fixing #1051: The `TableColumnDefinitions` of the null-supplying input in outer joins should be nullable
=> Fix outer join column nullability

src/lib/storage/reference_segment.cpp
Theoretically, a ReferenceSegment can become bigger than the input segments of the operator. This can happen, for example, if a hash-based join puts all entries into the same bucket and generates a single segment. It is the duty of the operator to make sure that, once a ReferenceSegment is full, the next one is started. So far, most operators ignore this, simply because we have not experienced the issue and have not considered it to be a priority. This assert makes sure that we become aware of it becoming relevant. 
fixes #1236
=> Assert pos list size

src/bin/console/console.cpp
Currently, the PQP cannot be properly visualized. I believe this was introduced with a0ad23a508fd7658720d4be8710281e3f91ba795.
Another thing I realized is that the help says the default behaviour for `exec or noexec` would be `noexec` which is not true.
=> Fix visualize PQP

cmake/EmbedLLVM.cmake, src/lib/operators/jit_operator/specialization/llvm/jit_llvm_bundle.s, src/lib/utils/assert.hpp
Fix #1328
@FabianWiebe this is pretty much precisely your proposed fix - what about this doesn't work? This will copy `jit_llvm_bundle.s` to the build directly and configure it. It isn't deleted when running `ninja clean`.
=> Use configure_file to generate jit_llvm_bundle.s

.gitmodules, src/test/cache/cache_test.cpp, src/test/expression/expression_evaluator_to_values_test.cpp, src/test/operators/difference_test.cpp, src/test/operators/index_scan_test.cpp, src/test/operators/join_equi_test.cpp, src/test/operators/join_full_test.cpp, src/test/operators/join_hash_steps_test.cpp, src/test/operators/join_hash_types_test.cpp, src/test/operators/join_index_test.cpp, src/test/operators/join_null_test.cpp, src/test/operators/operator_deep_copy_test.cpp, src/test/operators/union_all_test.cpp, src/test/optimizer/lqp_translator_test.cpp, src/test/sql/sql_pipeline_statement_test.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_jit.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_unencoded.cpp, src/test/statistics/chunk_statistics/counting_quotient_filter_test.cpp, src/test/statistics/chunk_statistics/histograms/abstract_histogram_test.cpp, src/test/statistics/chunk_statistics/min_max_filter_test.cpp, src/test/statistics/chunk_statistics/range_filter_test.cpp, src/test/storage/chunk_test.cpp, src/test/storage/materialize_test.cpp, src/test/storage/multi_segment_index_test.cpp, src/test/storage/single_segment_index_test.cpp, src/test/storage/table_test.cpp, src/test/storage/variable_length_key_store_test.cpp, src/test/tpc/tpch_test.cpp
In #1339, @cmfcmf made us aware of `GTEST_SKIP`, which is a better solution for tests that should not run in the release mode. This updates googletest and changes those test files.
=> Update googletest, use GTEST_SKIP

src/lib/operators/delete.cpp, src/test/operators/delete_test.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_queries.sql
Zis is German database. We do not tolerate lazyness. Every operator muzt be productive.
However, `Delete` did not work if there was nothing to delete. That should not happen, either.
=> Fix deleting zero rows

src/lib/statistics/chunk_statistics/min_max_filter.hpp, src/lib/statistics/chunk_statistics/range_filter.hpp, src/test/statistics/chunk_statistics/min_max_filter_test.cpp, src/test/statistics/chunk_statistics/range_filter_test.cpp
Fixes #1324.
Thing done:
* Add tests for unsupported predicates. They have been skipped before and returned false, which is fine, but NULL_VALUE parameters have not been handled (which can occur when the predicate is isNull). In these cases, the method crashed as it could not convert the value.
* To fix the error, NULL parameters are now checked and return false directly.
* Add tests for between and improve between pruning, which only pruned a few cases before.
=> Improve testing, handle isNull, and improve between pruning.

DEPENDENCIES.md, Dockerfile, install.sh
Build-essential does depend on gcc-7 which is then unnecessary installed because our scripts install gcc-8 anyways.
I removed build-essential from the install script on a fresh Ubuntu 18.04 image. Either we do not need any of the packages or Ubuntu 18.04 comes with them anyway.
I believe we had to add build-essential for lib tool or something similar to be able to build a former external dependency.
=> Remove build-essential from install script, dependencies and docker

src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp, src/test/operators/table_scan_test.cpp
=> ColumnVsValueScan: Fix MatchesAll optimization on Dictionaries

src/benchmark/benchmark_playground.cpp, src/benchmark/operators/aggregate_benchmark.cpp, src/benchmark/operators/difference_benchmark.cpp, src/benchmark/operators/join_benchmark.cpp, src/benchmark/operators/projection_benchmark.cpp, src/benchmark/operators/sort_benchmark.cpp, src/benchmark/operators/sql_benchmark.cpp, src/benchmark/operators/table_scan_benchmark.cpp, src/benchmark/operators/union_all_benchmark.cpp, src/benchmark/operators/union_positions_benchmark.cpp, src/benchmark/statistics/generate_table_statistics_benchmark.cpp, src/benchmark/tpch_db_generator_benchmark.cpp
As recommended by Google, range for loops have a smaller overhead that the currently used while(keepRunning) loops (see https://github.com/google/benchmark#a-faster-keeprunning-loop).
This PR changes the loops accordingly.
=> Change keepRunning to range for loop

src/benchmarklib/abstract_table_generator.cpp, src/bin/console/console.cpp
fixes #1187 
I don't think we need a prompt for confirmation. If you write `generate_...` it is clear what you want to do.
=> Console: Override tables when using generate_*

src/lib/scheduler/worker.hpp
This doesn't change anything if we don't assume we know the scheduler implementation, but for the current implementation it is more likely that non-finished tasks are in the end of the vector when a worker has to `_wait_for_tasks()`.
=> Reverse check if tasks are completed in Worker::_wait_for_tasks().

src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp, src/test/operators/table_scan_test.cpp
Another day, another bug that the TableScan unit tests didn't catch.
=> Fix NotEquals scan on Dictionaries

.gitignore, .gitmodules, scripts/setup_imdb.py, src/benchmark/CMakeLists.txt, src/benchmark/file_based_benchmark.cpp, src/benchmark/join_order_benchmark.cpp, src/benchmarklib/abstract_query_generator.cpp, src/benchmarklib/abstract_query_generator.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/file_based_query_generator.cpp, src/benchmarklib/file_based_query_generator.hpp, src/benchmarklib/file_based_table_generator.cpp, src/benchmarklib/tpch/tpch_query_generator.cpp, src/benchmarklib/tpch/tpch_query_generator.hpp
Adds a new target `hyriseBenchmarkJoinOrder` which lazily downloads the IMDB from @Bensk1 dropbox and otherwise functions just as the `hyriseBenchmarkFileBased`.
The queries are acquired from the new `third_party/join-order-benchmark` submodule.
Following [some dude's](https://twitter.com/SebAaltonen/status/1080076144089665537) advice on twitter, I didn't seek to introduce an abstraction layer that both `hyriseBenchmarkJoinOrder` and `hyriseBenchmarkFileBased` can use but instead c/p'ed the code. Roast me.
=> Join Order Benchmark

Jenkinsfile
This should make memcheck run much faster. We will still see leaks, but not where they come from. If that happens, we can still manually run the full check.
=> memcheck: remove leak check detail

src/lib/operators/table_scan/abstract_table_scan_impl.hpp
Improves the alignment of the table scan's hot loop. Also, I hope that this improves the stability of the benchmark results. Binary size for the TPC-H grows from 35M to 45M.
```
+-----------+-----------------+------+-----------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s    | runs | new iter/s      | runs | change | p-value (significant if <0.001) |
+-----------+-----------------+------+-----------------+------+--------+---------------------------------+
| TPC-H 1   | 0.564372479916  | 34   | 0.581200122833  | 35   | +3%    |                          0.0002 |
| TPC-H 2   | 7.89877462387   | 474  | 8.54508304596   | 513  | +8%    |     (run time too short) 0.0000 |
| TPC-H 3   | 6.66416120529   | 400  | 6.74540519714   | 405  | +1%    |     (run time …
```
=> WIP: Improve table scan alignment

src/CMakeLists.txt
This works as long as Hyrise is not used as a submodule. However, for plugins exactly that is the case.
=> Fix cmake include path for TargetLinkLibrariesSystem

src/bin/console/console.cpp, src/lib/utils/plugin_manager.cpp, src/test/utils/plugin_manager_test.cpp
As found out by @Bouncner [here](https://github.com/Bensk1/example-plugin/issues/1), unloading a plugin does not fail or indicate if the plugin did not exist in the first place. This PR is going to fix it and does some minor renamings.
=> Fix plugin unload behaviour.

src/lib/CMakeLists.txt, src/lib/storage/create_iterable_from_segment.hpp, src/lib/storage/create_iterable_from_segment.ipp, src/lib/storage/segment_iterables/any_segment_iterable.cpp, third_party/CMakeLists.txt
This reduces the compile time for the debug build as typed iterators are created once by `any_segment_iterable.cpp`, not every time `create_iterable_from_segment.hpp` is used.
You won't see any effect just with this, but it is blocking some bigger compile time reductions that I am working on.
(Also, it removes the pesky cqf warnings)
=> Faster type erasure for iterators

src/test/operators/join_equi_test.cpp, src/test/operators/join_hash_test.cpp
I found this while working on the sort-merge join and it bothered me. Test is executed for every join method but everytime the test actually just tests the same hash join call.
Further, the test is now covering more supported and unsupported cases.
=> Move hash join applicability test

scripts/cpplint.py, src/benchmarklib/benchmark_runner.cpp, src/bin/console/console.cpp, src/lib/operators/print.cpp, src/lib/operators/print.hpp, src/test/operators/print_test.cpp
fixes #1363
```
(debug)> load ../resources/test_data/csv/float_int.csv t Dictionary
Loading ../resources/test_data/csv/float_int.csv into table "t"
Encoding "t" using Dictionary
```
```
(debug)> load ../resources/test_data/csv/float_int.csv
Loading ../resources/test_data/csv/float_int.csv into table "float_int"
Encoding "float_int" using Unencoded
```
```
(debug)> print t
=== Columns
|       b|       a||        MVCC        |
|   float|     int||_BEGIN|_END  |_TID  |
|not null|not null||      |      |      |
=== Chunk 0 ===
|<Dic:1B>|<Dic:1B>||
|   458.7|   12345||     0|      |      |
```
=> Add encodings to Console and Print

src/lib/operators/aggregate.cpp, src/lib/operators/aggregate.hpp
This mostly moves around code in the aggregate operator. It is not the oh-so-much needed cleanup/rewrite, but at least reduces the compile time:
Previously (my laptop, debug): 0m35.766s
Now: 0m22.158s
Details:
* Removes unused GroupByContext struct.
* Splits up AggregateContext so that we can use it without the caller being templated on AggregateKey.
* Stores AggregateResult in a vector instead of the AggregateResultMap. This reduces the number of instantiations of that map. Also, it allows for the output step to be independent of AggregateKey.
Performance, just to show that I didn't break anything (not TPC-H, because that is not using the operator heavily enough; measured on nemea):
```
(release)> generate_tpch 10
(release)> SELECT COUNT(*) FROM lineitem GROUP BY l_suppkey LIMIT 10
```
=> Reduce compile time of Aggregate

resources/test_data/tbl/joinoperators/int_outer_join_sorted_asc.tbl, src/lib/storage/reference_segment/reference_segment_iterable.hpp, src/lib/storage/segment_accessor.hpp, src/lib/types.hpp, src/lib/utils/plugin_manager.cpp, src/test/operators/sort_test.cpp, src/test/storage/iterables_test.cpp, src/test/storage/segment_accessor_test.cpp
This fixes #1421 and some other nasty NULL cases.
One problem was that the SegmentAccessors did not correctly check for null values and accessed chunks with `INVALID_CHUNK_ID`.
Also, ReferenceSegmentIterables created SegmentPositions with `chunk_offset = 0u` when they were NULL. This way it was impossible to correctly check for `is_null()` afterwards. 
Last but not least, some optimizations that were implemented for `references_single_chunk` assume now that no NULL values are involved.
=> Fix NULL behavior (#1421)

resources/test_data/tbl/joinoperators/int_smaller_outer_join_null.tbl, src/lib/operators/join_sort_merge/column_materializer.hpp, src/lib/types.hpp, src/test/operators/join_full_test.cpp
Previously, we had `NULL_VALUE_ID{std::numeric_limits<ValueID::base_type>::max()}`. Now NULL values are represented by a ValueID that equals the size of the dictionary. The ColumnMaterializer did still use the old way to represent NULL values.
Looking over the code, there should be the opportunity for some simple optimizations taking into account if the column is nullable or not. E.g., the branch in the hot loop that is comparing `value_id != null_value_id` could be avoided.
=> Fix sort merge join when joining columns containing NULL

src/bin/console/console.cpp, src/bin/console/console.hpp, src/bin/console/pagination.cpp, src/bin/console/pagination.hpp
Closes #1426.
Just ignoring CTRL+C during pagination is simple (first commit of this PR), we just don't handle the signal.
To make CTRL+C behave the same way as 'q' during pagination, I made it push the curses character code for CTRL+C onto the input stack (with ungetch()), and also add a generous timeout to the getch() loop, so that the simulated keypress actually gets captured without a second input.
A bit hacky, but since we catch the signal in the console, it is not passed on to the pagination window, therefore we have to manually push it back.
=> Fix Pagination CTRL+C behaviour

src/lib/operators/join_hash.cpp, src/lib/operators/join_sort_merge.cpp, src/lib/operators/join_sort_merge/column_materializer.hpp, src/lib/operators/join_sort_merge/radix_cluster_sort.hpp, src/test/operators/join_equi_test.cpp
This PR addresses #1208. Previously, the sampling (apart from being plain wrong) was using the frequency of values to determine splits in the data. Since the chance of sampling the same value multiple times is low (and even then, it does not need to be a good split value), the splitting resulted in highly skewed clusters.
Now, we gather a small `SampleRequest` in which each materialized segment puts some samples. Then, the sample requests are merged, sorted and we select the required number of split values.
I measured the performance with an active scheduler and the change is minimal. I expected it to be better since the values are now (almost) equally sized.
Now:
```
➜  OpossumDB git:(fix/sort_merge_join) ✗ ./rel/hyriseMicroBenchmarks  --benchmark_filter="BM_Sam" …
```
=> Fix sampling in sort-merge join

src/lib/logical_query_plan/delete_node.cpp, src/lib/logical_query_plan/delete_node.hpp, src/lib/logical_query_plan/lqp_translator.cpp, src/lib/logical_query_plan/lqp_utils.cpp, src/lib/logical_query_plan/mock_node.cpp, src/lib/logical_query_plan/mock_node.hpp, src/lib/operators/abstract_read_write_operator.cpp, src/lib/operators/abstract_read_write_operator.hpp, src/lib/operators/delete.cpp, src/lib/operators/delete.hpp, src/lib/operators/jit_operator/jit_types.hpp, src/lib/operators/jit_operator/operators/jit_read_tuples.cpp, src/lib/operators/update.cpp, src/lib/sql/sql_translator.cpp, src/lib/storage/chunk.cpp, src/lib/storage/chunk.hpp, src/lib/storage/table.hpp, src/test/logical_query_plan/delete_node_test.cpp, src/test/logical_query_plan/lqp_utils_test.cpp, src/test/operators/delete_test.cpp, src/test/sql/sql_translator_test.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_encodings.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_jit.cpp, src/test/statistics/chunk_statistics/histograms/histogram_utils_test.cpp
Fix #1083 
Closes #1269
The `Delete` operator can now work on "pruned" versions of stored Tables. Such Tables contain a subset of the Chunks of a stored Table and are generated if `GetTable` is instructed to exclude Chunks.
* Removes the "table_name" fields from `Delete` and `DeleteNode`
* Enables the `SQLiteTestrunner` for all encodings (and JIT + Dictionary for good measure)
* Fix a bug in the `SQLiteTestrunner` that made it not reset the SQLite version of a Table when running the same query for multiple encodings.
=> Fix Delete'ing from pruned Table

src/lib/operators/delete.cpp, src/test/operators/delete_test.cpp
When deleting rows that have not been validated, delete fails, but its error message is not helpful. #1424 tried to implement #1344 and track if the input table has been validated. But even the latter was already on the wrong track.
If we want to make sure that the rows given to delete are visible, why don't we... well... check that?
Stupid.
fixes #1344.
=> Delete only visible rows

src/lib/CMakeLists.txt, src/lib/optimizer/optimizer.cpp, src/lib/optimizer/strategy/insert_limit_in_exists.cpp, src/lib/optimizer/strategy/insert_limit_in_exists.hpp, src/test/CMakeLists.txt, src/test/optimizer/strategy/insert_limit_in_exists_test.cpp
This pr introduces a new optimization rule, which allows jittable operators to terminate early during processing of the subexpression of an exists expression.
The optimization rule adds a limit node to the the subquery of an exists expression if the subquery does not contain one.
=> Add optimization rule to add a Limit node to the subquery of an Exists expression

src/lib/CMakeLists.txt, src/lib/logical_query_plan/jit_aware_lqp_translator.cpp, src/lib/logical_query_plan/jit_aware_lqp_translator.hpp, src/lib/logical_query_plan/lqp_utils.cpp, src/lib/operators/jit_operator/jit_types.hpp, src/lib/operators/jit_operator/operators/jit_limit.cpp, src/lib/operators/jit_operator/operators/jit_limit.hpp, src/lib/operators/jit_operator/operators/jit_read_tuples.cpp, src/lib/operators/jit_operator/operators/jit_read_tuples.hpp, src/lib/operators/jit_operator_wrapper.cpp, src/test/CMakeLists.txt, src/test/logical_query_plan/jit_aware_lqp_translator_test.cpp, src/test/operators/jit_operator/operators/jit_limit_test.cpp, src/test/operators/jit_operator/operators/jit_read_write_tuple_test.cpp, src/test/operators/jit_operator_wrapper_test.cpp
This pr introduces a jittable Limit operator.
The `JitAwareLQPTranslator` adds the jittable Limit operator to the jittable operator pipeline if a Limit exists in the lqp.
The row count expression of the limit is evaluated before execution by the first operator in the pipeline, `JitReadTuples` operator.
=> Add jittable Limit Operator

CMakeLists.txt, src/benchmarklib/CMakeLists.txt, src/bin/CMakeLists.txt, src/bin/playground.cpp, src/lib/CMakeLists.txt, src/test/CMakeLists.txt
Fix #1447
* Remove "hyriseBenchmarkLib --> AlwaysCheckGit" dependency in favor of "hyrise --> AlwaysCheckGit" dependency
* Remove hyriseServer dependency to boost includes, because linking hyriseServer to hyrise already delivers this dependency
* Remove Boost_PROGRAM_OPTIONS_LIBRARY dependency of hyriseServer, because the server doesn't seem to use boost program options?
=> Only link libhyrise against CMAKE_DL_LIBS. Remove build dependencies

scripts/compare_benchmarks.py
For some reason, the reported runtime sometimes ends up just short of 60 seconds. This leads to the compare_benchmarks.py script to report results as "runtime too short".
Also changes the grey color for insignificant results to white. Grey doesn't seem to be supported by OS X.
=> compare_benchmarks.py: fix "runtime too short"

third_party/CMakeLists.txt
fixes #1448.
The problem was that the jemalloc build step did not fail our build if it fails to config/build jemalloc. This is because of the `||` case in the config and build command. We use that to print the output in case of failure, but it also prevents the failure to propagate to the next step:
```
BUILD_COMMAND bash -c "output=$(make 2>&1) || printf \"$output\\n\""
```
This PR makes it that, if either the config or build step of jemalloc fails, we manually fail (which is what's supposed to happen anyway).
=> Fail if config or build step of jemalloc fails.

src/test/storage/encoded_segment_test.cpp, src/test/storage/simd_bp128_test.cpp
Decreased some magic numbers and got the test runtime (debug) from >5s down to 4.5s on my machine. For none of these magic numbers was a justification given, so I suppose they are fair game :man_shrugging:
=> Reduce hyriseTest runtime

third_party/CMakeLists.txt
references #1448 ([comment](https://github.com/hyrise/hyrise/issues/1448#issuecomment-460221250))
On Ubuntu (e.g., the build vms for the DYOD seminar) the following does not work:
`BUILD_COMMAND bash -c "output=$(make 2>&1) || (printf \"$output\\n\" && /usr/bin/false)"`
The false binary is located in `/usr/bin/false` on macOS while it is located in `/bin/false` on linux (or at least ubuntu).
This PR just uses `false` instead.
=> Fix false call in jemalloc build

src/lib/scheduler/task_queue.cpp, src/lib/scheduler/task_queue.hpp, src/lib/scheduler/worker.cpp, src/lib/scheduler/worker.hpp
I'm currently benchmarking the pipeline creation for my thesis. I noticed a big spreading of execution times (min: 78 µs, median: 2300 µs, max: 18000 µs for query `select 1;`). The strongly fluctuating times are a result of the worker sleep time of 10 ms. As discussed in PR #1379 we actually don't want to have a sleep timer for the workers. Hence, I implemented a solution using `std::condition_variable`s. I changed the current implementation in such a way, that the node's task queue notifies a worker (on the same node) as soon as a new job gets pushed into the queue. Work stealing is performed by waking up each worker every 100µs (debatable).
However, benchmark performance on numa systems using many clients will **decrease** tremendously (see screenshot below). This is because of the bad …
=> Worker sleep times (Follow-up on #1379)

src/lib/storage/table.cpp, src/lib/storage/table.hpp, src/test/storage/table_test.cpp
fixes #1463 
Not optimal and we might want to revisit this, but at least it doesn't break anymore.
```
+-----------+-----------------+------+-----------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s    | runs | new iter/s      | runs | change | p-value (significant if <0.001) |
+-----------+-----------------+------+-----------------+------+--------+---------------------------------+
| TPC-H 1   | 0.6128718853    | 37   | 0.579127073288  | 35   | -6%    |                          0.0000 |
| TPC-H 2   | 8.59151172638   | 516  | 8.31142425537   | 499  | -3%    |                          0.0000 |
| TPC-H 3   | 6.95756530762   | 418  | 6.60669755936   | 397  | -5%    |                          0.0000 |
| TPC-H 4   | 2.13772106171   | 129  | 2.14647006989 …
```
=> Fix concurrent access to _chunks

src/benchmarklib/benchmark_runner.cpp
Fix #1472 
Bloody `selected_query_ids`
=> Fix SQLite verification on subset of benchmark queries

resources/tracer_scripts/query_analyzer.stp, src/lib/scheduler/task_queue.cpp, src/lib/scheduler/task_queue.hpp
This issue addresses two small things I found during my work on hyrise.
1) Since PR #1419 operator performance is measured in nanoseconds. The SystemTap script `query_analyzer.stp` uses this information but has not been updated from microseconds to nanoseconds. (Other scripts are not effected)
2) In `TaskQueue` class we currently count the amount of tasks present in the node's queues. We increment/decrement `std::atomic_uint _num_tasks` whenever a task is pushed to/pulled from the queue. However, this variable is only accessed in `TaskQueue::empty()`. Indeed, this method is only called once - in a DebugAssert (node_queue_scheduler.cpp:72).
=> Fix query_analyzer.stp and remove TaskQueue::_num_tasks

resources/test_data/sqlite_testrunner_queries.sql, src/lib/logical_query_plan/jit_aware_lqp_translator.cpp, src/lib/logical_query_plan/jit_aware_lqp_translator.hpp, src/lib/logical_query_plan/lqp_translator.cpp, src/lib/logical_query_plan/lqp_utils.cpp, src/lib/logical_query_plan/lqp_utils.hpp, src/lib/operators/jit_operator/jit_types.cpp, src/lib/operators/jit_operator/jit_types.hpp, src/lib/operators/jit_operator/operators/jit_read_tuples.cpp, src/lib/operators/jit_operator/operators/jit_read_tuples.hpp, src/lib/operators/jit_operator_wrapper.cpp, src/lib/operators/jit_operator_wrapper.hpp, src/test/logical_query_plan/jit_aware_lqp_translator_test.cpp, src/test/logical_query_plan/lqp_utils_test.cpp, src/test/operators/jit_operator/operators/jit_read_write_tuple_test.cpp, src/test/operators/jit_operator_wrapper_test.cpp
This PR enables the jittable operators to use parameters.
The `JitReadTuples` operator keeps track of all used parameters within the jittable operator pipeline. The actual parameter values are stored within the `JitOperatorWrapper` and are passed to the `JitReadTuples` operator via the `JitReadTuples::before_query` function call.
The support for parameters enables JIT to be used within correlated subqueries. To prevent a new specialization of code for every execution of a correlated subquery, all `JitOperatorWrapper` instances with the same operator pipeline share the specialized function in a `SpecializedFunctionWrapper`. In case that multiple correlated subqueries are executed in parallel, a mutex within the wrapper ensures that the code is specialized only once.
This pr also enhances …
=> JIT - Add parameter support for jittable operators

src/benchmarklib/benchmark_runner.cpp, src/lib/optimizer/optimizer.cpp, src/lib/optimizer/optimizer.hpp, src/test/optimizer/optimizer_test.cpp
> The optimizer stores the rules as shared_ptr. Is this necessary? Could these be unique_ptr?
No. Yes.
Fixes #1476.
=> Optimizer: store rules as unique_ptr

src/lib/logical_query_plan/delete_node.cpp, src/lib/logical_query_plan/delete_node.hpp, src/lib/logical_query_plan/insert_node.cpp, src/lib/logical_query_plan/insert_node.hpp, src/lib/logical_query_plan/update_node.cpp, src/lib/logical_query_plan/update_node.hpp, src/lib/optimizer/strategy/column_pruning_rule.cpp, src/test/logical_query_plan/delete_node_test.cpp, src/test/logical_query_plan/insert_node_test.cpp, src/test/logical_query_plan/update_node_test.cpp, src/test/optimizer/strategy/column_pruning_rule_test.cpp
Fix #1440
There was already a ColumnPruningRule test for Insert, but it did not fail because, by coincidence, another bug fixed things: The Delete/Insert/UpdateNodes were assumed to output all their input columns, causing the ColumnPruningRule to not prune in LQPs with Insert/Update/DeleteNodes. Actually, the Delete/Insert/Update **operators** return a nullptr, which is now reflected in the LQP as well.
=> Fix ColumnPruningRule for Insert and Delete

src/lib/operators/join_index.cpp
The index join preallocated the result pos list, assuming the worst case output size of a join (n*m tuples). For large tables with hundreds of thousands of rows, the join easily allocated TBs.
This PR changes the size to reserve. It expects that each tuple of the smaller relation will have exactly one match. For very small tables, 100 RowIDs are reserved to avoid frequent resizes while not wasting memory.
Fixes #1390.
=> Index join: change pos list size initially reserved

src/lib/logical_query_plan/lqp_utils.cpp, src/lib/logical_query_plan/lqp_utils.hpp, src/test/logical_query_plan/jit_aware_lqp_translator_test.cpp, src/test/logical_query_plan/lqp_utils_test.cpp
This PR corrects the LQP helper function, `lqp_subplan_to_boolean_expression()`.
The function can combine multiple Predicate and Union nodes in an LQP to one boolean expression and is used by the jit-aware LQP translator.
The old implementation reversed the order of the predicates which results in the last predicate of an LQP being evaluated first. This was caused by the fact that an LQP is evaluated from first to last node but `lqp_subplan_to_boolean_expression` traverses the LQP from last to first node.
The new implementation traverses the LQP in the same way but reverses the order in which predicates are added to the result expression.
=> LQP Utils: Correct order of expressions in the translation of an LQP to a boolean expression

src/lib/storage/create_iterable_from_segment.hpp, src/lib/storage/segment_iterables/any_segment_iterable.cpp
I was a bit uneasy that it might still happen that code gets instantiated for the LZ4Iterable and higher compile times might be creeping in. This PR makes sure the compiler will tell us if someone attempts to do this and only allows type-erased iteration of the LZ4Segment
=> Force erasure of LZ4Segment

src/test/optimizer/greedy_operator_ordering_test.cpp, src/test/optimizer/strategy/insert_limit_in_exists_rule_test.cpp, src/test/testing_assert.hpp
Tests like this:
```c++
// clang-format off
const auto input_lqp =
PredicateNode::make(greater_than_equals_(_column_a, 200),
PredicateNode::make(less_than_equals_(_column_b, 300),
_node));
const auto expected_lqp = input_lqp;
// clang-format on
const auto result_lqp = StrategyBaseTest::apply_rule(_rule, input_lqp);
EXPECT_LQP_EQ(result_lqp, expected_lqp);
```
should be encouraged to do `const auto expected_lqp = input_lqp->deep_copy()` to avoid false-positive tests.
=> Strict EXPECT_LQP_EQ to avoid mistakes in Optimizer tests

src/lib/concurrency/transaction_context.cpp, src/lib/concurrency/transaction_context.hpp, src/lib/concurrency/transaction_manager.cpp, src/lib/concurrency/transaction_manager.hpp, src/test/CMakeLists.txt, src/test/concurrency/transaction_manager_test.cpp
Our upcoming MvccDeletePlugin (DYOD18/19 project) requires some changes within hyrise.
- `TransactionManager` needs to keep track of running transactions resp. the snapshot-commit-ids being in use. 
This allows our MvccDeletePlugin to make sure that an already logically deleted chunk (fully invalidated) can be deleted physically (from memory) as well – without interfering with ongoing transactions.
- `TransactionContext` notifies `TransactionManager` that the transaction has finished. So the `TransactionManager` can "release" the snapshot-commit-id
=> [DYOD18/19] MvccDeletePlugin prep. (TransactionManager & -Context)

src/lib/storage/segment_iterables/base_segment_iterators.hpp
Code smell, imo, to have a special base class of a core class, dedicated to a particular component. Thankfully it wasn't used.
=> Remove JitBaseSegmentIterator

src/lib/operators/table_scan/column_vs_column_table_scan_impl.cpp, src/lib/storage/base_segment.hpp, src/lib/storage/segment_iterate.hpp, src/lib/types.hpp
Single-threaded release build with clang on pella: 57m39,206s (from 68m28,928s on the master)
Instead of always instanciating `#LeftDataType*#LeftSegmentType*#RightDataType+#RightSegmentType` versions of the inner lambda before deciding to type-erase, only instantiate `#LeftDataType*#RightDataType` (for the type-erased case) plus `#LeftDataType*#LeftSegmentType` (for the non-type erased case).
This PR makes it harder to switch back to never-erase in code, but those days are over for good imo.
=> Reduce ColumnVsColumnScan compile time

src/bin/console/console.cpp, src/bin/console/console.hpp
Fixes #1235 
The way the auto completion currently works is not ideal, as it requires to implement the logic and add new commands that take more than the first parameter by hand. For example, if another "setting" gets added, it would have to be added to the auto completion by hand. I don't see this as super problematic right now, but it could get annoying in the future.
=> Add auto completion for visualize and setting commands in Console

src/lib/operators/abstract_join_operator.hpp, src/lib/operators/join_index.hpp, src/lib/operators/join_mpsm.hpp, src/lib/operators/join_sort_merge.hpp
Note, again, how comments do not compile and do not fail tests even if they become confusing gibberish.
* Both JSM and JMPSM are run through the join_null_test, so I'd assume they support null values.
* JSM supports outer joins for non-equal
=> Remove obsolete docs for Join operators

src/benchmark/file_based_benchmark.cpp, src/benchmark/join_order_benchmark.cpp
Right now, only TPC-H supports `-q 1` for selecting a single query. This PR adds that to the other benchmarks.
=> FileBasedBenchmark, JOB: Support -q

resources/test_data/sqlite_testrunner_queries.sql, src/lib/operators/jit_operator/jit_operations.hpp, src/lib/operators/jit_operator/operators/jit_expression.cpp, src/test/operators/jit_operator/jit_operations_test.cpp, src/test/operators/jit_operator/operators/jit_expression_test.cpp
This pr adds a check for division and modulo operations if the right operand is zero.
The tests have been extended to cover these edge cases including two new queries for the sqlite test.
Fixes #1450
=> [JIT] Correct div/mod by zero (issue #1450)

scripts/cpplint.py, src/lib/expression/evaluation/like_matcher.cpp, src/lib/expression/evaluation/like_matcher.hpp
This pr replaces `boost::variant` with `std::variant` in `LikeMatcher` class.
It is a preparation for a future JIT pr improving the evaluation of like queries.
JIT cannot handle `boost::variant` code during specialization but it can handle `std::variant` code.
=> Replace boost::variant with std::variant in LikeMatcher

src/lib/storage/lz4_segment.cpp, src/test/storage/lz4_segment_test.cpp
This PR just adds two test cases (one for strings, one for non-strings) that test segments with enough values, so that a dictionary can be used. This is not the case in any of the tests in EncodedSegmentTest or EncodedStringSegmentTest. 
@Bouncner
=> [DYOD18/19] Add LZ4 test for (de)compressing with a dictionary

src/lib/logical_query_plan/jit_aware_lqp_translator.cpp, src/lib/operators/jit_operator/jit_operations.cpp, src/lib/operators/jit_operator/jit_operations.hpp, src/lib/operators/jit_operator/jit_types.cpp, src/lib/operators/jit_operator/jit_types.hpp, src/lib/operators/jit_operator/operators/jit_aggregate.cpp, src/lib/operators/jit_operator/operators/jit_compute.cpp, src/lib/operators/jit_operator/operators/jit_compute.hpp, src/lib/operators/jit_operator/operators/jit_expression.cpp, src/lib/operators/jit_operator/operators/jit_expression.hpp, src/lib/operators/jit_operator/operators/jit_filter.cpp, src/lib/operators/jit_operator/operators/jit_filter.hpp, src/lib/operators/jit_operator/operators/jit_read_tuples.cpp, src/lib/operators/jit_operator/operators/jit_read_tuples.hpp, src/lib/operators/jit_operator/operators/jit_validate.cpp, src/lib/operators/jit_operator/operators/jit_validate.hpp, src/lib/operators/jit_operator/operators/jit_write_tuples.cpp, src/lib/operators/jit_operator/operators/jit_write_tuples.hpp, src/lib/operators/jit_operator_wrapper.cpp, src/test/logical_query_plan/jit_aware_lqp_translator_test.cpp, src/test/operators/jit_operator/jit_hashmap_entry_test.cpp, src/test/operators/jit_operator/operators/jit_expression_test.cpp, src/test/operators/jit_operator/operators/jit_read_write_tuple_test.cpp, src/test/operators/jit_operator/specialization/get_runtime_pointer_for_value_test.cpp, src/test/operators/jit_operator/specialization/jit_repository_test.cpp, src/test/operators/jit_operator/specialization/resolve_condition_test.cpp, src/test/operators/jit_operator_wrapper_test.cpp
This pr removes unnecessary getter and setter functions from JIT operators.
If a class member has a getter, the class member is now `public const`.
If the member has a setter, it has no `const` attribute.
This pr also incorporates the new rule to use automatic pointer conversion to bool.
Updated JIT tests according to the following rules:
`ASSERT_EQ(x, nullptr); -> ASSERT_FALSE(x);`
`ASSERT_NE(x, nullptr); -> ASSERT_TRUE(x);`
`ASSERT_EQ(x, false); -> ASSERT_FALSE(x);`
`ASSERT_EQ(x, true); -> ASSERT_TRUE(x);`
=> [JIT] Remove unnecessary getters and setters from JIT operators

src/CMakeLists.txt, src/benchmarklib/benchmark_config.cpp, src/benchmarklib/benchmark_config.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/cli_config_parser.cpp, src/bin/console/console.cpp, src/bin/console/console.hpp
This pr introduces the option to enable JIT in console and benchmark.
JIT can be enabled in the benchmark with `--jit ` and in the console with `setting jit on`.
If Hyrise is build without JIT support (`-DENABLE_JIT_SUPPORT=OFF`), these options are not available.
This pr also corrects the functionality in the CMake file to en- or disable JIT.
Fixes #970
=> [JIT] Add option to use JIT in console and benchmark

src/lib/concurrency/transaction_manager.cpp, src/lib/expression/evaluation/expression_evaluator.cpp, src/lib/expression/expression_utils.cpp, src/lib/expression/is_null_expression.cpp, src/lib/operators/join_mpsm/radix_cluster_sort_numa.hpp, src/lib/statistics/chunk_statistics/histograms/equal_width_histogram.cpp, src/lib/utils/assert.hpp, src/test/tpc/tpch_test.cpp
Before, this may have caused formatting/linting confusion.
The do-while(false) thing is the standard pattern for requiring macros to be concluded with a semicolon just like a normal function call. Pls don't question this. ;)
=> Make Assert() and DebugAssert() require semicolon

src/CMakeLists.txt, src/lib/operators/jit_operator/operators/jit_read_tuples.cpp
This pr corrects the default value of `ENABLE_JIT_SUPPORT` which was changed in pr #1566 caused the value to be always set to `OFF`.
As a result, Jenkins did not build and test the JIT code anymore so that the changes concerning the evaluation of limit expressions in pr #1581  could pass by not running the not working JIT tests.
The limit expression evaluation in the JIT code has now been adjusted.
=> [JIT] Correct default value of ENABLE_JIT_SUPPORT and handling of LIMIT expressions

src/bin/playground.cpp, src/lib/concurrency/transaction_manager.hpp, src/lib/operators/delete.cpp, src/lib/operators/insert.cpp, src/lib/operators/insert.hpp, src/lib/storage/chunk.cpp, src/lib/storage/chunk_encoder.cpp, src/lib/storage/chunk_encoder.hpp, src/lib/storage/mvcc_data.cpp, src/lib/storage/mvcc_data.hpp, src/lib/tasks/chunk_compression_task.cpp, src/lib/types.hpp, src/test/storage/table_test.cpp
...and general cleanup. The Insert code is now much more pleasant to read.
Also, fix #1086 
Here is the playground that I used to "test" whether multi-threaded insert works:
```c++
#include <atomic>
#include <iostream>
#include <thread>
#include "operators/print.hpp"
#include "sql/sql_pipeline_builder.hpp"
#include "storage/storage_manager.hpp"
#include "storage/table.hpp"
#include "types.hpp"
using namespace opossum;               // NOLINT
using namespace std::string_literals;  // NOLINT
int main() {
const auto table =
std::make_shared<Table>(TableColumnDefinitions{{"a", DataType::Int}}, TableType::Data, 5, UseMvcc::Yes);
//table->add_unique_constraint({ColumnID{0}}, false);
StorageManager::get().add_table("T0", table);
std::atomic<int32_t> global_variable{0};
std::vector<std::thread> …
```
=> Fix Multi-threading support for Insert

src/lib/optimizer/strategy/between_composition_rule.cpp, src/test/optimizer/strategy/between_composition_rule_test.cpp
The master currently fails with libc++, where the iteration order of `unordered_map` is different.
=> Between: Make order of inserted predicates deterministic

src/lib/operators/join_hash.cpp, src/lib/operators/join_hash/join_hash_steps.hpp, src/test/operators/join_hash_steps_test.cpp, src/test/operators/join_hash_types_test.cpp
In the case of semi or anti joins, we do not need to track all rows on the hashed side, just one per value. However, if we have secondary predicates, those might fail on that single row. In that case, we DO need all rows.
```
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s   | runs | new iter/s     | runs | change | p-value (significant if <0.001) |
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| TPC-H 1   | 0.524710536003 | 32   | 0.529083013535 | 32   | +1%    |                          0.3526 |
| TPC-H 2   | 8.37547397614  | 503  | 8.58118247986  | 515  | +2%    |                          0.0000 |
| TPC-H 3   | 6.53036642075  | 392  | …
```
=> JoinHash for semi/anti: Insert values just once

src/bin/console/pagination.cpp, src/lib/operators/join_hash/join_hash_steps.hpp, src/lib/operators/table_scan/abstract_table_scan_impl.hpp, src/lib/operators/table_scan/column_vs_column_table_scan_impl.cpp, src/lib/operators/table_scan/column_vs_column_table_scan_impl.hpp, src/lib/storage/create_iterable_from_segment.hpp, src/lib/storage/create_iterable_from_segment.ipp, src/lib/storage/dictionary_segment/attribute_vector_iterable.hpp, src/lib/storage/reference_segment/reference_segment_iterable.hpp, src/lib/storage/segment_iterables/any_segment_iterable.cpp, src/test/operators/aggregate_test.cpp, src/test/storage/iterables_test.cpp, src/test/storage/segment_iterators_test.cpp
In ColumnVsColumnScans, we previously generated code for comparing `ReferenceSegmentIterable::SingleChunkIterator<SegmentAccessor<int, FrameOfReferenceSegment<int>>>` with `ReferenceSegmentIterable::SingleChunkIterator<SegmentAccessor<int, LZ4Segment<int>>>`. No more.
The PerformanceWarning is never printed, and except for Q15 acting weird again, the TPC-H results remain the same, too.
```
8df96d5075443fde6dc98d41fce711e8cf02b969 (master)
real    10m22,591s
user    86m39,677s
sys     12m16,553s
d8a3a44920f4e61d9109aff50150cce97d050c01 (Type-erase the accessor in type-erased reference segments, erase more aggressively in ColumnVsColumnScan)
real    5m35,670s
user    82m8,795s
sys     12m35,370s
```
=> Compile time: More type erasure in ColumnVsColumnScan

src/lib/operators/insert.cpp, src/lib/operators/validate.cpp, src/lib/operators/validate.hpp, src/lib/storage/chunk.cpp, src/lib/storage/mvcc_data.cpp, src/lib/storage/mvcc_data.hpp, src/lib/storage/table.cpp
#1585 changed the way MVCC vectors were extended. Resizing and writing a couple hundred atomics is quite expensive if we synchronize for each.
Also, the same PR changed new MVCC rows that they were not immediately visible. For the TPC-H with MVCC enabled, this meant that all tables were basically empty. This won't happen anymore with #1597, where we get rid of the option of running without MVCC altogether.
```
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s   | runs | new iter/s     | runs | change | p-value (significant if <0.001) |
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| TPC-H 1   | 0.533324956894 | 33   | 0.527172207832 | 32   | -1%    | …
```
=> Fix MVCC performance regression, fix MVCC data for rows that are not inserted.

Jenkinsfile, src/lib/CMakeLists.txt, src/test/CMakeLists.txt
fixes #1583, makes it possible to call `./hyriseTest` without changing the directory.
Tested with ninja and OS X as well as make+ninja and Ubuntu.
=> Cmake: add link to resources

src/test/storage/btree_index_test.cpp
The pmr_string change was not represented. Fixes #1266
=> Fix btree_index_test for libc++

src/lib/CMakeLists.txt
fixes #1619, but you will have to delete the symlink inside the resources folder yourself.
=> Create resources link only once

src/lib/operators/table_scan/abstract_table_scan_impl.hpp
fixes #1505 
As seen there, `aligned` now seems to hurt the performance, while it was good a while ago. Since it causes issues on OSX, it should go.
I also checked if `noinline` had a reason to stay, but GCC likes it:
```
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| Benchmark | prev. iter/s   | runs | new iter/s     | runs | change | p-value (significant if <0.001) |
+-----------+----------------+------+----------------+------+--------+---------------------------------+
| TPC-H 1   | 0.514372348785 | 31   | 0.505956292152 | 31   | -2%    |                          0.0337 |
| TPC-H 2   | 6.7894821167   | 408  | 7.1751203537   | 431  | +6%    |                          0.0000 |
| TPC-H 3   | 6.35070705414  | 382  | 5.90168619156 …
```
=> Remove scan alignment

src/test/lossless_cast_test.cpp, src/test/operators/table_scan_test.cpp, src/test/optimizer/strategy/chunk_pruning_test.cpp
On OS X, `long` and `int64_t` are not the same type.
I'll ask for a Mac Mini to be used as a CI server tomorrow. -.-
=> Fix lossless tests on OS X

src/lib/optimizer/strategy/expression_reduction_rule.hpp
Sorry to create another PR for this, but previously the NOT LIKE rewrite was doc'ed under the headline "LIKE to BetweenUpperExclusive" , which just didn't fit.
=> Update ExpressionReductionRule docs for NOT LIKE rewrite

src/bin/console/console.cpp
fixes #1635
> Static destruction order... -.-
> The console is static so that the signal handler can find it. The console gets initialized first. The SQL pipeline needs a transaction context, so it calls `TransactionManager::get().new_transaction_context()`, which initializes the static transaction manager. On destruction, the transaction manager was created last and gets destructed first. Next, the console, and with it, the last SQL pipeline is destructed. The pipeline has a context which cannot be deregistered in the now defunct transaction manager.
=> Fix console crashing on exit

resources/test_data/csv/no_columns.csv.json, src/benchmarklib/table_generator.cpp, src/benchmarklib/tpcc/tpcc_table_generator.cpp, src/benchmarklib/tpch/tpch_table_generator.cpp, src/bin/playground.cpp, src/lib/expression/expression_utils.cpp, src/lib/import_export/csv_parser.cpp, src/lib/operators/abstract_operator.cpp, src/lib/operators/alias_operator.cpp, src/lib/operators/import_binary.cpp, src/lib/operators/index_scan.cpp, src/lib/operators/projection.cpp, src/lib/operators/table_scan.cpp, src/lib/operators/union_positions.cpp, src/lib/storage/chunk.cpp, src/lib/storage/chunk.hpp, src/lib/storage/table.cpp, src/lib/storage/table.hpp, src/test/operators/import_csv_test.cpp
Fix #1645 
Also, avoid redundant calls to `input_table_left()` for each `Chunk` to save a shared_ptr copy.
Also, remove `Chunk::set_mvcc_data()` because it isn't needed anymore since `Table::append_chunk()` now takes the new Chunk's MvccData as well. One entry point less for potential concurrency problems.
TPC-H with sf=5 
```
+----------------+-----------------+------+-----------------+------+------------+---------------------------------+
| Benchmark      | prev. iter/s    | runs | new iter/s      | runs | change [%] | p-value (significant if <0.001) |
+----------------+-----------------+------+-----------------+------+------------+---------------------------------+
| TPC-H 1        | 0.0490739420056 | 10   | 0.0489541068673 | 10   | -0%        |                          0.4264 |
| …
```
=> Projection performance: Don't allocate MvccData to then immediately overwrite it

resources/test_data/sqlite_testrunner_queries.sql, src/lib/logical_query_plan/lqp_translator.cpp, src/test/logical_query_plan/lqp_translator_test.cpp
Fix #1529 
Fall back from JoinHash to JoinSortMerge to JoinNestedLoop to find a matching Join operator for JoinNode.
=> Use JoinOperator::supports() to find a matching Join implementation for a JoinNode

src/lib/storage/encoding_type.hpp, src/lib/storage/frame_of_reference_segment.cpp, src/test/operators/join_test_runner.cpp
This PR disables the support of `int64_t` for FrameOfReverence segments.
During table generation for the calibration framework, I stumbled over the issue that Moritz found during the work on the join test runner as well. FrameOfReference segments do not support `uint64_t` values since the underlying vector compression only handles `uint32t` values (see discussion in #1662).
I would vote for extending the vector compression to default to `uint64_t` values, but that has several disadvantages (one of them compile time). And since SIMDBP adaptions do not appear to be too easy, I don't think it will be fixed within the next couple of weeks.
This change simply limits the usage of FrameOfReference segments. No benchmark I know of uses anything larger int and most users won't use FoR at all. So I …
=> Adapt supported encodings of FoR

src/lib/sql/sql_translator.cpp, src/test/sql/sql_translator_test.cpp
After #1656, this adds input assertions so that we can also survive DML (INSERT/UPDATE/DELETE) on non-existing tables.
=> Console: Survive missing tables in DML

README.md
Much important fixes for the readme:
* Fix the order of contributors
* Add a missing dot
This PR is absolutely not for any other reason.
=> Readme: fixes

src/lib/operators/join_hash.cpp, src/lib/operators/join_hash.hpp, src/test/operators/join_hash_test.cpp
This PR prints the number of radix bits (used in the hash join operator) in the PQP visualization. Before, it has only been printed, when it was set with the creation of the hash join operator.
When somebody is not happy with public mutable members, I am happy to take suggestions.
=> Show hash join's radix bits in PQP

src/lib/operators/join_index.cpp, src/lib/operators/join_index.hpp, src/lib/types.hpp, src/test/operators/join_index_test.cpp
This PR integrates the possibility to use the JoinIndex with the mandatory index structures in the output table of the left input operator. Previously the index structures had to be on the right side.
Now, the JoinIndex constructor expects the specification of the join input operator which output table contains the index structures (`const JoinInputSide index_side`). By default, the index_side is `JoinInputSide::Right`.
=> JoinIndex support index on both sides

src/CMakeLists.txt, src/lib/operators/index_scan.cpp, src/lib/operators/table_scan.cpp, src/lib/server/client_connection.cpp, src/lib/server/server_session.cpp, src/lib/server/task_runner.hpp
With C++20 the implicit capture of `this` when the capture default is `=` [becomes deprecated](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0806r2.html). This PR adapts relevant Lambdas to be compatible with C++20.
* To capture `*this` by reference, explicit captures of `this` are added.
* `[=, this]` is an [extension of C++20](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0409r2.html) and not backward compatible with C++17. Therefore, some captures became more explicit.
=> Change Lambda captures to be compatible with C++20

src/benchmark/operators/table_scan_sorted_benchmark.cpp, src/lib/operators/aggregate_sort.cpp, src/lib/operators/join_hash/join_hash_steps.hpp, src/lib/operators/sort.cpp, src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp, src/lib/storage/table.cpp, src/lib/storage/table.hpp, src/test/operators/index_scan_test.cpp, src/test/operators/table_scan_between_test.cpp, src/test/operators/table_scan_test.cpp, src/test/optimizer/strategy/chunk_pruning_test.cpp, src/test/storage/chunk_encoder_test.cpp, src/test/storage/table_test.cpp
This PR has its root in #1686, which implements `std::atomic_load` and `std::atomic_store` for the vector `_chunks` in `Table`. Latter PR is in favor of the MvccDeletePlugin, which removes chunks from the `_chunks` vector.
Each read-/write-access on `_chunks` has to happen via atomics functions. People might forget about this and break thread-safety unwittingly.
Because of this, we remove the `chunks()` function from `Table`.  This limits all critical access to the `_chunks` vector to a single class (`Table`).
=> Remove function Table::chunks()

src/lib/cost_estimation/cost_estimator_logical.cpp, src/lib/operators/aggregate_hash.hpp, src/lib/operators/join_hash.cpp, src/lib/operators/join_hash/join_hash_steps.hpp, src/lib/optimizer/optimizer.cpp, src/lib/storage/reference_segment.cpp, src/lib/storage/reference_segment.hpp, src/lib/storage/segment_accessor.cpp, src/lib/storage/segment_accessor.hpp
* Improved the SingleChunkReferenceSegmentAccessor, throwing away some indirections
* Return the pos_list of a ReferenceSegment by... reference
* Change the execution order of the optimizer rules to something more beneficial
* AggregateHash: Use bytell_hash_map for the hash table
* JoinHash: Shrink the hash tables before probing
* JoinHash: Clean up materialized data earlier
```
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| Benchmark      | prev. iter/s   | runs | new iter/s     | runs | change [%] | p-value (significant if <0.001) |
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| TPC-H 1        | 0.420189529657 | 26   | 0.613110005856 | 37   | +46% …
```
=> More performance optimizations

src/lib/scheduler/topology.cpp, src/lib/scheduler/topology.hpp
Previously, `--scheduler` would take the physical configuration, ignoring everything that was set with `numactl -N x`. Now, the affinity is taken into account meaning that `numactl -N 1 -m 1 ./hyriseBenchmarkTPCH` will (a) correctly use only CPUs from node 1 and (b) spawn only 56 workers instead of 224.
=> Fix NUMA node binding

src/benchmarklib/abstract_table_generator.cpp
When reusing .bin files but specifying a different chunk size, the latter is ignored. This PR adds a warning about this.
=> Benchmark: Warn about mismatching chunk sizes

src/CMakeLists.txt
After making some required changes in #1728, we can switch to c++20.
See the performance impact below.
Setup:
```
- Running in single-threaded mode
- 1 simulated clients are scheduling items in parallel
- Running benchmark in 'Ordered' mode
- Encoding is 'Dictionary'
- Chunk size is 100000
- Max runs per item is 10000
- Max duration per item is 60 seconds
- No warmup runs are performed
- Not caching tables as binary files
- JIT is disabled
- Benchmarking Queries: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, ]
- TPCH scale factor is 1
- Using prepared statements: no
```
Comparison result c++17 vs c++20:
```c++
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| Benchmark      | prev. iter/s …
```
=> Upgrade to c++20

resources/test_data/sqlite_testrunner_queries.sql, src/lib/logical_query_plan/create_view_node.cpp, src/lib/sql/sql_translator.cpp, src/lib/storage/lqp_view.cpp, src/lib/storage/lqp_view.hpp, src/test/logical_query_plan/create_view_node_test.cpp, src/test/operators/maintenance/create_view_test.cpp, src/test/operators/maintenance/drop_view_test.cpp, src/test/sql/sql_translator_test.cpp, src/test/statistics/cardinality_estimator_test.cpp, src/test/storage/storage_manager_test.cpp
- Close #1748 
- This partially reverts changes from #1692.
- The WITH feature (#1715) should use a similar solution.
=> View columns can have only single names

scripts/compare_benchmarks.py, src/benchmarklib/abstract_benchmark_item_runner.cpp, src/benchmarklib/abstract_benchmark_item_runner.hpp, src/benchmarklib/benchmark_config.cpp, src/benchmarklib/benchmark_config.hpp, src/benchmarklib/benchmark_item_result.cpp, src/benchmarklib/benchmark_item_result.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/benchmark_runner.hpp, src/benchmarklib/cli_config_parser.cpp, src/benchmarklib/file_based_benchmark_item_runner.cpp, src/benchmarklib/file_based_benchmark_item_runner.hpp, src/benchmarklib/tpcc/tpcc_table_generator.cpp, src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp, src/benchmarklib/tpch/tpch_benchmark_item_runner.hpp, src/lib/expression/expression_utils.hpp
I realized that we will need support for unsuccessful transactions (i.e., transaction aborts). As #1759 will change the JSON result format and this will change it again, I'd rather have only a single master commit.
Also makes the inclusion of SQL metrics optional, greatly reducing the size of the resulting JSON.
To make the review easier, this is a PR into #1759.
Sorry for making this slightly confusing. Hopefully, this makes the final TPC-C PR a bit easier to read.
=> TPC-C Preparation Part 2

requirements.txt, scripts/plot_run_duration_over_time.json, scripts/plot_run_duration_over_time.py
Adds a script that plots the duration of individual benchmark runs over time. Example:
Detailed version:
=> New plot script: Run duration over time

resources/test_data/sqlite_testrunner_queries.sql, src/lib/logical_query_plan/jit_aware_lqp_translator.cpp, src/test/logical_query_plan/jit_aware_lqp_translator_test.cpp
This pr fixes the issue that Aggregate in JIT could not handle COUNT(*) without a group by column.
`JitAggregate` always requires a value as a parameter for an aggregate function. Since COUNT(*) does not have a parameter, we just passed in the first value of the tuple as a dummy. This caused a problem if the tuple has no values and is now solved by adding a constant value to the tuple and using it as a parameter.
Closes #1741
=> [JIT] Fix bug #1741 - no support for COUNT(*) without group by

src/lib/optimizer/strategy/predicate_placement_rule.cpp, src/test/optimizer/strategy/predicate_placement_rule_test.cpp
fixes #1776 
In "full" Hyrise, this bug is only exposed if the PredicatePlacementRule is running alone. Otherwise, it is hidden by the JoinOrderingRule.
@mweisgut - since you are looking into diamonds anyway, could you have a look at this and see if you can come up with any additional edge cases?
=> Fix handling of diamonds in placement rule

scripts/test/hyriseConsole_test.py, src/lib/utils/check_table_equal.cpp, src/lib/utils/check_table_equal.hpp, src/lib/utils/sqlite_wrapper.cpp
By default, LIKE is case-insensitive in sqlite. This PR changes that behavior to match Hyrise's.
Also, it fixes the comparison of all-NULL columns.
There is still a mismatch in the table sizes between the imdb_data set that we are using and the one linked in the benchmark. That leads to some results being NULL as described in #1409. I don't see this as a big issue, as we are only using the JOB for internal comparisons. As a result, I suggest that this closes #1409.
=> Fix sqlite comparison

src/benchmark/tpch_data_micro_benchmark.cpp
fixes https://github.com/hyrise/hyrise/issues/1798:
> That should not have been committed.
=> Remove erroneously committed micro benchmarks

src/lib/logical_query_plan/base_non_query_node.hpp, src/lib/optimizer/strategy/predicate_placement_rule.cpp, src/test/optimizer/strategy/predicate_placement_rule_test.cpp
Fixes the problem with the PredicatePlacementRule identified in #1791. A quick benchmark run did not reveal any performance differences.
=> Fix predicate pushdown below diamond

scripts/test/hyriseBenchmarkTPCH_test.py, src/benchmarklib/abstract_table_generator.cpp, src/benchmarklib/abstract_table_generator.hpp, src/benchmarklib/benchmark_config.cpp, src/benchmarklib/benchmark_config.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/cli_config_parser.cpp, src/benchmarklib/tpch/tpch_table_generator.cpp, src/benchmarklib/tpch/tpch_table_generator.hpp, src/lib/logical_query_plan/stored_table_node.cpp, src/lib/optimizer/strategy/index_scan_rule.cpp, src/test/logical_query_plan/stored_table_node_test.cpp
* Sort two TPC-H tables (see the benchmark results below)
* Enabled `./hyriseBenchmarkTPCH --indexes` (even if the indexes don't help yet)
* Fixes the column pruning of index statistics in StoredTableNode
```
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| Benchmark      | prev. iter/s   | runs | new iter/s     | runs | change [%] | p-value (significant if <0.001) |
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| TPC-H 01       | 0.615062177181 | 37   | 0.539779722691 | 33   | -12%       |                          0.0000 |
| TPC-H 02       | 7.99957561493  | 480  | 8.06976127625  | 485  | +1%        |                          0.0000 |
| TPC-H 03       | …
```
=> Add optional indexes (currently unused) and sorting to TPC-H, fix StoredTableNode

resources/benchmark/tpcds/query_blacklist.cfg
Fix hyrise-mp/hyrise/issues/65
The trick was to find a [workaround](https://github.com/hyrise-mp/tpcds-result-reproduction/commit/91989ede0a8886f8b2545a6c7e8354996e1a89ac#diff-cb0b896c1c63ee0c445ac5cd54b4f59c) for #1820. 
Benchmark results on sidon (10 runs):
- Query 39a: 4.86s
- Query 39b: 4.92s
PQP for query 39a:
=> Execute TPC-DS query 39

src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp
Adds to #1832. It is not that we have predicates that "need to be processed as normal predicates". We only have predicates that MUST be executed within the joins and predicates that NEED NOT.
=> Update multi-predicate-join comment

src/lib/logical_query_plan/abstract_lqp_node.cpp, src/lib/logical_query_plan/abstract_lqp_node.hpp, src/lib/logical_query_plan/lqp_utils.hpp, src/test/logical_query_plan/aggregate_node_test.cpp, src/test/logical_query_plan/alias_node_test.cpp, src/test/logical_query_plan/create_prepared_plan_node_test.cpp, src/test/logical_query_plan/create_table_node_test.cpp, src/test/logical_query_plan/create_view_node_test.cpp, src/test/logical_query_plan/delete_node_test.cpp, src/test/logical_query_plan/drop_table_node_test.cpp, src/test/logical_query_plan/drop_view_node_test.cpp, src/test/logical_query_plan/dummy_table_node_test.cpp, src/test/logical_query_plan/insert_node_test.cpp, src/test/logical_query_plan/join_node_test.cpp, src/test/logical_query_plan/limit_node_test.cpp, src/test/logical_query_plan/mock_node_test.cpp, src/test/logical_query_plan/predicate_node_test.cpp, src/test/logical_query_plan/projection_node_test.cpp, src/test/logical_query_plan/sort_node_test.cpp, src/test/logical_query_plan/static_table_node_test.cpp, src/test/logical_query_plan/stored_table_node_test.cpp, src/test/logical_query_plan/union_node_test.cpp, src/test/logical_query_plan/update_node_test.cpp, src/test/logical_query_plan/validate_node_test.cpp, src/test/storage/table_column_definition_test.cpp
* Remove necessity to use const cast by making visit_lqp() support const LQPs
* HashEquals -> HashingAndEqualityCheck because "HashEquals" to me sound like "test whether hashes are equal", not "test whether hashing and equality checks work"
* Remove the left_input==right_input seed from the LQP hash - the only test that this broke was a IMO malformed test with an UpdateNode with only one input (should always be two, right?)
=> Add const LQP support to visit_lqp() and clean up LQP hashing

src/lib/operators/validate.cpp, src/lib/operators/validate.hpp
Currently, the `Validate` operator processes all chunks sequentially. Especially for large input tables this can be time-consuming.
This PR parallelizes the validation process on a chunk-level. Chunks of `100.000` rows and more are handled by individual`JobTask`s. 
Running the TPC-DS benchmark, we get the following results:
```
+----------------+-----------------+------+-----------------+------+------------+-----------------------------------------------+
| Benchmark      | prev. iter/s    | runs | new iter/s      | runs | change [%] |               p-value (significant if <0.001) |
+----------------+-----------------+------+-----------------+------+------------+-----------------------------------------------+
| 01             | 1.23315536976   | 74   | 1.33324241638   | 80   | +8% …
```
=> Optimize Validate operator to validate chunks in parallel

Jenkinsfile, scripts/test/hyriseBenchmarkTPCH_test.py, src/benchmarklib/abstract_table_generator.cpp, src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp, src/lib/visualization/abstract_visualizer.hpp, src/lib/visualization/lqp_visualizer.cpp, src/lib/visualization/lqp_visualizer.hpp, src/lib/visualization/pqp_visualizer.cpp, src/lib/visualization/pqp_visualizer.hpp
fixes #1840 
Also, as the query plans become more complex, this changes the arrowheads of multi-input nodes to identify the input sides. This is so that we don't mistake the visually left input of this semi join to be the probe side.
=> Fix chunk size in benchmarks, add join side in viz

src/test/cache/cache_test.cpp, src/test/operators/aggregate_test.cpp, src/test/operators/index_scan_test.cpp, src/test/operators/join_hash_types_test.cpp, src/test/operators/join_index_test.cpp, src/test/operators/join_test_runner.cpp, src/test/operators/operator_deep_copy_test.cpp, src/test/operators/sort_test.cpp, src/test/operators/table_scan_between_test.cpp, src/test/operators/table_scan_sorted_segment_search_test.cpp, src/test/operators/table_scan_string_test.cpp, src/test/operators/table_scan_test.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_encodings.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_jit.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_unencoded.cpp, src/test/statistics/chunk_statistics/range_filter_test.cpp, src/test/statistics/statistics_objects/counting_quotient_filter_test.cpp, src/test/statistics/statistics_objects/min_max_filter_test.cpp, src/test/statistics/statistics_objects/range_filter_test.cpp, src/test/storage/any_segment_iterable_test.cpp, src/test/storage/compressed_vector_test.cpp, src/test/storage/dictionary_segment_test.cpp, src/test/storage/encoded_segment_test.cpp, src/test/storage/encoded_string_segment_test.cpp, src/test/storage/materialize_test.cpp, src/test/storage/multi_segment_index_test.cpp, src/test/storage/segment_iterators_test.cpp, src/test/storage/simd_bp128_test.cpp, src/test/storage/single_segment_index_test.cpp, src/test/tpc/tpch_test.cpp
Updates the third party module of the Google Test framework.
With it goes the necessity to add an empty item at the list of some test instantiations and thus also some `NOLINT` are removed.
For `TYPED_TEST_SUITE` the problem remains (https://github.com/google/googletest/issues/2271).
=> Update Google Test

src/lib/sql/sql_pipeline.cpp, src/lib/sql/sql_pipeline.hpp, src/lib/storage/table.cpp, src/lib/utils/meta_table_manager.cpp, src/test/utils/meta_table_manager_test.cpp
* fixes #1787 
* fixes predicates on meta tables
* fixes UB if `get_result_table` was called on xvalue pipeline:
```
const auto result = SQLPipelineBuilder{"SELECT * FROM int_int"}
.create_pipeline()
.get_result_table();
```
As `get_result_table` would return a pair containing a reference to the result table, which is stored in the now expired pipeline, accessing the table was previously UB. We now copy the `shared_ptr<Table>` if necessary.
=> Add DESCRIBE as an alias for SHOW COLUMNS

src/lib/operators/table_scan/column_like_table_scan_impl.cpp
fixes #1839 - we still have some queries that run slower, but the -99% parts are gone. Given that we don't really optimize for the JOB, that should be good enough for now.
Splitting up `x LIKE '...' OR x LIKE '...'` into two predicates (#1791) enables the TableScan to use the ColumnLikeTableScanImpl. That implementation first builds a bitmap of the entire dictionary, then checks the value id against that bitmap. If the number of input rows is significantly lower than the size of the dictionary (because the input has already been filtered), that is a bad idea. Now, we only scan the entire dictionary if the filtered segment has no more unique values in the dictionary than rows in the input.
old:
regression:
new:
=> Fix performance regression in JOB

Jenkinsfile, src/lib/storage/encoding_type.hpp, src/test/base_test.hpp, src/test/operators/join_test_runner.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_encodings.cpp, src/test/storage/any_segment_iterable_test.cpp, src/test/storage/encoded_segment_test.cpp, src/test/storage/encoded_string_segment_test.cpp, src/test/storage/encoding_test.hpp, src/test/storage/materialize_test.cpp, src/test/storage/segment_iterators_test.cpp
This PR limits the testing of encoding types for sanitizer runs of hyriseSystemTest.
Further, it fixes #1673 by adding two fixed arrays of encoding types and all segment encoding specs to `encoding_types.hpp`. Tests now iterate over these lists (sometimes with explicit filtering in case some encodings to not support data types) instead of the cumbersome and error-prone listing of encodings (which lead to cases that encodings haven't been tested).
=> Clean up hyriseSystemTest and unify encoding enumerations

src/lib/optimizer/optimizer.cpp
Prune chunks after the BetweenCompositionRule ran, as `a >= 5 AND a <= 7` may not be prunable predicates while `a BETWEEN 5 and 7` is. Also prune only once all predicates are pushed down.
```
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| Benchmark      | prev. iter/s   | runs | new iter/s     | runs | change [%] | p-value (significant if <0.001) |
+----------------+----------------+------+----------------+------+------------+---------------------------------+
| TPC-H 01       | 0.60651409626  | 37   | 0.606586277485 | 37   | +0%        |                          0.9863 |
| TPC-H 02       | 8.91521930695  | 535  | 8.79386711121  | 528  | -1%        |                          0.0000 |
| TPC-H 03       | 6.18643331528  | …
```
=> Run chunk pruning after between composition

src/lib/expression/expression_utils.cpp, src/lib/expression/expression_utils.hpp, src/lib/sql/sql_translator.cpp, src/lib/statistics/cardinality_estimator.cpp, src/test/expression/expression_utils_test.cpp, src/test/statistics/cardinality_estimator_test.cpp
Estimating correlated parameters is tricky. Example: `SELECT c_custkey, (SELECT AVG(o_totalprice) FROM orders WHERE o_custkey = c_custkey) FROM customer`. If the subquery was executed for each customer row, assuming that the predicate has a selectivity matching that of searching for a single value would be reasonable. However, it is likely that the SubqueryToJoinRule will rewrite this query so that the CorrelatedParameterExpression will turn into an LQPColumnExpression that is part of a join predicate. However, since the JoinOrderingRule is executed before the SubqueryToJoinRule, it would create a different join order if it assumes `orders` to be filtered down to very few values.
For now, return a high selectivity (90%) for predicates that contain correlated parameters.
``` …
```
=> Better estimation for correlated parameters

src/lib/logical_query_plan/mock_node.cpp, src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.cpp, src/lib/optimizer/join_ordering/abstract_join_ordering_algorithm.hpp, src/test/logical_query_plan/create_prepared_plan_node_test.cpp, src/test/logical_query_plan/create_view_node_test.cpp, src/test/logical_query_plan/mock_node_test.cpp, src/test/optimizer/dp_ccp_test.cpp, src/test/optimizer/greedy_operator_ordering_test.cpp, src/test/optimizer/join_graph_test.cpp, src/test/optimizer/strategy/join_ordering_rule_test.cpp
To make the input sides more deterministic, we make sure that the larger input is on the right side. This helps future rules to identify common subplans. For plans with equal cardinalities, this might still result in non-deterministic orders. Deal with it once it becomes a problem - maybe use the hash? 
Also, adds the column names to the printed version of MockNodes. Trying to understand why two seemingly identical MockNodes were considered different took me longer than it should.
No performance difference in TPC-H yet - that will come with future rules.
=> Make left/right side of joins deterministic

src/benchmarklib/abstract_table_generator.cpp, src/lib/operators/get_table.cpp, src/test/operators/get_table_test.cpp
Currently, the order-by information is not carried through to the table scan. This PR adapts (i) the abstract table generator to add the sorted information to the chunks (in case sorting is requested for the benchmark) and (ii) the get table operator to forward and adapt (in case of column pruning) this information.
For the benchmarks, basically nothing changed. Only TPC-H Q3 has a qualifying scan, but the impact is not significant.
```
+----------------+-------------------+------+-------------------+------+------------+---------------------------------+
| Benchmark      | prev. iter/s      | runs | new iter/s        | runs | change [%] | p-value (significant if <0.001) |
+----------------+-------------------+------+-------------------+------+------------+---------------------------------+ …
```
=> Forward a chunk's ordered-by information to GetTable

src/lib/logical_query_plan/stored_table_node.hpp, src/lib/optimizer/strategy/chunk_pruning_rule.cpp, src/lib/optimizer/strategy/chunk_pruning_rule.hpp, src/lib/statistics/attribute_statistics.cpp, src/lib/statistics/attribute_statistics.hpp, src/lib/statistics/base_attribute_statistics.cpp, src/lib/statistics/base_attribute_statistics.hpp, src/lib/statistics/cardinality_estimator.cpp, src/lib/statistics/statistics_objects/abstract_histogram.cpp, src/lib/statistics/statistics_objects/abstract_histogram.hpp, src/lib/statistics/statistics_objects/abstract_statistics_object.cpp, src/lib/statistics/statistics_objects/abstract_statistics_object.hpp, src/lib/statistics/statistics_objects/histogram_domain.cpp, src/test/CMakeLists.txt, src/test/optimizer/strategy/chunk_pruning_rule_test.cpp, src/test/statistics/statistics_objects/generic_histogram_test.cpp
fixes #1672 
If a chunk is pruned, we update the table statistics. This is so that the selectivity of the predicate that was used for pruning can be correctly estimated. Example: For a table that has sorted values from 1 to 100 and a chunk size of 10, the predicate `x > 90` has a selectivity of 10%. However, if the ChunkPruningRule removes nine chunks out of ten, the selectivity is now 100%. Updating the statistics is important so that the predicate ordering can properly order the predicates. For the column that the predicate pruned on, we remove chunk.size() values that do not match the predicate from the histogram, assuming equidistribution among the pruned values. The other columns are simply scaled to reflect the reduced table size.
``` …
```
=> Update column statistics when chunks are pruned

src/lib/visualization/abstract_visualizer.hpp
We never (a) closed the tempfile and we (b) never deleted it. You might want to run `rm -f /tmp/hyrise_viz_*` on your machine(s).
fixes #1869
=> Fix tmpfile handling in visualization

scripts/compare_benchmarks.py
I always liked the colored version of this better. Now, we can have it on Github, too.
```diff
+----------------+----------------+------+---------------+------+------------+-----------------------------------------------+
| Benchmark      | prev. iter/s   | runs | new iter/s    | runs | change [%] |               p-value (significant if <0.001) |
+----------------+----------------+------+---------------+------+------------+-----------------------------------------------+
+| 01             | 20.7994117737  | 208  | 21.9238319397 | 220  | +5%        |                   (run time too short) 0.0000 |
+| 03             | 16.0511054993  | 161  | 28.5994300842 | 287  | +78%       |                   (run time too short) 0.0000 |
+| 06             | 16.8967514038  | 169  | 29.4084148407 | 295  | …
```
=> Format compare_benchmarks.py output for Github

CMakeLists.txt, DEPENDENCIES.md, Dockerfile, install.sh, scripts/coverage.sh, scripts/format.sh, src/CMakeLists.txt, src/benchmarklib/cli_config_parser.cpp, src/lib/operators/table_scan/abstract_table_scan_impl.hpp, src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp, src/lib/operators/table_scan/column_vs_value_table_scan_impl.hpp, src/lib/optimizer/join_ordering/join_graph.hpp, src/lib/storage/index/abstract_index.hpp, src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_index.hpp, src/lib/storage/index/group_key/composite_group_key_index.hpp, src/lib/storage/index/group_key/group_key_index.hpp, src/lib/storage/vector_compression/simd_bp128/simd_bp128_decompressor.hpp, src/lib/utils/performance_warning.hpp, src/lib/utils/plugin_manager.cpp, src/lib/utils/tracing/probes.hpp, src/test/testing_assert.hpp, third_party/CMakeLists.txt
Not upgrading to clang-9 as Ubuntu 19.04 does not have it in its default sources and 19.10 has just landed. With all the changes going on right now, let's wait for the dust to settle.
fixes #1077
=> Upgrade to clang-8

src/lib/logical_query_plan/lqp_utils.hpp
Working with LQP and stumbled upon this wording.
Not sure if we could merge `LQPUpwardVisitation` and `LQPVisitation`.
=> Correct two words in LQP utils

src/lib/operators/table_scan/abstract_table_scan_impl.hpp
The latest clang 9 does not like the line `;  // clang-format off` which is used to prevent clang-format from removing the indentation.
This has not been tested by the CI machine as the machine does not see the AVX512 code (happened on Nemea).
The simple "fix" is to use a `{}` over a `;`.
=> Fix table scan for clang 9 and AVX512 machines

src/lib/storage/lz4_segment/lz4_segment_iterable.hpp
When not erasing LZ4 iterables, it turned out that certain std algorithms cannot use the iterators. With @mrks 's help, these issues have been fixed.  This change further allows to use unerased LZ4 segments, which are of relevance for my compression selection work and @krichly's spatial work.
Further, it adds a slight change to the caching of blocks. With this change, an iterable that is accessed multiple times, can still profit from LZ4-block caching (will be relevant for upcoming changes to the segment accessors).
TPC-H (gcc, sf=1, nemea):
```diff
+----------------+-----------------------+------+----------------------+------+------------+-------------------+
| Benchmark      | prev. iter/s          | runs | new iter/s           | runs | change [%] |           p-value | …
```
=> Modifications to LZ4 iterable

src/test/optimizer/strategy/chunk_pruning_rule_test.cpp
The chunk pruning test is apparently supposed to test the pruning of compressed tables. But the tables are not compressed. This PR simply fixes a typo and adds compression.
=> Missing compression in chunk pruning tests

install.sh, scripts/format.sh, scripts/test/hyriseBenchmarkFileBased_test.py, scripts/test/hyriseBenchmarkJoinOrder_test.py, scripts/test/hyriseBenchmarkTPCH_test.py, src/benchmarklib/benchmark_sql_executor.cpp, src/benchmarklib/benchmark_sql_executor.hpp, src/benchmarklib/cli_config_parser.cpp, src/lib/operators/abstract_read_write_operator.cpp, src/lib/operators/abstract_read_write_operator.hpp, src/lib/optimizer/strategy/in_expression_rewrite_rule.cpp, src/lib/statistics/cardinality_estimator.cpp, src/test/optimizer/strategy/in_expression_rewrite_rule_test.cpp, src/test/statistics/cardinality_estimator_test.cpp
Some minor things that I had lying around. As none of these should have any effect on benchmarks etc., I hope that compressing them into one PR should be fine
* Make clang-format work independent of current clang version
* Make visualization work if benchmark item has multiple SQL pipelines (e.g., TPC-C)
* Make `ReadWriteOperatorState` printable
* Fix visualization of `x IN (...)` when the IN expression is rewritten to a join
=> A potpourri of smaller fixes

resources/test_data/tbl/meta_tables/meta_chunks.tbl, resources/test_data/tbl/meta_tables/meta_chunks_updated.tbl, resources/test_data/tbl/meta_tables/meta_columns.tbl, resources/test_data/tbl/meta_tables/meta_columns_updated.tbl, resources/test_data/tbl/meta_tables/meta_segments.tbl, resources/test_data/tbl/meta_tables/meta_segments_updated.tbl, resources/test_data/tbl/meta_tables/meta_tables.tbl, resources/test_data/tbl/meta_tables/meta_tables_updated.tbl, src/lib/utils/meta_table_manager.cpp, src/test/sql/sql_translator_test.cpp, src/test/utils/meta_table_manager_test.cpp
The meta table manager currently uses `table` as a column name. A student (thanks Caterina) just informed me that queries such as `select table, chunk_id from meta_chunks` can thus not be executed. While a simple `select "table"` is sufficient, I'd say we should better not have SQL keywords as column names.
Further, `column_name` & `column`  and `row_count` & `rows` have been unified.
=> SQL keyword "table" as column name in meta manager

src/lib/cache/abstract_cache_impl.hpp, src/lib/cache/cache.hpp, src/lib/cache/gdfs_cache.hpp, src/lib/sql/sql_pipeline_builder.hpp, src/test/cache/cache_test.cpp
This PR introduces the `frequency()` method to the cache. The GDFS cache (which is the only one used right now) has a nice `F` in the name and we should use that.
The function is not implemented for other cache. On the one hand, they aren't used anyways. On the other hand, as far as I can tell they do not store any frequency information.
=> Retrieve access frequency of cached elements

src/test/sql/sqlite_testrunner/sqlite_testrunner.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner.hpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_encodings.cpp, src/test/sql/sqlite_testrunner/sqlite_testrunner_unencoded.cpp
This has happened one time too often:
```
[ RUN      ] SQLiteTestRunnerEncodings/SQLiteTestRunner.CompareToSQLite/876
Segmentation fault (core dumped)
script returned exit code 139
```
By making the line number within the .sql file part of the test names, it will be easier to trace this back to the SQL query that caused the segfault:
```
[ RUN      ] SQLiteTestRunnerEncodings/SQLiteTestRunner.CompareToSQLite/Line309WithUnencoded
[       OK ] SQLiteTestRunnerEncodings/SQLiteTestRunner.CompareToSQLite/Line309WithUnencoded (12 ms)
```
=> SQLite test runner: Print line numbers

src/benchmark/operators/join_benchmark.cpp, src/benchmarklib/benchmark_table_encoder.cpp, src/lib/expression/evaluation/expression_evaluator.cpp, src/lib/operators/alias_operator.cpp, src/lib/operators/difference.cpp, src/lib/operators/export_binary.cpp, src/lib/operators/export_csv.cpp, src/lib/operators/index_scan.cpp, src/lib/operators/join_hash/join_hash_steps.hpp, src/lib/operators/join_index.cpp, src/lib/operators/join_nested_loop.cpp, src/lib/operators/join_sort_merge/column_materializer.hpp, src/lib/operators/limit.cpp, src/lib/operators/multi_predicate_join/multi_predicate_join_evaluator.cpp, src/lib/operators/product.cpp, src/lib/operators/projection.cpp, src/lib/operators/sort.cpp, src/lib/operators/table_scan.cpp, src/lib/operators/union_all.cpp, src/lib/operators/validate.cpp, src/lib/storage/chunk_encoder.cpp, src/lib/storage/table.hpp, src/lib/tasks/chunk_compression_task.cpp
My seminar group found the reference to #1686 confusing and somehow ended up at #1643 (?!) without understanding why we checked for nullptr. Hopefully this is a bit clearer.
=> Improve get_chunk == nullptr documentation

src/lib/optimizer/optimizer.cpp, src/lib/optimizer/strategy/subquery_to_join_rule.cpp, src/test/optimizer/strategy/subquery_to_join_rule_test.cpp
Fixes #1940, i.e., the SubqueryToJoinRule modifying the original subquery LQP without any regard for other consumers of that subquery LQP.
=> Fix plan reuse in SubqueryToJoinRule

third_party/CMakeLists.txt
It looks like `--prefix=<...>` does not work too well if the prefix has a whitespace. We did not spend too long trying to get this to work as (1) this is easy to fix by the user, (2) it has only come up once in a long time, and (3) Makefiles are notoriously bad with spaces: http://savannah.gnu.org/bugs/?712
fixes #1953 (well, doesn't...)
=> Refuse build on paths with whitespaces

src/lib/statistics/cardinality_estimator.cpp, src/test/statistics/cardinality_estimator_test.cpp
Used in 12,16,19,22, so 5 and 8 are outliers.
```diff
+----------------+----------------+-------+----------------+-------+------------+---------+
| Benchmark      | prev. iter/s   | runs  | new iter/s     | runs  | change [%] | p-value |
+----------------+----------------+-------+----------------+-------+------------+---------+
| TPC-H 01       | 0.591941773891 | 36    | 0.612216353416 | 37    | +3%        |  0.0000 |
| TPC-H 02       | 68.1781997681  | 4091  | 69.1267700195  | 4148  | +1%        |  0.0698 |
| TPC-H 03       | 6.9803276062   | 419   | 7.15190076828  | 430   | +2%        |  0.0000 |
| TPC-H 04       | 6.87540578842  | 413   | 6.80770301819  | 409   | -1%        |  0.0882 |
+| TPC-H 05       | 3.4995496273   | 211   | 3.74816703796  | 225   | +7%        |  0.0000 |
| TPC-H …
```
=> CardinalityEstimator: Estimate IN expressions

src/lib/operators/projection.cpp
For any table, we require all segments to be either ReferenceSegments or not. Thus, when the Projection creates a single ValueSegment, all other ReferenceSegments have to be converted into ValueSegments. Currently, this happens via the ExpressionEvaluator, which has a couple of unnecessary abstractions for this. By doing this step in the projection itself, we can save some time:
```diff
+----------------+----------------+-------+----------------+-------+------------+---------+
| Benchmark      | prev. iter/s   | runs  | new iter/s     | runs  | change [%] | p-value |
+----------------+----------------+-------+----------------+-------+------------+---------+
| TPC-H 01       | 0.591941773891 | 36    | 0.614538609982 | 37    | +4%        |  0.0000 |
| TPC-H 02       | 68.1781997681  | 4091 …
```
=> Projection: Better forward of ReferenceSegments

src/lib/CMakeLists.txt, src/lib/operators/table_scan/column_is_null_table_scan_impl.cpp, src/lib/operators/table_scan/column_vs_column_table_scan_impl.cpp, src/lib/storage/chunk_encoder.cpp, src/lib/storage/create_iterable_from_reference_segment.ipp, src/lib/storage/create_iterable_from_segment.hpp, src/lib/storage/create_iterable_from_segment.ipp, src/lib/storage/reference_segment/reference_segment_iterable.hpp, src/lib/storage/segment_iterables/any_segment_iterable.hpp, src/lib/storage/value_segment/value_segment_iterable.hpp, src/lib/types.hpp, src/test/operators/join_hash_steps_test.cpp
When we are looking at a ReferenceSegment that points at a single segment, it makes more sense to use that segments iterator instead of using accessors:
```diff
+----------------+----------------+-------+----------------+-------+------------+---------+
| Benchmark      | prev. iter/s   | runs  | new iter/s     | runs  | change [%] | p-value |
+----------------+----------------+-------+----------------+-------+------------+---------+
+| TPC-H 01       | 0.591941773891 | 36    | 0.684819757938 | 42    | +16%       |  0.0000 |
| TPC-H 02       | 68.1781997681  | 4091  | 66.9826126099  | 4019  | -2%        |  0.0202 |
+| TPC-H 03       | 6.9803276062   | 419   | 7.40183210373  | 445   | +6%        |  0.0000 |
| TPC-H 04       | 6.87540578842  | 413   | 6.71953058243  | 404   | -2%        | …
```
=> ReferenceSegment: Use iterable instead of accessor where possible

Jenkinsfile, src/plugins/mvcc_delete_plugin.cpp, src/test/plugins/mvcc_delete_plugin_system_test.cpp
* Hopefully fixes the MVCC Delete Plugin Freezes
* Should help us in tracking down the spurious CI fails. Adds 5 minutes to those steps, but since we are usually waiting for clang-tidy anyway, it should not be noticeable.
=> CI: RelWithDebInfo for TSAN

src/lib/expression/abstract_expression.cpp, src/lib/logical_query_plan/abstract_lqp_node.cpp
For an expensive `operator==`, we should check for object identify before diving deep into the comparison of input nodes / expressions.
```diff
+----------------+----------------+-------+---------------+-------+------------+---------+
| Benchmark      | prev. iter/s   | runs  | new iter/s    | runs  | change [%] | p-value |
+----------------+----------------+-------+---------------+-------+------------+---------+
| TPC-H 01       | 0.675015389919 | 41    | 0.68032002449 | 41    | +1%        |  0.2273 |
| TPC-H 02       | 69.8773880005  | 4194  | 72.3441390991 | 4341  | +4%        |  0.0000 |
| TPC-H 03       | 7.38249874115  | 443   | 7.3743019104  | 443   | -0%        |  0.8475 |
| TPC-H 04       | 6.83276081085  | 410   | 7.05099821091 | 424   | +3%        |  0.0000 |
| TPC-H 05       | …
```
=> Make LQP/Expression equals more efficient

scripts/test/hyriseConsole_test.py, src/bin/console/console.cpp, src/lib/import_export/binary/binary_parser.cpp, src/lib/import_export/binary/binary_parser.hpp, src/test/lib/import_export/binary/binary_parser_test.cpp
While working on another PR, I found that tables are not encoded when being imported (e.g, using `load tpch_cached_tables/sf-0.100000/lineitem.bin lineitem LZ4`)in the console (not only here). 
The reason was that the binary importer does not finalize chunk. This PR finalizes chunk in the binary parser and adds tests.
Maybe an open discussion: do we want to finalize the last chunk? I'd say no, since this is unexpected behaviour in my opinion. It also could lead to cases where we finalize a single chunk with a few rows.
=> Enable encoding after binary import

src/lib/operators/projection.cpp
Creating string vectors and copying strings is expensive. In cases where the projection needs to materialize a dictionary segment without modifications, it is cheaper to reuse the existing dictionary and simply materialize the value ids.
```diff
+----------------+----------------+-------+----------------+-------+------------+---------+
| Benchmark      | prev. iter/s   | runs  | new iter/s     | runs  | change [%] | p-value |
+----------------+----------------+-------+----------------+-------+------------+---------+
+| TPC-H 01       | 0.672982573509 | 41    | 0.747316241264 | 45    | +11%       |  0.0000 |
| TPC-H 02       | 71.4696502686  | 4289  | 71.8923034668  | 4315  | +1%        |  0.3648 |
| TPC-H 03       | 7.58716583252  | 456   | 7.53408670425  | 453   | -1%        |  0.1666 | …
```
=> Projection: Forward dictionaries when materializing

Jenkinsfile, resources/.tsan-ignore.txt, scripts/test/hyriseBenchmarkTPCC_test.py, src/benchmarklib/tpcc/tpcc_table_generator.cpp, src/benchmarklib/tpcc/tpcc_table_generator.hpp, src/lib/cache/cache.hpp, src/lib/cache/gdfs_cache.hpp, src/lib/cache/gds_cache.hpp, src/lib/cache/lru_cache.hpp, src/lib/cache/lru_k_cache.hpp, src/lib/cache/random_cache.hpp, src/lib/operators/insert.cpp, src/lib/operators/join_hash/join_hash_steps.hpp, src/lib/operators/join_sort_merge.cpp, src/lib/visualization/abstract_visualizer.hpp, src/test/cache/cache_test.cpp, src/test/operators/join_test_runner.cpp
The recent TPC-C fails were caused by improved performance, which caused more MT issues to surface
* Cache::try_get did not acquire the mutex, so the GDFSCache got corrupted
* TPCCTableGenerator called a method on an expired object
* JoinHash could not deal with the table size / chunk count increasing while the table was being processed
Once this is merged, I can bring Jenkins back to 4 workers.
=> Fix Multi-threading issues

src/benchmark/operators/table_scan_sorted_benchmark.cpp, src/benchmark/tpch_data_micro_benchmark.cpp
The effect of not running the micro benchmarks has shown. One issue in the sort table scan benchmark was that the `ChunkEncoder` no longer supports encoding of mutable chunks (it's now the writers task to finalize chunks). The other issue was that a scale factor of 0.001f for the TPC-H data generator is no longer possible. Changed to 0.01f.
=> Fix two small issues in the micro benchmarks

Jenkinsfile, src/benchmark/tpcc_benchmark.cpp, src/benchmarklib/tpcc/tpcc_table_generator.cpp, src/benchmarklib/tpcc/tpcc_table_generator.hpp, src/bin/console/console.cpp
Fixes #1988. While I was looking at it, I made the data type for `num_warehouses` consistent because the TPCCTableGenerator was taking an `int` in the constructor and then storing that into a `size_t`.
=> Fix generate_tpcc in Console (#1988)

src/benchmarklib/benchmark_runner.cpp, src/lib/cache/cache.hpp, src/lib/hyrise.cpp, src/lib/hyrise.hpp, src/lib/sql/sql_pipeline_builder.cpp, src/lib/sql/sql_pipeline_builder.hpp, src/test/base_test.hpp, src/test/sql/query_plan_cache_test.cpp, src/test/sql/sql_pipeline_test.cpp
This PR brings back the possibility to access the cache implementation that is used. This is necessary to access certain methods that are not implemented for all cache implementations (e.g., the access counter via `frequency()` in GDFS). This method is called `unsafe_cache()` in accordance with the recent changes to the cache (#1980) and to denote that this access is inherently unsafe as concurrent modifications are likely to happen.
Further:
* added a test that documents the behaviour of `default_pqp_cache` which was not obvious to me, thus it might help others as well
* removed `frequency()` from cache.hpp as it is not part of the abstract cache interface anyways (see discussion in #1932)
=> Enable Cache Implementation Access

resources/tpch_validation_queries.sql, src/benchmarklib/tpch/tpch_queries.cpp
We've never removed the comment about the TPC-H query parameters being hardcoded, even though we changed that a looong time ago.
=> TPC-H: Remove comment about non-random values

Jenkinsfile
Hopefully this stops CI from ruining everyone's day.
Seems to be a known issue: https://gitlab.kitware.com/cmake/cmake/issues/19923
Also removes the no-numa builds. We don't do too much differently there and the no-libnuma support is tested in the mac build anyway.
=> Jenkins: disable ccache for clang

scripts/compare_benchmarks.py, scripts/plot_operator_breakdown.py, src/lib/visualization/pqp_visualizer.cpp, src/lib/visualization/pqp_visualizer.hpp
This adds a table at the lower right corner of each PQP visualization that shows the aggregate runtime per operator:
Also, this adds a script that accumulates this information over different *PQP.svg files:
I don't particularly like the colors but haven't found a nice color scheme that doesn't imply some type of ordering.
=> Plot operator breakdown

resources/test_data/sqlite_testrunner_queries.sql, src/lib/optimizer/strategy/column_pruning_rule.cpp
When using `CREATE TABLE FROM`, the column pruning rule has to consider all columns as required.
fixes #1996
=> Fix CREATE TABLE FROM

scripts/test/hyriseBenchmarkFileBased_test.py, scripts/test/hyriseBenchmarkJoinOrder_test.py, scripts/test/hyriseBenchmarkTPCH_test.py, src/benchmarklib/abstract_table_generator.cpp, src/benchmarklib/benchmark_config.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/cli_config_parser.cpp, src/test/tpc/tpcc_test.cpp
The binary dumps have no information if the entire table is sorted. As such, we currently re-sort and re-encode TPC-H tables. By checking if the table is already sorted, we can avoid this step and reduce the benchmark startup time from 0m30.447s to 0m16.147s. This is not the perfect solution and storing the flag in the table would be nicer, but at least this fixes #1864.
Also, this changes the default to cached binary tables, use `--dont_cache_binary_tables` to disable.
Before:
```
- Loading/Generating tables
[...]
-  Loading table "orders" from cached binary "tpch_cached_tables/sf-1.000000/orders.bin" (183 ms 491 µs)
[...]
-  Loading table "lineitem" from cached binary "tpch_cached_tables/sf-1.000000/lineitem.bin" (620 ms 853 µs)
- Loading/Generating tables done (1 s 45 ms)
- Sorting …
```
=> TPC-H: Don't sort binary tables again, use cache by default

src/lib/logical_query_plan/abstract_lqp_node.cpp, src/lib/logical_query_plan/abstract_lqp_node.hpp, src/lib/logical_query_plan/aggregate_node.cpp, src/lib/logical_query_plan/aggregate_node.hpp, src/lib/logical_query_plan/alias_node.cpp, src/lib/logical_query_plan/alias_node.hpp, src/lib/logical_query_plan/base_non_query_node.cpp, src/lib/logical_query_plan/base_non_query_node.hpp, src/lib/logical_query_plan/delete_node.cpp, src/lib/logical_query_plan/delete_node.hpp, src/lib/logical_query_plan/dummy_table_node.cpp, src/lib/logical_query_plan/dummy_table_node.hpp, src/lib/logical_query_plan/insert_node.cpp, src/lib/logical_query_plan/insert_node.hpp, src/lib/logical_query_plan/join_node.cpp, src/lib/logical_query_plan/join_node.hpp, src/lib/logical_query_plan/mock_node.cpp, src/lib/logical_query_plan/mock_node.hpp, src/lib/logical_query_plan/projection_node.cpp, src/lib/logical_query_plan/projection_node.hpp, src/lib/logical_query_plan/static_table_node.cpp, src/lib/logical_query_plan/static_table_node.hpp, src/lib/logical_query_plan/stored_table_node.cpp, src/lib/logical_query_plan/stored_table_node.hpp, src/lib/logical_query_plan/union_node.cpp, src/lib/logical_query_plan/union_node.hpp, src/lib/logical_query_plan/update_node.cpp, src/lib/logical_query_plan/update_node.hpp, src/lib/optimizer/strategy/column_pruning_rule.cpp, src/lib/sql/sql_translator.cpp
`AbtractLQPNode` defines the following interface for `column_expressions()`:
```cpp
/**
* @return The Expressions defining each column that this node outputs
*/
virtual const std::vector<std::shared_ptr<AbstractExpression>>& column_expressions() const;
```
Currently, subclasses have to declare a local member to fulfill the const-ref return value requirement. E.g.:
```cpp
private:
mutable std::vector<std::shared_ptr<AbstractExpression>> _column_expressions;
```
Some classes like `StoredTableNode` use it for caching purposes. Other classes like `AggregateNode` do not profit from it in any way. 
This PR removes the const-ref requirement to streamline the code of classes such as `AggregateNode`. 
Caching is still possible and there do not seem to be any drawbacks.
**TPC-H** with `-s 0.1` on …
=> Change interface of column_expressions() – No more const-ref

src/lib/operators/get_table.cpp, src/test/operators/get_table_test.cpp
This PR fixes a wrong order information of chunks which gets corrupted when columns are pruned.
For the pruned `order` table in the TPC-H benchmark, rather by luck, the correct sorting information was kept after column pruning (used in queries 3, 4, 5, and 10, but almost no effect on overall running time). For the `lineitem` table, the order information was not properly set for queries 1, 6, 14, and 15. After this PR, these are now correctly using sorted scans.
Benchmarks are **without** the iterator fix.
**Clang:**
```diff
+----------------+--------------------+-------+--------------------+-------+------------+---------+
| Benchmark      | prev. iter/s       | runs  | new iter/s         | runs  | change [%] | p-value |
+----------------+--------------------+-------+--------------------+-- …
```
=> Fix: order information can be corrupt when columns are pruned

src/benchmarklib/synthetic_table_generator.cpp, src/lib/statistics/generate_pruning_statistics.cpp, src/lib/storage/chunk_encoder.cpp, src/lib/storage/storage_manager.cpp, src/test/optimizer/strategy/chunk_pruning_rule_test.cpp, src/test/storage/storage_manager_test.cpp
This PR create `ChunkPruningStatistics` whenever tables are added to the storage manager.
When tables are added to the storage manager, currently only table statistics are created but no chunk pruning statistics. That leads to cases when data is loaded and no chunk pruning takes place, because the `ChunkPruningRule` cannot find any chunk pruning statistics.
Currently, chunk pruning statistics are generated when data is encoded. Hence, the case of no pruning statistics usually does not happen in our benchmarks.
Moreover, we currently might create the statistics several times as `generate_chunk_pruning_statistics(table)` did not check for their presence. This leads to a reduce encoding times for TPC-H SF 1:
* Dictionary: from `3 s 857 ms` to `3 s 184 ms` (statistics creation is optimized …
=> Create chunk pruning statistics in StorageManager::AddTable

src/lib/utils/meta_tables/abstract_meta_table.hpp, src/lib/utils/meta_tables/segment_meta_data.cpp, src/lib/utils/settings/abstract_setting.hpp
When not using pre-compile headers, the last master commit introduces some problems due to missing includes.
This PR adds the missing includes (forwarding declaration was not sufficient).
=> Fix: missing includes

src/benchmark/file_based_benchmark.cpp, src/benchmark/join_order_benchmark.cpp, src/benchmark/tpcc_benchmark.cpp, src/benchmark/tpcds_benchmark.cpp, src/benchmark/tpch_benchmark.cpp, src/benchmarklib/benchmark_config.cpp, src/benchmarklib/benchmark_config.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/cli_config_parser.cpp, src/benchmarklib/cli_config_parser.hpp
fixes #1926 
*Deleted code is bug-free code.*
The diff is easier to read if you enable "Hide whitespace changes".
=> Get rid of benchmarks' JSON config

src/lib/storage/segment_accessor.hpp, src/test/storage/segment_accessor_test.cpp
When working on the segment accessors, I stumpled upon an arbitrary values for the member `_accesses`. This PR simply initializes the variable.
=> Initialize accesses variable with zero

Jenkinsfile, src/lib/sql/sql_translator.hpp
Same as with #2042. If people continue to disable PCH (I know I am not the only one), we might want to automatically check for building without it.
=> Add missing forward declaration

src/benchmarklib/benchmark_table_encoder.cpp, src/lib/storage/chunk_encoder.cpp, src/lib/storage/encoding_type.hpp, src/lib/storage/segment_encoding_utils.cpp, src/lib/storage/segment_encoding_utils.hpp, src/test/base_test.cpp, src/test/base_test.hpp, src/test/memory/segments_using_allocators_test.cpp, src/test/storage/chunk_test.cpp, src/test/storage/dictionary_segment_test.cpp, src/test/storage/encoded_segment_test.cpp, src/test/storage/encoded_string_segment_test.cpp, src/test/storage/fixed_string_dictionary_segment_test.cpp, src/test/storage/group_key_index_test.cpp, src/test/storage/lz4_segment_test.cpp, src/test/storage/segment_accessor_test.cpp
This PR mainly introduces a function to the encoding segment utils that allows to receive the segment encoding spec. This function can be used to check if an encoding is really required or if the encoding is already in place (needed for current work on a plugin).
The segment encoding spec has also changed a little bit to make working with it simpler.
=> Small changes to segment encoding

src/lib/utils/size_estimation_utils.hpp
This mini PR changes the seed to be static in the size estimation utils.
The size estimation utils are used to determine the size of string segments, for which random sampling is used. Currently, the seed is random with the effect of steadily changing values for the size of a segment. Since the segments don't change, the size should not change as well.
This effect is especially obvious when the memory usage is steadily requested and visualized (e.g., in the bachelor's project's cockpit).
The potential short comings of this approach are only theoretical in my opinion as the meta table is not meant to be requested multiple times in order to capture a more accurate estimate.
If this would be the case, we could add another Sampling Enum value (SampledStatic, SampledRandom), but I don't see …
=> Size estimation utils: make seed static

resources/test_data/sqlite_testrunner_queries.sql, src/lib/logical_query_plan/aggregate_node.cpp, src/lib/sql/sql_translator.cpp, src/test/sql/sql_translator_test.cpp
These queries are currently broken because the SQLTranslator incorrectly identifies the aggregate function as having already been calculated (see #1902):
```
SELECT COUNT(*) FROM (SELECT COUNT(*) FROM t WHERE a <= 1234) t2
SELECT COUNT(a) FROM (SELECT a, COUNT(a) FROM t GROUP BY a) t2
SELECT AVG(a) FROM (SELECT a, AVG(a) FROM t GROUP BY a) t3
```
As long as this (1) does not produce wrong results and (2) does not get in the way of experiments or benchmarks, it feels more like a cosmetic issue. This PR introduces a check for these cases.
=> Catch duplicate aggregate functions

src/lib/storage/dictionary_segment/dictionary_encoder.hpp, src/lib/storage/fixed_string_dictionary_segment.cpp, src/lib/storage/fixed_string_dictionary_segment/fixed_string_vector.cpp, src/lib/storage/fixed_string_dictionary_segment/fixed_string_vector.hpp, src/lib/storage/frame_of_reference_segment.cpp, src/lib/storage/lz4_segment.cpp, src/lib/storage/resolve_encoded_segment_type.hpp, src/lib/storage/run_length_segment.cpp, src/lib/storage/value_segment.cpp, src/test/base_test.hpp, src/test/memory/segments_using_allocators_test.cpp
While working on something else, I noticed that 
* FixedStringDictionarySegments did not correctly implement copy_using_allocator (related to #623),
* this was not tested because the FixedStringDictionary was not included in the list of encodings to test, and
* the existing tests did not use external memory for pmr_strings.
All should be fixed now.
Also, this fixes and tests that segment access counters are persistent across migrations.
=> Fix PMR in FixedStringDictionarySegments, include in tests

scripts/plot_operator_breakdown.py
After reviewers rightly complained about this, I made another approach. This uses Cubehelix, which gradually changes all of HSV:
https://ifweassume.blogspot.com/2013/05/cubehelix-or-how-i-learned-to-love.html
Additionally, I added some light hatching. To have a look at how this looks in grayscale, I used
```
\gs  -sOutputFile=output.pdf  -sDEVICE=pdfwrite  -sColorConversionStrategy=Gray  -dProcessColorModel=/DeviceGray  -dCompatibilityLevel=1.4  -dNOPAUSE  -dBATCH -dAutoRotatePages=/None operator_breakdown.pdf
```
I won't say which one is the old and which one is the new. If you can't tell, please simply close this PR. ;)
=> Improve colors of scripts/plot_operator_breakdown.py

src/benchmark/tpch_data_micro_benchmark.cpp, src/benchmarklib/benchmark_sql_executor.cpp, src/bin/console/console.cpp, src/lib/expression/evaluation/expression_evaluator.cpp, src/lib/operators/abstract_join_operator.cpp, src/lib/operators/abstract_operator.cpp, src/lib/operators/operator_performance_data.cpp, src/lib/operators/operator_performance_data.hpp, src/lib/scheduler/operator_task.cpp, src/lib/scheduler/operator_task.hpp, src/lib/server/query_handler.cpp, src/lib/sql/sql_pipeline.cpp, src/lib/sql/sql_pipeline.hpp, src/lib/sql/sql_pipeline_builder.cpp, src/lib/sql/sql_pipeline_builder.hpp, src/lib/sql/sql_pipeline_statement.cpp, src/lib/sql/sql_pipeline_statement.hpp, src/lib/storage/table.cpp, src/lib/storage/table.hpp, src/lib/types.hpp, src/lib/visualization/abstract_visualizer.hpp, src/lib/visualization/pqp_visualizer.cpp, src/test/operators/delete_test.cpp, src/test/operators/operator_deep_copy_test.cpp, src/test/operators/table_scan_test.cpp, src/test/scheduler/scheduler_test.cpp, src/test/sql/sql_pipeline_test.cpp, src/test/tasks/operator_task_test.cpp
* For each operator, this stores the resulting chunk and row count in OperatorPerformanceData
* As a result, we don't need the result table anymore to visualize the plan (fixes #1646)
* As a result of that, we don't need CleanupTemporaries anymore.
* To reduce the impact of having to calculate the row_count, we now cache the row count for reference tables.
```diff
+----------------+--------------------+-------+--------------------+-------+------------+---------+
| Benchmark      | prev. iter/s       | runs  | new iter/s         | runs  | change [%] | p-value |
+----------------+--------------------+-------+--------------------+-------+------------+---------+
| TPC-H 01       | 1.2954007387161255 | 78    | 1.2995855808258057 | 78    | +0%        |  0.4136 |
+| TPC-H 02       | …
```
=> Store row count in performance data, don't keep temporaries

Dockerfile, Jenkinsfile
Pretty sure #2027 was caused by `make` spawning too many processes.
@cH3n7i, could you please check out this branch and check if this fixes #2027?
=> Dockerfile: Set number of cores for make -j

src/lib/expression/abstract_expression.cpp, src/test/logical_query_plan/aggregate_node_test.cpp
For `operator==` on an expression, it makes sense to first compare the expression itself before recursing into the inputs.
When hashing, we do not need to consider each and every part of the expression tree. As a hash comparison is always followed by a call to `operator==`, we will have to recurse anyway and while `operator==` can use early outs once it detected a difference, `hash` cannot.
Benchmark numbers for SF 0.01 (which places more load on the optimizer and has more complex LQPs than TPC-C):
```diff
+----------------+--------------------+--------+--------------------+--------+------------+---------+
| Benchmark      | prev. iter/s       | runs   | new iter/s         | runs   | change [%] | p-value |
+----------------+--------------------+--------+--------------------+--------+------ …
```
=> Expression: faster equals and hash

src/lib/server/server.cpp, src/lib/server/server.hpp, src/test/server/server_test_runner.cpp
#1977 showed issues with the server stopping before all sessions are closed. To quote from the new test:
> Test that open sessions are allowed to finish before the server is destroyed. This is more relevant for tests than for the actual execution. In "real-life", i.e., during our experiments, we usually simply kill the server. In tests however, the server finishing while sessions might not be completely finished could lead to issues like #1977.
Benchmark:
```
echo 'CREATE TABLE t (a INT)' | psql -h localhost -p 1241
echo 'SELECT * FROM t;' > test
pgbench -h localhost -p 1241 -f test -n -c 100 -j 100 -T 10
```
old:
> tps = 151788.790109 (including connections establishing)
> tps = 152061.524404 (excluding connections establishing)
new:
> tps = 152625.496717 (including connections …
=> Let server sessions finish before exiting

Jenkinsfile, src/lib/operators/aggregate_hash.cpp, src/lib/operators/table_scan/abstract_table_scan_impl.hpp, src/lib/operators/table_scan/column_vs_column_table_scan_impl.cpp, src/lib/resolve_type.hpp, src/lib/storage/pos_lists/entire_chunk_pos_list.cpp, src/lib/storage/pos_lists/entire_chunk_pos_list.hpp, src/lib/storage/pos_lists/rowid_pos_list.hpp, src/lib/storage/reference_segment/reference_segment_iterable.hpp, src/lib/storage/segment_iterables.hpp, src/lib/storage/segment_iterables/any_segment_iterable.hpp, src/lib/utils/load_table.cpp
```
ninja clean; time ninja hyriseBenchmarkTPCH
nemea, single node          Macbook 16"
gcc                         clang
master before PR commit
debug (with unity)
real  1m29.816s         1m47.360s
user  10m7.729s         14m0.838s
release (no unity)
real  3m36.696s         6m2.243s
user  31m29.549s        59m31.819s
master with PR commit
debug
real  1m30.820s         1m47.463s
user  10m30.046s        14m17.649s
release
real  6m27.217s         10m4.363s
user  43m37.977s        77m10.721s
now (dffdabaae4d35123a9080d3c86f0ec82df841c5d)
debug
real  1m30.643s         1m47.410s
user  10m12.337s        14m2.814s
release
real  3m11.059s         7m2.953s
user  34m10.579s        67m41.654s
```
I ran a couple of benchmarks. Unfortunately, they are not super-conclusive. The only thing I can say is …
=> Reduce compile time impact of static PosList polymorphism

src/benchmarklib/abstract_table_generator.cpp
Some benchmarks define sort orders, e.g. lineitem is sorted by l_shipdate. To avoid unnecessary sorting, the AbstractTableGenerator performs a check whether the table is already sorted. This led to an endless loop, if the first value of the sorting column is NULL.
fixes #2079, thanks @aloeser
=> Benchmark: fix NULL detection

scripts/analyze_gtest_runtime.py, src/test/sql/sql_translator_test.cpp
fixes #2083, adds a new script to list the most expensive tests:
```
[:~/Projekte/Opossum/Git/build] mrks/test_times(+30/-17)+* ± ../scripts/analyze_gtest_runtime.py old.json
+----------------------------------------------------+--------+---------------------------------------------------------------------------------+-------+
| 20 most expensive test suites                      | s      | 20 most expensive tests                                                         | s     |
+----------------------------------------------------+--------+---------------------------------------------------------------------------------+-------+
| JoinNestedLoop/JoinTestRunner                      | 17.265 | BinaryWriterTest.LZ4MultipleBlocks                                              | 0.596 |
| …
```
=> Reduce test times

src/benchmarklib/benchmark_runner.cpp
Why estimate if we can compute the real table size?
=> BenchmarkRunner: Compute real table size

src/lib/operators/abstract_operator.cpp, src/lib/operators/aggregate_hash.cpp, src/lib/operators/aggregate_sort.cpp, src/lib/operators/join_index.cpp, src/lib/operators/join_nested_loop.cpp, src/lib/storage/table.cpp, src/lib/types.hpp, src/test/operators/print_test.cpp, src/test/storage/table_test.cpp
In #2085, I found that the aggregate operator created empty chunks, which the sort did not handle properly. This tightens the rules for empty chunks, allowing them only as the last, mutable chunk for data tables. It also fixes the operators that were violating this new rule.
=> Properly protect against empty chunks

src/lib/logical_query_plan/abstract_lqp_node.cpp, src/lib/optimizer/strategy/column_pruning_rule.cpp, src/test/optimizer/strategy/column_pruning_rule_test.cpp
#2011 prepared Hyrise for set operations. As part of that, the ColumnPruningRule was changed. This halved the performance of Q19. For the Positions mode in the UnionNode, this change is definitely not necessary. Skipping the additions of the column_expressions fixes the performance regression. For the other, upcoming modes, I am not sure. I removed it for now.
fixes #2115 (won't fix the other issue mentioned there)
```diff
+----------------+--------------------+-------+--------------------+-------+------------+---------+
| Benchmark      | prev. iter/s       | runs  | new iter/s         | runs  | change [%] | p-value |
+----------------+--------------------+-------+--------------------+-------+------------+---------+
| TPC-H 01       | 1.2329988479614258 | 74    | 1.2363585233688354 | 75 …
```
=> Fix performance regression in ColumnPruningRule

src/test/operators/join_test_runner.cpp, src/test/tpc/tpch_db_generator_test.cpp
The JoinTestRunner caches the verification tables as generated by the JoinVerification operator. The key for that cache is the test configuration. As more and more test configurations were added, that cache grew in size, leading to out-of-memory issues with TSAN.
Most of the configuration options, however, are not relevant for the JoinVerification operator. Its results will always be the same independent of, e.g, the chunk size. By leaving the options out of the cached key, we can reduce the size of the cache and fix the current CI issues.
As a welcomed side effect, the number of JoinVerification invocations is down from 2219 to 691, reducing the total runtime from 49975 ms to 41540 ms (debug on Mac).
=> Reduce cache size in JoinTestRunner

src/lib/operators/join_hash.cpp
When discussing and analyzing Hyrise's semi joins for TPC-H, @aloeser  stumpled upon the following explanation:
`* JoinMode::Semi/Anti*   The left relation becomes the build side, the right relation becomes the probe side`
Just below that, we determine to build the hash table on the right side when `const auto 
_mode == JoinMode::Left || _mode == JoinMode::AntiNullAsTrue || _mode == JoinMode::AntiNullAsFalse ||
_mode == JoinMode::Semi`
Since we want to iterate all the values of the left semi side and check them for existing partner, the left side should be the probe side.
This PR fixes the comment.
=> Fix explanation in hash join

src/lib/operators/operator_join_predicate.cpp, src/lib/operators/operator_join_predicate.hpp, src/test/operators/operator_join_predicate_test.cpp
When analyzing PQPs, the order of predicates might differ between LQP and PQP (e.g., LQP with `A.x = B.x` and a PQP with `B.x = A.x`). This PR adds a simple bool and method to later check if sides have been flipped.
=> Allow recognizing flipped JoinOperatorPredicates

src/lib/visualization/abstract_visualizer.hpp, src/lib/visualization/lqp_visualizer.cpp, src/lib/visualization/pqp_visualizer.cpp
This PR integrates the usage of thousands separators in the LQP and PQP visualizations for the row (and chunk) count.
LQP example
PQP example
=> Query plan visualization: use of thousands separators

src/lib/operators/join_index.cpp
With this PR, the `JoinIndex` supports Semi and Anti* joins where the left input table is indexed. Even if by definition the tuples of the left input table are outputted, using indexes of the left table's chunks can be beneficial when the number of tuples of the right table is very small.
Fixes #2119
=> JoinIndex: Support Semi and Anti* joins with IndexSide::Left

resources/test_data/sqlite_testrunner_queries.sql, src/lib/operators/table_scan.cpp, src/lib/sql/sql_translator.cpp, src/test/operators/table_scan_test.cpp, src/test/sql/sql_translator_test.cpp
* For BETWEEN expressions where one of the bounds is not a column, we correctly fall back to the ExpressionEvaluator. Before this PR, we still expected both to be PQPColumnExpressions in one place.
* When trying to `SUM(string_column)`, a non-descript exception was thrown later on. We now catch this in the SQLTranslator.
=> Fix two expression issues

src/lib/expression/value_expression.cpp
Turns out #2134 was a false alarm. The 'l' indicating a long value just looks awfully similar to a '1'. Let's use upper case suffixes instead.
fixes #2134
=> Change ValueExpression long suffix to upper case

src/lib/CMakeLists.txt, src/lib/optimizer/optimizer.cpp, src/lib/optimizer/strategy/stored_table_column_alignment_rule.cpp, src/lib/optimizer/strategy/stored_table_column_alignment_rule.hpp, src/test/CMakeLists.txt, src/test/optimizer/strategy/stored_table_column_alignment_rule_test.cpp
The PQP sub plan memoization for StoredTableNodes is sensitive to the node's table name, set of pruned chunks and set of pruned columns. Consequently, for multiple nodes with the same table name, same pruned chunks and same pruned columns, only one GetTable operator is created and executed. In some queries, the ColumnPruningRule and ChunkPruningRule provide an LQP with multiple StoredTableNodes where the table names and sets of pruned chunks are equal but the sets of pruned columns are different. This leads to the creation and execution of different GetTable operators instead of only one operator.
This rule identifies StoredTableNodes that differ only in the pruned columns. It then intersects the lists of pruned columns. While this means that some columns are left unpruned, it makes the …
=> StoredTableColumnAlignmentRule

scripts/test/hyriseBenchmarkFileBased_test.py, scripts/test/hyriseBenchmarkJoinOrder_test.py, scripts/test/hyriseBenchmarkTPCH_test.py, src/benchmarklib/cli_config_parser.cpp
When using 1 client, the benchmark states "1 simulated clients is scheduling items in parallel".
For one client, it's now "1 simulated client is scheduling items".
=> Clarify benchmark information text

src/lib/logical_query_plan/lqp_translator.cpp, src/test/lib/logical_query_plan/lqp_translator_test.cpp
The translation of predicates node to index scans checks if a GroupKey index exists and creates the corresponding included_chunk_ids and excluded_chunk_ids vectors to specify for which chunks the index scan can be used and for which chunks the table scan should be used as a fallback.    
During the creation of the include/exclude chunk id vector, information about pruned chunks are not considered at the moment. For that reason, the pull request adds an id mapping, which removes pruned chunks and adopts the chunk ids correspondingly.
=> Consider pruned chunk ids in LQPTranslator for index scans

scripts/lint.sh, src/lib/logical_query_plan/lqp_translator.cpp, src/test/lib/storage/any_segment_iterable_test.cpp, src/test/lib/storage/encoded_segment_test.cpp, src/test/lib/storage/encoded_string_segment_test.cpp, src/test/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_index_test.cpp
fixes #1321:
- removal of random value generation in tests
- extension of the lint script so that using random values in tests will be reported as errors (taken from @mrks)
- renaming (leading underscore for private/protected variables/functions)
- formatting
=> Removal of random values in tests

src/lib/storage/constraints/abstract_table_constraint.hpp
This might not be the best solution to resolve #2165, but at least it compiles.
=> Fix missing constructors for AbstractTableConstraint

src/lib/sql/sql_translator.cpp, src/lib/sql/sql_translator.hpp, src/test/lib/sql/sql_translator_test.cpp
Fixes #2162.
There are two things I don't really like, they are up for discussion:
- ~~Solving the subquery involving non-cacheable metatables problem by making `SQLTranslator's` `_cacheable` a public member~~
- ~~The way this is tested: adding an optional parameter to `SQLTranslatorTest's` `compile_query` method. We could also change the function's return type but then we would need to adapt almost all 147 SQLTranslatorTests.~~
=> Fix `show tables` and subqueries involving meta tables (#2162)

Dockerfile, install_dependencies.sh
Depending on the linux system used, lld might not be available. Since we are very explicit with `clang-9`, `clang-cov-9`, we should also use `lld-9`. With that, adding the llvm9 repositories is sufficient to get the install script running.
=> Explicitly install lld-9

.gitmodules
Our third party module `nlohmann_json` has recently deleted its test files and shrunk from ~260 MB to ~20 MB.
This PR uses the shallow submodule flag to only pull the most recent version (same as a clone with `--depth 1`).
```
$ git clone --single-branch --branch master --recursive https://github.com/hyrise/hyrise.git master_clone
$ git clone --single-branch --branch martin/shallow_nlohmann_submodule --recursive https://github.com/hyrise/hyrise.git shallow_branch_clone
$ du -h -d1
679M	./master_clone
408M	./shallow_branch_clone
```
=> Shallow clone for third party module nlohmann

src/lib/logical_query_plan/abstract_lqp_node.cpp, src/lib/logical_query_plan/functional_dependency.cpp, src/lib/logical_query_plan/functional_dependency.hpp, src/lib/logical_query_plan/join_node.cpp, src/lib/logical_query_plan/lqp_unique_constraint.cpp, src/lib/logical_query_plan/lqp_unique_constraint.hpp, src/lib/logical_query_plan/lqp_utils.cpp, src/lib/logical_query_plan/union_node.cpp, src/test/CMakeLists.txt, src/test/lib/logical_query_plan/functional_dependency_test.cpp, src/test/lib/logical_query_plan/join_node_test.cpp, src/test/lib/logical_query_plan/lqp_unique_constraint_test.cpp, src/test/lib/logical_query_plan/union_node_test.cpp
This PR adds an implementation and tests for functional dependencies in UnionNode with `SetOperationMode` set to `All`.
In the course of this, various FD-related utility functions have been added as well:
* inflate_fds
* deflate_fds
* intersect_fds
---
Furthermore, the hash functions of LQPUniqueConstraint & FunctionalDependency have been fixed, so that they are no longer dependent on the internal order of elements in its unordered sets. Additional tests that cover the hash-ordering issues have been added as well.
=> Implement FDs for UnionNode (SetOperationMode::All) & Fix hashing of FDs and LQPUniqueConstraints

src/lib/operators/table_scan.cpp, src/lib/operators/table_scan/column_between_table_scan_impl.cpp, src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp, src/lib/optimizer/strategy/subquery_to_join_rule.cpp, src/test/lib/operators/table_scan_test.cpp
If the dictionary lookup shows that all values in the chunk match, we still need to make sure not to return any NULL rows. With this PR, we use the NULLable flag to skip this check where possible.
Additionally, this adds a shortcut in the generation of the output chunks if the entire chunk matches: Instead of creating a new ReferenceSegment (and potentially rebuilding the mapping), we simply forward the input chunk. This part is easier to review with whitespace changes hidden.
**System**
<details>
| -- | -- |
| Memory | 1.2TB |
| numactl | nodebind: 1  |
| numactl | membind: 1  |
</details>
| commit | date | message | …
=> Table Scan: Improve all-rows-match shortcut

scripts/lint.sh
E203 is broken and it is recommended to ignored it (see https://github.com/psf/black/issues/280).
Currently, `black` correctly adds spaces around colons in some cases and `flake8` marks them as errors due to the broken E203.
This PR extends the ignore list by adding E203 (note, the default settings of `flake8` already ignore several warnings).
Resolves #2200.
=> Fix problems with flake8 linter and E203

scripts/test/compareBenchmarkScriptTest.py
Checking for edge case, when there has been not a single successful run (apparently happens in the CI).
There is no error when the throughput is calculated on an empty set of runs.
Resolves #2196.
=> Fix division by zero in compare benchmark test

scripts/compare_benchmarks.py, src/benchmarklib/abstract_table_generator.cpp
With this PR, the table generator fails if an imported cached binary table has a different chunk size than the one defined in the benchmark configuration.
Additionally, this PR introduces minor format changes in `compare_benchmarks.py`, performed by our format script.
=> Import cached binary tables: fail for inconsistent chunk sizes

scripts/test/compareBenchmarkScriptTest.py, src/bin/console/console.cpp
With this PR, metatables can be exported from the console.
Example: `export meta_system_utilization sys_util.csv`
Additionally, this PR introduces minor format changes in `compareBenchmarkScriptTest.py`, performed by our format script.
=> Export meta table support for the console

src/lib/operators/aggregate_hash.cpp
The time in _aggregate was measured twice. Fixes #2203.
=> AggregateHash: Fix performance timer

src/lib/import_export/csv/csv_parser.cpp, src/test/lib/import_export/csv/csv_parser_test.cpp
With this PR, all chunks of a table created by `CsvParser::parse` are finalized and thus immutable.
=> CsvParser: Finalize chunks of parsed table

src/lib/operators/join_hash.cpp, src/lib/operators/join_hash/join_hash_steps.hpp
If a hash join's input is heavily pre-filtered or the join results in very few matches, we might end up with a high number of chunks that contain only few rows. This involves a trade-off: A lower number of output chunks reduces the overhead, especially when multi-threading is used. However, merging chunks destroys a potential references_single_chunk property of the PosList that would have been emitted otherwise.
@mweisgut - Did we already talk about the impact of chunk sizes on the efficiency of multi-threading? This popped up when I was looking at MT for my thesis, so I wrote a quick fix for it. `500` is a number that seems to work well for TPC-H, but that is just an educated guess. I suspect that there is more to the chunk+MT discussion than just this.
---------------
**System** …
=> Hash Join: Merge output chunks <500 rows

resources/test_data/tbl/meta_tables/meta_segments_accurate_libcpp_updated.tbl, resources/test_data/tbl/meta_tables/meta_segments_accurate_libstdcpp_updated.tbl, resources/test_data/tbl/meta_tables/meta_segments_libcpp_updated.tbl, resources/test_data/tbl/meta_tables/meta_segments_libstdcpp_updated.tbl, src/lib/optimizer/strategy/chunk_pruning_rule.cpp, src/test/lib/optimizer/strategy/chunk_pruning_rule_test.cpp
Currently, if a PredicateNode has multiple outputs, it is not considered for chunk pruning. You can see the effects in TPC-H Q4, where the predicate on the orders table is not used because the between predicate has multiple outputs at the time where the rule is run.
While we must not use predicates that are on a branch of the query, using the one on the fork is fine.
No impact on TPC-H, as the affected cases profit from being able to use a binary search and the scan is quite cheap anyway. Might still be interesting for @aloeser (and @krichly?).
=> Fix pruning of PredicateNodes with multiple outputs

src/lib/operators/join_hash/join_hash_steps.hpp
There is a check in the hash join that we only need to do once. This moves it out of the loop.
Benchmarks are running. It appears that we are triggering another binary alignment change (Q6 is not supposed to change), so I am not sure how conclusive they are. In any case, I believe that the code change is sensible.
=> JoinHash: Move branch out of loop

src/lib/operators/aggregate_hash.cpp, src/lib/operators/join_hash.cpp, src/lib/operators/projection.cpp, src/lib/operators/projection.hpp
Adds the following steps to the projection operator: `UncorrelatedSubqueries, ForwardUnmodifiedColumns, EvaluateNewColumns, BuildOutput`.
This helps us in understanding the performance of queries.
Also changes some casts to dynamic_casts that fail if the data structure was not properly initialized.
=> Add OperatorSteps to Projection

scripts/run_benchmarks_over_commit_range.sh
* Use ninja where ninja is used, fixes #2216 
* Check that the SHA-1 hash is part of the json
* Fix output if incomplete hash or other commit reference (e.g., HEAD^) is used
=> run_benchmarks_over_commit_range.sh: Some Fixes

resources/test_data/tbl/aggregateoperator/groupby_int_1gb_0agg/result_any_null.tbl, resources/test_data/tbl/aggregateoperator/groupby_int_1gb_1agg/any_filtered.tbl, src/lib/expression/evaluation/expression_evaluator.cpp, src/lib/operators/abstract_aggregate_operator.hpp, src/lib/operators/aggregate_hash.cpp, src/lib/operators/aggregate_hash.hpp, src/lib/operators/aggregate_sort.cpp, src/lib/optimizer/optimizer.cpp, src/test/lib/operators/aggregate_test.cpp
Currently we treat ANY as a regular aggregate function, which means that we look at each value individually. By writing it as if it was a group-by column (but not using it for grouping), we gain quite a bit:
```diff
+Configuration Overview----+------------------------------------------------+------------------------------------------------+
| Parameter                | /home/Markus.Dreseler/master_node1.json        | agg.json                                       |
+--------------------------+------------------------------------------------+------------------------------------------------+
|  GIT-HASH                | ae811a4f022d58a54c40c8b49eeb2146fb01e9db-dirty | e228c01d829714a3027a484a903c8bbba7550023-dirty |
|  benchmark_mode          | Ordered …
```
=> Aggregate: Write ANY as part of grouping, not as pseudo aggregate function

scripts/compare_benchmarks.py
Makes the "Configuration Overview" section collapsable when using the `--github` flag.
**Example Output**:
<details>
<summary>Configuration Overview - click to expand</summary>
```diff
+Configuration Overview---------------------------------------------+------------------------------------------------+
| Parameter        | results_master.json                            | results_constraints.json                       |
+------------------+------------------------------------------------+------------------------------------------------+
|  GIT-HASH        | 2905a7817d9d8d62581160431c07ff657e537441-dirty | c0e706da1384d8c0bfd54f8e5590c63b1956bc61-dirty |
|  benchmark_mode  | Ordered                                        | Ordered                                        |
|  build_type …
```
=> Improve --github output of compare_benchmarks.py 

src/lib/import_export/binary/binary_writer.cpp, src/lib/storage/lz4_segment.cpp, src/lib/storage/lz4_segment.hpp, src/test/lib/storage/lz4_segment_test.cpp
For empty string columns (not the case for TPC-H, but for TPC-DS), LZ4 does not store the string vector offsets as every query is of length 0.
When requesting the vector compression type, a check was missing and Hyrise crashed when the vector compression type was requested for an empty string column.
I thought about testing it, but empty string columns are tested and would be needed is now testing the return value of the compressed vector type. I am not sure if that test makes sense.
In case anybody likes to see a test, I'll add one.
=> Fix segfault when requesting vector compression of LZ4 segment of an empty string column

src/lib/statistics/abstract_cardinality_estimator.hpp, src/lib/statistics/cardinality_estimation_cache.hpp, src/lib/statistics/cardinality_estimator.cpp, src/lib/statistics/cardinality_estimator.hpp, src/lib/statistics/join_graph_statistics_cache.cpp, src/lib/statistics/join_graph_statistics_cache.hpp
`AbstractCardinalityEstimator::estimate_cardinality()` requires `const std::shared_ptr<AbstractLQPNode>& lqp` as an argument. As there is no obvious reason to make changes to an LQP while estimating the cardinality of its output, this PR changes the signature to require a shared pointer to a `const` LQP node and adapts the underlying data structures.
This change seems not to have a stable effect on performance (TPC-H, sf 0.01, 60s/query).
```diff
+--------------------------+------------------------------------------------+------------------------------------------------+
|  GIT-HASH                | 2905a7817d9d8d62581160431c07ff657e537441-dirty | da616f0adc9d72689dfd3be7b30526ab666d8e27-dirty |
|  benchmark_mode          | Ordered                                        | Ordered …
```
=> Prohibit LQP Modification for Cardinality Estimation

Jenkinsfile, src/benchmark/tpcds_benchmark.cpp, src/benchmarklib/tpcds/tpcds_table_generator.cpp, src/benchmarklib/tpcds/tpcds_table_generator.hpp, src/bin/console/console.cpp, src/lib/storage/segment_iterate.hpp, src/test/benchmarklib/tpcds/tpcds_db_generator_test.cpp
Adds all PRIMARY KEY key constraints from the TPC-DS spec, so that we can profit from unique constraints and FDs in our query plans.
**TPC-DS, SF=1**
<details>
<summary>Configuration Overview - click to expand</summary>
```diff
+Configuration Overview---------------------------------------------+------------------------------------------------+
| Parameter        | results_master.json                            | results_constraints.json                       |
+------------------+------------------------------------------------+------------------------------------------------+
|  GIT-HASH        | 2905a7817d9d8d62581160431c07ff657e537441-dirty | c0e706da1384d8c0bfd54f8e5590c63b1956bc61-dirty |
|  benchmark_mode  | Ordered                                        | Ordered …
```
=> Add key constraints for the TPC-DS benchmark

src/lib/operators/sort.cpp, src/lib/operators/sort.hpp
I was wondering if incorporating the limit operator into the sort operator could reduce the time spent writing the result. At least in TPC-H Q2, the only one where Sort has a significant cost, it does not.
Still, the performance counters should not go to waste.
=> Sort: Add performance steps

src/lib/optimizer/strategy/column_pruning_rule.cpp, src/test/lib/optimizer/strategy/column_pruning_rule_test.cpp
The ColumnPruningRule prunes columns from StoredTableNodes which are not relevant to other LQP nodes. Therefore, it has to check each LQP node for required expressions. 
In terms of AggregateNodes, the rule considers group-by expressions and the arguments of aggregate functions as required. Ungrouped `COUNT(*)` aggregations, however, are an edge case because we cannot derive any required expressions. Until now, the rule considered all input expressions as required whenever there was a `COUNT(*)` aggregate function. In consequence, column pruning became effectively disabled for some queries.
This PR enables column pruning for AggregateNodes with `COUNT(*)` aggregates. 
Some TPC-DS queries heavily profit from this change due to the semi join reformulations that were not possible before. …
=> Improve ColumnPruningRule for COUNT(*) aggregates

scripts/benchmark_all.sh, src/lib/operators/join_hash/join_hash_steps.hpp
For some reason, `~BloomFilter(BLOOM_FILTER_SIZE);` is quite expensive, resulting in a `> 1 ms` startup time for a join. For as long as we do not have dynamic bloom filter sizes, this is a hotfix:
**System**
<details>
| -- | -- |
| Memory | 1.2TB |
| numactl | nodebind: 0  |
| numactl | membind: 0  |
</details>
| 88b690fc4 | 07.10.2020 07:35 | benchmark_all: Include TPC-H SF 10 | real 265.11 user 2399.13 sys 132.74|
| 792e6f29a | 07.10.2020 07:35 | Reuse empty bloom filter | real 266.38 user 2385.16 sys 135.59|
**hyriseBenchmarkTPCH - single-threaded** …
=> Create empty bloom filter only once

src/lib/optimizer/optimizer.cpp, src/lib/optimizer/strategy/predicate_split_up_rule.cpp, src/test/lib/optimizer/strategy/predicate_split_up_rule_test.cpp
Optimization: The ExpressionReductionRule transforms `x NOT LIKE 'foo%'` into `x < 'foo' OR x >= 'fop'`. For this special case, we know that the two OR arguments are mutually exclusive. In this case, we do not need to use SetOperationMode::Positions but can use SetOperationMode::All. This surely applies to other cases, too, but those are not covered yet.
This only applies to TPC-H Q16; other benchmarks do not use this construct.
**System**
<details>
| -- | -- |
| Memory | 1.3TB |
| numactl | nodebind: 2  |
| numactl | membind: 2  |
</details>
| 71a783492 | …
=> PredicateSplitUpRule: Create UnionAll for NOT LIKE

src/lib/operators/validate.cpp
We already have a shortcut for data tables and single-chunk reference segments. For reference segments without the guarantee, we currently perform a validation of each row. By checking which chunks are entirely visible, we can skip this validation for some rows.
**System**
<details>
| -- | -- |
| Memory | 1.2TB |
| numactl | nodebind: 3  |
| numactl | membind: 3  |
</details>
| 71a783492 | 07.10.2020 08:44 | Sort: Add performance steps (#2234) | real 266.09 user 2382.89 sys 141.05|
| 5fe1cbcde | 07.10.2020 23:56 | Validate: Add shortcut for entirely visible …
=> Validate: Add shortcut for entirely visible even without chunk guarantee

src/lib/optimizer/optimizer.cpp, src/lib/optimizer/strategy/column_pruning_rule.cpp, src/test/lib/optimizer/strategy/column_pruning_rule_test.cpp
#2238 introduced a performance regression in TPC-DS:
```diff
-| 10      ||     19.7 |    6060.5 |   +30674%  ||    50.77 |     0.17 | -100%  |  0.0000 |
-| 35      ||     89.2 | 1303100.2 | +1461565%  ||    11.22 |     0.00 | -100%  |       ˅ |
-| 45      ||      9.8 |      17.4 |      +77%  ||   101.89 |    57.59 |  -43%  |  0.0000 |
```
This went unnoticed because <s>I</s> someone did not have sufficient compute resources and only ran the TPC-H benchmark. What happened was that some disjunctions were made unavailable for the SubqueryToJoinRule.
With this PR, that someone reverts the old order in the optimizer and instead fixes the ColumnPruningRule to be able to deal with certain types of UnionAll.
<details>
<summary>Here is the complete benchmark_all result for #2238</summary> …
=> Fix Performance Regression caused by split-or

src/lib/operators/join_hash.cpp
For the bloom filter to be efficient, it makes sense for the smaller side to be materialized first. That way, the bloom filter created on that side can serve as a filter when materializing the bigger side.
In cases where the build side is bigger than the probe side (unavoidable for some semi/anti joins), this PR flips the order of the two materialization steps.
The overall performance is not tooo impressive, as only few queries are affected. A 49% improvement for TPC-H Q22 is nice to have though.
**System**
<details>
| -- | -- |
| Memory | 1.2TB |
| numactl | nodebind: 0  |
| numactl | membind: 0  |
</details>
| commit | …
=> JoinHash: Materialize smaller side first

.gitmodules, DEPENDENCIES.md, scripts/compare_benchmarks.py, src/CMakeLists.txt, src/benchmarklib/abstract_table_generator.cpp, src/lib/CMakeLists.txt, src/lib/statistics/statistics_objects/equal_distinct_count_histogram.cpp, src/lib/statistics/table_statistics.cpp, third_party/CMakeLists.txt
* For the generation of the table histograms, use the robin_map. It allows us to cache the hash of strings, which makes generation much faster. We will likely replace the current bytell hash map with this one for other things, too.
* Parallelize some steps of the benchmark start. Hide whitespaces when reviewing this.
Old:
- Sorting tables done (5 s 957 ms)
- Encoding tables and generating pruning statistic done (10 s 692 ms)
- Adding tables to StorageManager and generating table statistics done (2 min 41 s)
- Total time from binary start to first query: 3 min 21 s
New:
- Sorting tables done (5 s 238 ms)
- Encoding tables and generating pruning statistic done (8 s 778 ms)
- Adding tables to StorageManager and generating table statistics done (1 min 23 s)
- Total time from binary start to …
=> Make hyriseBenchmarkX loading faster

src/lib/operators/projection.cpp, src/lib/storage/chunk.cpp, src/lib/storage/segment_iterables.hpp, src/test/lib/operators/projection_test.cpp
Up to now, whenever a Projection `SELECT a, a+1 FROM t` emitted a newly generate column (here: `a+1`), it also materialized all columns that it forwarded (here: `a`). The reason for that is that we do not allow ValueSegments and ReferenceSegments to be mixed within one table.
With this PR, we instead forward the ReferenceSegments and create new ReferenceSegments for the newly generated columns. These point to a new, temporary table. Because we use the EntireChunkPosList, this virtually causes no overhead.
Also does a minor improvement to `segment_iterate` which causes a segment that is iterated on using an EntireChunkPosLists to use the sequential iterator, not the random access one.
```
+-----+     +------+  Case 1
|a |b |     |a |a+1|   * Input TableType::Data
|DS|DS| --> |DS|VS |   * A …
```
=> Projection: Stop materializing forwarded columns

src/bin/CMakeLists.txt, src/bin/server.cpp, src/lib/CMakeLists.txt, src/lib/operators/aggregate_hash.cpp, src/lib/operators/index_scan.cpp, src/lib/operators/index_scan.hpp, src/lib/operators/join_hash/join_hash_steps.hpp, src/lib/operators/join_sort_merge.cpp, src/lib/operators/join_sort_merge/column_materializer.hpp, src/lib/operators/join_sort_merge/radix_cluster_sort.hpp, src/lib/operators/table_scan.cpp, src/lib/operators/validate.cpp, src/lib/scheduler/abstract_scheduler.cpp, src/lib/scheduler/abstract_scheduler.hpp, src/lib/scheduler/abstract_task.cpp, src/lib/scheduler/abstract_task.hpp, src/lib/scheduler/node_queue_scheduler.cpp, src/lib/scheduler/node_queue_scheduler.hpp, src/lib/scheduler/operator_task.cpp, src/lib/scheduler/operator_task.hpp, src/lib/scheduler/topology.hpp, src/lib/scheduler/worker.cpp, src/lib/scheduler/worker.hpp, src/lib/server/query_handler.cpp, src/test/lib/operators/operator_deep_copy_test.cpp, src/test/lib/scheduler/operator_task_test.cpp, src/test/lib/scheduler/scheduler_test.cpp, src/test/lib/tasks/chunk_compression_task_test.cpp
Some optimizations for scheduling:
* We have previously seen how a high number of tasks can impact the scheduling performance (#2202). By grouping these tasks and allowing a maximum task fan-out of 10, we can further reduce the impact of this. While this means that we limit the degree of concurrency and might not use all cores in a single-node environment, it improves the overall performance. Some day in the future we might have a resource monitor that automatically adjusts the fan-out depending on the system load.
* This only works when all tasks are scheduled at the same time. Make all operators use `schedule_and_wait_for_tasks` to enable this.
* When a task is done, we currently add the successor task(s) to the high priority queue. This means that they are worked on before an entirely …
=> Scheduler: Improve handling of JobTasks with high fan-out and of successor tasks

src/lib/expression/abstract_expression.hpp, src/lib/optimizer/strategy/predicate_split_up_rule.cpp
I was not able to build with Clang 9 and disabled precompiled headers.
Error was:
```
In file included from ../src/lib/logical_query_plan/abstract_lqp_node.hpp:8:
../src/lib/expression/abstract_expression.hpp:50:11: error: definition of implicit copy constructor for 'AbstractExpression' is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated]
virtual ~AbstractExpression() = default;
```
Not sure what I am doing here, but it fixed the issue. Not sure why this was not caught by our CI.
=> Make AbstractExpression Noncopyable

src/benchmark/operators/join_aggregate_benchmark.cpp
One micro benchmark has been defunct. I don't want to remove this benchmark, because I am working on a related topic that might make sorted aggregations an actual option.
=> Fix sorted aggregation micro benchmarks

src/lib/operators/aggregate_hash.cpp, src/lib/operators/aggregate_hash.hpp, src/lib/operators/operator_performance_data.hpp, src/test/lib/operators/operator_performance_data_test.cpp
Resolves #2266.
`_write_groupby_output` can be called at two places. In one of the (`write_aggregate_output()`), its self-recorded step runtime is included in the runtime of the AggregateColumnWriting step, leading to cumulative step runtimes that are larger than the actual operator runtime.
=> Fix operator performance counters in hash aggregate

src/lib/operators/sort.cpp, src/lib/operators/sort.hpp
With this PR, we split up the "Sort" step into different phases:
=> Sort: Make performance steps more precise

src/lib/utils/meta_table_manager.cpp, src/lib/utils/meta_table_manager.hpp, src/test/lib/operators/change_meta_table_test.cpp, src/test/lib/utils/meta_table_manager_test.cpp, src/test/lib/utils/meta_tables/meta_table_test.cpp
I am currently working on a plugin and found the meta tables to be an excellent way of storing information.
This PR simply makes the add table method public, so that a plugin can add meta tables to Hyise.
A sample use case (also what I am currently working on) is a plugin that extracts all operators from the query plan cache and makes it queryable. The Hyrise cockpit can then simply do a `SELECT * FROM meta_cool_new_list_of_operator_instances`.
=> Make MetaTableManager::_add() public

scripts/test/compareBenchmarkScriptTest.py, src/lib/operators/table_scan.cpp, src/lib/operators/table_scan.hpp, src/lib/operators/table_scan/abstract_table_scan_impl.hpp, src/lib/operators/table_scan/column_between_table_scan_impl.cpp, src/lib/operators/table_scan/column_is_null_table_scan_impl.cpp, src/lib/operators/table_scan/column_like_table_scan_impl.cpp, src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp, src/test/lib/operators/operator_performance_data_test.cpp
I was wondering, why table scans did not show any skipping (e.g., due to value not existing in the dictionary) for scans that should skip (at least that was what I thought).
Turns out, this information is only shown when there have been at least one chunk that was skipped or scanned binary.
This PR now fixes that (i) there has not been a tooltip before when no chunks were skipped and (ii) the skip information is always shown now.
Before Q19 (no information for non-skipped):
Now:
Further changed the table scan operator as well as the tests to use `dynamic_cast` over `static_cast` to ensure that wrong casts are catched. It's not in a hot loop, so that should not matter.
One potentially open question is how to handle table scan's splitting of reference table into their actual physical …
=> Improve PQP tooltip of table scan

src/lib/expression/evaluation/like_matcher.cpp, src/lib/expression/evaluation/like_matcher.hpp, src/lib/optimizer/strategy/expression_reduction_rule.cpp, src/lib/statistics/statistics_objects/min_max_filter.cpp, src/test/lib/expression/evaluation/like_matcher_test.cpp, src/test/lib/statistics/statistics_objects/min_max_filter_test.cpp
This PR adds the `LIKE` and `NOT LIKE` predicate to the `min_max_filter`. 
The `does_not_contain` method works now as follows, if the predicate is `LIKE` or `NOT LIKE`: 
* Check if a wild card exists
* Calculate the upper and lower bound of the value. For example, if the value is `Japan%` the lower bound will be `Japan` and the upper will be `Japao`.
* Check if the lower bound is bigger than the max value or the upper bound smaller than the min value. If either of the cases occurs, we can say that the value is not included.
The following table shows the pruning effectiveness (JOB with one run and unsorted): 
<details><summary>show table</summary>
<p>
`pruning failed` = (max < lower_bound || upper_bound <= min) failed  
`bounds not valid` = pattern has a leading wildcard, or upper_bound …
=> Add Like predicate to min max filter

src/lib/operators/table_scan.cpp, src/lib/operators/table_scan.hpp, src/lib/operators/table_scan/abstract_table_scan_impl.hpp, src/lib/operators/table_scan/column_between_table_scan_impl.cpp, src/lib/operators/table_scan/column_between_table_scan_impl.hpp, src/lib/operators/table_scan/column_vs_value_table_scan_impl.cpp, src/lib/operators/table_scan/sorted_segment_search.hpp, src/test/lib/operators/operator_performance_data_test.cpp
While working with @dey4ss on our research seminar topic (what-if clustering cost models), we noticed that the table scan currently tracks only the number of chunks for which the scan was skipped because no row matches. However, this number is often 0 because those chunks get pruned before the scan is executed.
This PR adds an additional counter to track the number of chunks for which the scan was skipped because all rows match. This does happen, e.g., for `BETWEEN` scans on `l_shipdate`.
Those two metrics are not identical because for the latter we still need to write the output.
EDIT: As @Bensk1 pointed out, this PR changes the way sorted scans are tracked: If sorted BETWEEN scans use an early exit (no match) or an all-match-shortcut, the scan now increases the respective no/all-match …
=> TableScan: track number of chunks where all rows match

src/lib/CMakeLists.txt, src/lib/optimizer/optimizer.cpp, src/lib/optimizer/strategy/null_scan_removal_rule.cpp, src/lib/optimizer/strategy/null_scan_removal_rule.hpp, src/test/CMakeLists.txt, src/test/lib/optimizer/strategy/null_scan_removal_rule_test.cpp
This PR adds the `null scan removal rule` to the optimizer's strategies. The goal of this rule is to not do null scans on columns if we know that they are not nullable. 
The rule checks if a node meets all the required conditions to be removed from the LQP DAG: 
1. The node must be of type Predicate
2. The predicate must be a `null expression`
3. The predicate condition must be `is not null`
4. The predicate operand needs to be an `LQP Column expression`
5. The original node of the `LQP Column expression` needs to be a not defective `storage table node`
6. The column (referenced by the `LQP Column expression`) is not nullable
=> Add null scan removal rule

src/lib/operators/aggregate_hash.cpp, src/lib/operators/aggregate_hash.hpp
This is the first step of the AggregateHash optimizations. Currently, we perform a hash lookup for every row *and* every aggregate function. With this PR, we cache the result of that lookup so that we only need to look up every row once.
In a follow-up PR, we can use the same hack (masked AggregateKeyEntry) to forgo the hashmap lookup entirely in the case of more-or-less contiguous GROUP BY values (e.g., TPC-H Q 18).
----------------------------------------
**System**
<details>
| -- | -- |
| Memory | 1.5TB |
| numactl | nodebind: 2  |
| numactl | membind: 2  |
</details>
| -- | -- …
=> AggregateHash: Cache result ids

src/benchmarklib/abstract_table_generator.cpp
Fixes #2297 
In the AbstractTableGenerator, there is a case where sortedness information may be set on mutable chunks (for details see #2297), which causes Hyrise to crash.
This PR fixes the crash by finalizing chunks before the benchmark tables are sorted
=> Finalize chunks in AbstractTableGenerator before setting sortedness information

src/lib/operators/join_hash.hpp, src/lib/operators/join_hash/join_hash_steps.hpp, src/lib/operators/table_scan.cpp
This PR adds a threshold for the parallel execution of jobs in the `build` and `probe` step of the `join hash`.
It is implemented in the following way: 
* A static `JOB_SPAWN_THRESHOLD` attribute is added to the `JoinHash`class
* The jobs that perform the actual *materialize*, *partition by redix*, *build* and *probe* are executed directly if the number of elements of the partitions lies under the `JOB_SPAWN_THRESHOLD`
Like in #2269 the threshold still needs to be re-evaluated over time to find the value which gives the best performance. For now, a threshold of 500 is selected.
=> Add threshold for parallel execution in table scan and join hash

scripts/compare_benchmarks.py, scripts/test/compareBenchmarkScriptTest.py, src/benchmarklib/benchmark_runner.cpp
This PR fixes #2226
It solves the problem the following way:
* The `benchmark_runner` now reports the latency as the arithmetic mean of iterations.
* The output latency in the benchmark_runner is now in `ms` like in the `compare_benchmarks.py`
* The order of latency and throughput are now harmonized between the live-reporting of benchmarks and the `compare_benchmarks.py` script.
Example output TPC-H 01: 
Single-Threaded:
```
- Benchmarking TPC-H 01
-> Executed 41 times in 60.0047 seconds (Latency: 1463.1 ms/iter, Throughput: 0.68328 iter/s)
```
Multi-Threaded:
```
- Benchmarking TPC-H 01
-> Executed 1189 times in 60.0058 seconds (Latency: 2446.3 ms/iter, Throughput: 19.8148 iter/s)
```
`compare_benchmarks.py` :
```
+----------++----------+---------+---------++----------+----------+-------- …
```
=> Fix live reporting of latency

CMakeLists.txt
Turns out that the CPU architecture of a Raspberry Pi 4 is not `arm64` but rather `aarch64`. We now check for both to use `-mcpu=native` over `-march=native` for Clang on ARM.
=> Build on Raspberry Pi 4

src/lib/storage/segment_accessor.hpp
Fixes builds on MacOS with Clang11. The destructors in the segment accessors have not been marked as `override`, which is required even when the base destructor is marked as virtual.
C++ core discussion: https://github.com/isocpp/CppCoreGuidelines/issues/721 & https://github.com/isocpp/CppCoreGuidelines/pull/1448
I don't know why clang on Linux does not complain.
PS: I first upgraded several components on my laptop (Big Sur) and got various `boost` issues. Might be required to upgrade all Hyrise-related components together. But I haven't looked at it any further.
=> Override destructor in segment accessors (clang11)

Jenkinsfile
Github changed from HTTP/1.1 to HTTP/2 so the header check failed. Fixing that and also adding a quick hack that allows the Jenkins admin to run PRs of non-members.
=> Fix Jenkins, allow admin override

CMakeLists.txt
This should enable `-march=native` for exactly those architecture/compiler combinations that support it:
https://github.com/hyrise/hyrise/pull/2306#issuecomment-767388729
=> Fix -march=native once and for all (?)

scripts/test/compareBenchmarkScriptTest.py, src/lib/operators/abstract_operator.cpp, src/lib/operators/join_hash.cpp, src/lib/operators/join_hash.hpp, src/test/lib/operators/join_hash_test.cpp
Track the build side of the hash join by setting a flag in the operator performance struct. This information is important for join runtime estimations. @dey4ss, @aloeser, and me currently solve it by copying the if statement of the join, which is not an ideal solution.
Moreover, it's convenient to have this information in the PQP visualization.
=> Hash join: track which input table is build side

scripts/test/hyriseBenchmarkCore.py, scripts/test/hyriseBenchmarkFileBased_test.py, scripts/test/hyriseBenchmarkJoinOrder_test.py, src/lib/operators/join_hash/join_hash_steps.hpp, src/lib/operators/table_scan/column_like_table_scan_impl.cpp, src/lib/optimizer/strategy/semi_join_reduction_rule.cpp, src/plugins/mvcc_delete_plugin.cpp, src/test/lib/concurrency/stress_test.cpp, src/test/lib/server/server_test_runner.cpp
For the join order benchmark, binary tables are written into the table_path. In CI, this path is shared by different targets that are potentially executed concurrently. This sometimes led to issues with corrupted binary files.
I am also sneaking in some things that are too minor to have their own PR.
=> Disable binary caches for CI

src/lib/operators/aggregate_hash.cpp, src/lib/operators/join_hash.cpp, src/lib/operators/join_index.cpp, src/lib/operators/operator_performance_data.hpp, src/lib/scheduler/abstract_task.cpp, src/lib/scheduler/abstract_task.hpp, src/lib/scheduler/worker.cpp, src/lib/scheduler/worker.hpp
(This PR replaces #2311. Something is amiss with Jenkins in a way that we have not seen before. Assuming that this is a freak accident, I simply reopened the PR. If this reoccurs, we have to look into it.)
Currently, `Worker::wait_for_tasks` checks if all tasks are completed. If they are not, the worker pulls tasks from the queue and executes them until all tasks that we wait on are done. This, however, leads to a problem if one of the pulled tasks calls `wait_for_tasks` itself. Over time, the worker builds a stack of `wait_for_tasks` calls and the first task has to wait until all tasks that the worker started because it was bored are completed.
**System**
<details>
| -- | -- |
| CPU | Intel(R) Xeon(R) …
=> wait_for_tasks: Execute own tasks first

src/test/lib/storage/encoded_segment_test.cpp
Thanks to @benrobby for pointing at it. Currently, we unintentionally create a vector of zeros.
=> Fix all values zero in SegmentEncodingTests

scripts/benchmark_all.sh
Currently, not all TPC-H runs execute properly as the binary cached data is sorted in a clustered run (using `--clustering=Pruning`) which fails in the next non-clustered run.
This PR changes the clustered run to use `--dont_cache_binary_tables`. We could move the run to the very end, but that would probably crash with the next `benchmark_all.sh` run.
=> Fix benchmark_all.sh script

scripts/benchmark_all.sh, src/lib/operators/union_positions.cpp
@aloeser and @dey4ss found that the union positions operator takes a surprising large share of the overall runtime of the DS benchmark. For TPC-H or JOB, the union positions operators mostly does not matter (TPC-H is microseconds, JOB is more for two queries, but both are too fast to make an impact).
This PR simply changes `std::sort` to boost's `pdqsort` (see #2271 for a related discussion on sorting).
The results look good so far. The main reason fo the slow runtimes is Q28 and this query improve significantly. The noise is reproducible. I can't really tell where it comes from. The union positions operator is not used in many queries, which change quite a lot.
**System**
<details>
| -- | -- |
| CPU | …
=> Use boost's pdqsort in union positions operators

scripts/test/hyriseServer_test.py
Currently, the server starts with the default port which might crash if there is a parallel server running in the CI.
This PR starts with the server port 0 to let the OS assign a port, parses the output to obtain the port, and connects the client to this port.
Resolves #2320
=> Fix CI problems with the hyrise server test

Jenkinsfile, scripts/plot_operator_breakdown.py, scripts/test/hyriseBenchmarkTPCC_test.py, src/benchmarklib/abstract_table_generator.cpp, src/benchmarklib/abstract_table_generator.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/tpcc/tpcc_table_generator.cpp, src/benchmarklib/tpcds/tpcds_table_generator.cpp, src/benchmarklib/tpch/tpch_table_generator.cpp
Enable binary exports/imports for TPC-C, which was the only benchmark left that did not support binary export and imports.
The data creation for TPC-H does not scale linearly and larger tests with 10 warehouses, take a good amount of time.
| Warehouse count | Time to generate data (s) |
| --:            | --: |
| 1 |   6 |
| 2 |  19 |
| 3 |  36 |
| 5 |  86 |
| 10 | 312 |
=> Enable binary exports/imports for TPC-C

src/lib/CMakeLists.txt
Currently, we cannot build Hyrise's example plugin on Linux. In general, we build jemalloc first and then link and include the generated files.
Now, if we have import hyrise from the path `hyrise`, we do no longer find the jemalloc includes under `third_party/jemalloc/include` but rather `hyrise/third_party/jemalloc/include`.
This PR solves this issue by using `CMAKE_CURRENT_BINARY_DIR` to obtain the path `cmake-build-debug/hyrise/third_party` from which we can simply go upwards. `CMAKE_BINARY_DIR` does not tell us that Hyrise lives within the `hyrise` folder.
I have not found a nicer way to obtain the information, that we need to add `hyrise` to the include path.
This error does not occur on MaOS as we do not use jemalloc on MacOS.
=> Fix jemalloc includes for Plugin builds on Linux

src/test/lib/operators/join_test_runner.cpp
An old bug was recently exposed by an added assertion. The `print_configuration_info` lambda accessed `join_verification`, which might not be executed if the operator's result has been cached before.
=> Fix JoinTestRunner

src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/benchmark_runner.hpp
I am currently running multi-hour benchmarks. Waiting until the end to realize that something is wrong sucks. With this PR, `BenchmarkRunner::write_report_to_file` can be
* called more than once, with the resulting file simply being overwritten, and
* called from the outside so that my plugin can generate a report when something has been done.
This PR does not change the default behavior of the BenchmarkRunner. I decided against generating a report after each executed item in the `Ordered` mode as this may incur significant costs with `--metrics`. If you want to profit from this change, you thus need to call `Hyrise::get().benchmark_runner.lock()->write_report_to_file()` yourself.
=> BenchmarkRunner: Write report idempotently

scripts/plot_operator_breakdown.py, scripts/test/compareBenchmarkScriptTest.py, src/lib/CMakeLists.txt, src/lib/operators/join_hash.cpp, src/lib/operators/join_hash.hpp, src/lib/operators/join_hash/join_hash_steps.hpp, src/test/lib/operators/operator_performance_data_test.cpp
This PR adds three integers to the hash join's performance operator struct. They keep track of the "success" of the bloom filtering:
* size of materialized probe side (might or might not be filtered by a bloom filter, see added test)
* size of hash table
* size of positions stored for hash table (can be empty for certain joins)
The reason to add these counters is to enable better join runtime predictions (might be of interest for @dey4ss, @aloeser, and @Bensk1; even though it does not interact with clustering decisions). For certain joins, the bloom filters remove 90% of the data, almost removing the runtime of the probe phase from join.
I thought about adding these values to the visualization as well. But for now I have not, because:
- a sole number is cumbersome, to calculate percentage …
=> Hash join: keep track of skipped values from Bloom filtering

src/lib/operators/join_hash.cpp, src/lib/operators/join_hash.hpp
Without moving the definition, the linker throws several errors for release builds under g++ >= 10.2. Apparently, for older compilers these problems do not occur, but I don't even know why that was working before.
=> Move definition of JoinHash::calculate_radix_bits() to .hpp

Jenkinsfile
I noticed that our PRs suddenly fail early before anything is being actually built. Apparently, the login to docker is [failing](https://hyrise-ci.epic-hpi.de/blue/rest/organizations/jenkins/pipelines/hyrise/pipelines/hyrise/branches/PR-2374/runs/13/log/?start=0). I don't know the exact reason, they might have deactivated this endpoint. Apparently, by not specifying a registry, the default (and working) registry is used.
=> Fix docker pull in Jenkins

scripts/lint.sh
I was just using this as a base for something else and realized that our custom lint scripts expect at least two cpp files. Adding `-H` makes grep print the file name even if there is just a single file.
=> lint.sh: Work even if only a single file is present

src/lib/visualization/lqp_visualizer.cpp
Building Hyrise with GCC 10 fails as `isnan` is not defined. It's either std::isnan of `<cmath>` or it's `isnan`, if we include `<math.h>` (which we do not want).
I do not know why this hasn't been catched before.
=> Fix: isnan is undefined

third_party/CMakeLists.txt
Used version of Google benchmark does not build with GCC 11 (see here: https://github.com/google/benchmark/commit/3d1c2677686718d906f28c1d4da001c42666e6d2).
This PR simply updates google bench to the last master commit.
=> Update Google Benchmark

Jenkinsfile, README.md
Now that we quite frequently work with, and optimize for the JOB, fast access to its query plans would be useful. Also, the setup procedure is much faster now (smaller data set and faster download due to different hosting). 
The other changes in the Jenkinsfile optimize the visualization of the CI process in the CI's UI: previously, both of the Mac building steps have been displayed in green even though they have been skipped, now they are shown in grey. (@Bouncner made me aware of that.)
=> Let CI build JOB query plans

Jenkinsfile
The old version copies all SVG files to the JOB plan folder, which also includes copying the coverage badge...
=> Fix JOB plan file move statement

src/lib/operators/abstract_aggregate_operator.cpp, src/lib/operators/abstract_join_operator.cpp, src/lib/operators/alias_operator.cpp, src/lib/operators/get_table.cpp, src/lib/operators/join_hash.cpp, src/lib/operators/join_hash.hpp, src/lib/operators/join_index.cpp, src/lib/operators/table_scan.cpp, src/lib/operators/table_scan.hpp, src/lib/visualization/abstract_visualizer.hpp, src/test/lib/operators/join_hash_test.cpp, src/test/lib/operators/join_index_test.cpp, src/test/lib/operators/join_nested_loop_test.cpp, src/test/lib/operators/join_sort_merge_test.cpp, src/test/lib/operators/join_verification_test.cpp
The visualizer uses a `_wrap_label` function for shortening vertex labels. However, the implementation is messy and does not respect newline characters in string arguments, leading to line-width-inconsistencies and sometimes ugly plans.
This PR refactors `_wrap_label` and some operator descriptions to make plans look more nicely. For example: 
> <img width="790" alt="image" src="https://user-images.githubusercontent.com/9380917/130358401-5db70365-b461-40f9-b5f2-e78959d853cd.png">
> <img width="1412" alt="image" src="https://user-images.githubusercontent.com/9380917/130441470-70688875-ead1-4de5-abaf-3eb3c58c0c98.png">
> (new plans on the right)
=> Prettier Visualizer plans with consistent label wrapping & updated operator descriptions

scripts/test/compareBenchmarkScriptTest.py, src/benchmarklib/abstract_table_generator.cpp, src/benchmarklib/benchmark_config.cpp, src/benchmarklib/benchmark_config.hpp, src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/benchmark_table_encoder.cpp, src/benchmarklib/cli_config_parser.cpp, src/lib/statistics/table_statistics.cpp
With this PR, data preparation steps such as encoding and sorting table data, as well as generating table statistics, are executed using a `NodeQueueScheduler` instance. By default, the number of workers for the parallelized data preparation is equal to `std::thread::hardware_concurrency()`. A user can use the optional new benchmark flag `data_preparation_cores` to set the number of workers used for the data preparation.
Example configuration output of `compare_benchmarks.py` with this PR:
```
+Configuration Overview---+------------------------------------------------+------------------------------------------------+
| Parameter               | ./brel/file_based_output_1.json                | ./brel/file_based_output_1.json                | …
```
=> Use the scheduler for controlled data preparation parallelism

Jenkinsfile, scripts/benchmark_all.sh, scripts/compare_benchmarks.py, src/benchmark/tpcds_benchmark.cpp, src/lib/statistics/cardinality_estimator.cpp
Fixes #2381.
I updated the `benchmark_all.sh` according to #2381 and I want to get some feedback on the changes and whether they reflect what all of you had in mind when we decided to change the script. Currently, this PR is only meant to be used for discussions. Once we agree on the script, I will run some benchmarks and we can validate whether we still trust the script.
=> Adjust benchmark_all.sh to allow faster benchmark cycles

src/lib/optimizer/strategy/in_expression_rewrite_rule.cpp, src/lib/optimizer/strategy/in_expression_rewrite_rule.hpp, src/test/lib/optimizer/strategy/in_expression_rewrite_rule_test.cpp
Now, we heuristically take the number of input rows into account for InRewriting instead of purely relying on the number of items in the `IN`. At some point a proper cost model would be best.
=> Complement InRewriteRule's auto approach 

src/benchmarklib/abstract_table_generator.cpp
We usually indent the single table items when data is loaded or encoded:
```
- Loading/Generating tables
-  Loading table 'partsupp' from cached binary "tpch_cached_tables/sf-10.000000/partsupp.bin" (1 s 710 ms)
-  Loading table 'nation' from cached binary "tpch_cached_tables/sf-10.000000/nation.bin" (78 µs 761 ns)
-  Loading table 'supplier' from cached binary "tpch_cached_tables/sf-10.000000/supplier.bin" (30 ms 700 µs)
-  Loading table 'part' from cached binary "tpch_cached_tables/sf-10.000000/part.bin" (361 ms 356 µs)
-  Loading table 'orders' from cached binary "tpch_cached_tables/sf-10.000000/orders.bin" (2 s 184 ms)
-  Loading table 'customer' from cached binary "tpch_cached_tables/sf-10.000000/customer.bin" (522 ms 798 µs)
-  Loading table 'region' from cached binary …
```
=> Add missing space in benchmark runner output

src/CMakeLists.txt
This PR ensures that the include path of `libnuma` is used by the compiler when it's explicitly given to CMake (e.g., on non-root systems). Follow up to #2420.
=> CMake: include libnuma's include path

scripts/setup_imdb.py
Currently, out script to download the IMDB data [fails](https://hyrise-ci.epic-hpi.de/blue/organizations/jenkins/hyrise%2Fhyrise/detail/PR-2432/2/pipeline). The script downloads the IMDB data from dropbox. During the download, we display the download's progress on the command line. For displaying the progress, we need the total file size. Apparently, dropbox has changed the meta attribute for the file size from `Content-Length` to `X-Dropbox-Content-Length`.
=> Update setup_imdb script

scripts/test/hyriseBenchmarkTPCH_test.py, src/bin/server.cpp
This PR enables binary table loading for TPC-C in the `hyriseServer` binary. #2337 enabled it.
=> Enable binary table loading for TPC-C in server

scripts/setup_imdb.py
I don't know why the attribute changes from time to time. Maybe it depends on the dropbox server from which we download which might change based on utilization or whatever.
=> Fix imdb_script content length (again)

README.md
Since missing to link the alternate versions has already happened multiple times for different people, let's add additional information about linking the alternate version.
=> Readme: Add hint to link alternate brew package versions

src/benchmark/micro_benchmark_basic_fixture.cpp, src/benchmark/micro_benchmark_basic_fixture.hpp, src/benchmark/tpch_data_micro_benchmark.cpp, src/benchmarklib/table_builder.hpp, src/bin/console/console.cpp, src/bin/console/console.hpp, src/lib/expression/evaluation/expression_result_views.hpp, src/lib/expression/lqp_subquery_expression.cpp, src/lib/expression/lqp_subquery_expression.hpp, src/lib/null_value.hpp, src/lib/operators/abstract_read_only_operator.cpp, src/lib/operators/aggregate_hash.cpp, src/lib/storage/fixed_string_dictionary_segment.cpp, src/lib/storage/fixed_string_dictionary_segment.hpp, src/lib/storage/fixed_string_dictionary_segment/fixed_string_vector.cpp, src/lib/storage/frame_of_reference_segment.cpp, src/lib/storage/frame_of_reference_segment.hpp, src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_nodes.cpp, src/lib/storage/index/adaptive_radix_tree/adaptive_radix_tree_nodes.hpp, src/lib/storage/index/b_tree/b_tree_index.hpp, src/lib/storage/index/b_tree/b_tree_index_impl.cpp, src/lib/storage/index/b_tree/b_tree_index_impl.hpp, src/lib/storage/lz4_segment.cpp, src/lib/storage/lz4_segment.hpp, src/lib/storage/pos_lists/entire_chunk_pos_list.cpp, src/lib/storage/pos_lists/entire_chunk_pos_list.hpp, src/lib/utils/enum_constant.hpp, src/test/lib/storage/segment_iterators_test.cpp
This PR applies tidy's recommendation that unused parameters should have names. To avoid using getting an error for a unused parameter, tidy (more accurate: Google Style Guide and the "High Integrity C++ Coding Standard") recommends, e.g., `void print(std::string /*unused*/)`.
Note, the CI's clang-tidy will not catch these as they are part of more recent versions. With PR on using clang13/14, tidy starts to complain.
=> Clang Tidy: all parameters should be named in a function

Jenkinsfile, install_dependencies.sh
After the security vulnerability [CVE-2022-24765](https://github.blog/2022-04-12-git-security-vulnerability-announced/), the latest git version available in ubuntu 20.04 was [patched](https://launchpad.net/ubuntu/+source/git/1:2.25.1-1ubuntu3.3).
With this patch, git checks the owner of the top-level directory and does not perform a git command if the owner is not the current user. This check can be disabled for a repository by adding it as a safe directory, i.e., `git config --global --add safe.directory <dir>`.
In a current CI run, the user is `root`, but the files and directories in the cloned Hyrise project directory have the owner `113`.
This PR adds the directory of the root repository and the directories of the submodule repositories as safe directories to avoid CI errors of the …
=> Jenkinsfile: Add root repository and submodule repositories as safe directories

src/lib/optimizer/strategy/predicate_reordering_rule.cpp
The `PredicateReorderingRule` re-orders already-touched predicates. By tracking the visited nodes, this can be prohibited.
Here are some debug prints for TPC-DS Q41:
* Before
```
Before reordering:
0x6000025b5568: [Predicate] SUBQUERY (LQP, 0x600002780018, Parameters: [i_manufact, id=0]) > 0 card: 18000
0x6000025b5098: [Predicate] i_manufact_id BETWEEN INCLUSIVE 738 AND 778 card: 236.222
0x6000023e2bd8: [Validate] card: 18000
After reordering:
0x6000025b5568: [Predicate] SUBQUERY (LQP, 0x600002780018, Parameters: [i_manufact, id=0]) > 0 card: 18000
0x6000023e2bd8: [Validate] card: 18000
0x6000025b5098: [Predicate] i_manufact_id BETWEEN INCLUSIVE 738 AND 778 card: 236.222
Before reordering:
0x6000023e2bd8: [Validate] card: 18000
0x6000025b5098: [Predicate] i_manufact_id BETWEEN INCLUSIVE …
```
=> Fix redundant predicate reordering

install_dependencies.sh, src/lib/CMakeLists.txt, src/lib/utils/abstract_plugin.hpp, src/lib/utils/meta_table_manager.cpp, src/lib/utils/meta_tables/meta_exec_table.cpp, src/lib/utils/meta_tables/meta_exec_table.hpp, src/lib/utils/plugin_manager.cpp, src/lib/utils/plugin_manager.hpp, src/plugins/CMakeLists.txt, src/plugins/second_test_plugin.cpp, src/plugins/second_test_plugin.hpp, src/plugins/test_plugin.cpp, src/plugins/test_plugin.hpp, src/test/CMakeLists.txt, src/test/lib/utils/lossless_predicate_cast_test.cpp, src/test/lib/utils/meta_table_manager_test.cpp, src/test/lib/utils/meta_tables/meta_exec_table_test.cpp, src/test/lib/utils/plugin_manager_test.cpp
As highlighted by @Bouncner in #2437 there are many scenarios where the user (_Anwender_) wants to trigger a plugin function, e.g., to manually start reoptimization. 
There are two challenges to solve for this to work.
1. How should the user interaction look like? 
1. How can the PluginManager call plugin functions that are not known in advance without modifying the PluginManager. 
A possible solution for challenge 1 could be to use a new meta table. Inserting a row containing the name of the plugin and action to execute into this table could trigger the action.
This is the first proposal for a solution for challenge 2. The plugin's developer can just implement user-callable functions as a _normal_ plugin function. Afterward, the developer only has to use the macro …
=> Add user-callable functions to plugins

src/lib/logical_query_plan/lqp_utils.cpp, src/lib/logical_query_plan/lqp_utils.hpp, src/lib/optimizer/strategy/predicate_placement_rule.cpp, src/test/lib/logical_query_plan/lqp_utils_test.cpp, src/test/lib/optimizer/strategy/predicate_placement_rule_test.cpp
I have juggled around with JOB query plans and noticed that semi-join pushdowns are often blocked by diamond structures, involving `UnionNode`. Therefore, I changed the `PredicatePlacementRule` to allow for predicate pushdown through Union-based diamonds.
* TPC-H results stay unchanged
* JOB benchmark benefits heavily (~25%), mainly due to semi-joins getting pushed below Union-Like-Like diamonds.
* TPC-DS Q28 gains a boost of ~400%. 
**System**
<details>
<summary>pella - click to expand</summary>
| -- | -- |
| Hostname | pella |
| CPU | Intel(R) Xeon(R) CPU E7- 8870  @ 2.40GHz |
| Memory | 1.5TB |
| numactl | nodebind: 2  |
| numactl | membind: 2  |
</details>
| 02e587e5c | …
=> Allow predicate pushdown through Union diamonds

src/lib/cost_estimation/abstract_cost_estimator.cpp, src/lib/cost_estimation/abstract_cost_estimator.hpp, src/lib/logical_query_plan/abstract_lqp_node.cpp, src/lib/statistics/statistics_objects/generic_histogram.hpp, src/test/lib/logical_query_plan/mock_node_test.cpp
`AbstractLQPNode::_shallow_copy` does not cover the `comment` field. As a result, previously set comments get lost in deep-copied LQPs. With this PR, comments also get copied.
=> Deep-Copy LQP node comments

.gitmodules, src/lib/sql/sql_translator.cpp, src/test/lib/sql/sql_translator_test.cpp
This PR adds `BIGINT` as an alias for `LONG`. `BIGINT` column types in `CREATE TABLE` statements or `CAST`statements are translated to `DataType::Long`, as the two types are equal according to Postgres [1] (8 byte integer). 
[1] https://www.postgresql.org/docs/14/datatype-numeric.html
=> Support BIGINT Numeric Type

resources/test_data/tbl/string_numbers_null.tbl, src/lib/expression/evaluation/expression_evaluator.cpp, src/test/lib/expression/expression_evaluator_to_values_test.cpp
This PR fixes an error when casting nullable string columns to numeric types and adds a test for this case.
Steps to reproduce bug:
1. Consider the following file `a_table.tbl`:
```
a
string_null
1
null
```
2. Start `hyriseConsole` and import table (`COPY a_table FROM 'path_to_table'`)
3. Run the following query:
```SQL
SELECT CAST(a AS LONG) FROM a_table
```
4. Get the following error:
```
std::logic_error: src/lib/expression/evaluation/expression_evaluator.cpp:706 Cannot cast '' as Long
```
After applying this PR, we get the correct output:
```
=== Columns
|CAST(a AS long)|
|           long|
|           null|
=== Chunk 0 ===
|<ValueS>       |
|              1|
|           NULL|
===
2 rows total
```
We did not capture this bug in the tests yet as we only casted `NULL` values of numeric …
=> Fix Casting of string `NULL` Values 

src/lib/cache/gdfs_cache.hpp, src/lib/logical_query_plan/join_node.cpp, src/lib/logical_query_plan/join_node.hpp, src/lib/operators/abstract_join_operator.cpp, src/lib/optimizer/strategy/semi_join_reduction_rule.cpp, src/lib/visualization/abstract_visualizer.hpp, src/lib/visualization/lqp_visualizer.cpp, src/test/lib/logical_query_plan/join_node_test.cpp, src/test/lib/optimizer/strategy/semi_join_reduction_rule_test.cpp, src/test/lib/sql/sql_translator_test.cpp
This PR prepares for
* #2312
* #2467 
It adds the following functions/properties to `JoinNode`, which become relevant in case of `JoinMode::Semi`:
* `::is_semi_reduction`
* `::mark_as_semi_reduction`
* `::get_or_find_reduced_join_node`
=> JoinNode: Add semi reduction flag & reduced join reference as properties

src/benchmark/operators/join_aggregate_benchmark.cpp, src/lib/logical_query_plan/logical_plan_root_node.hpp, src/lib/optimizer/strategy/predicate_placement_rule.cpp, src/test/lib/optimizer/strategy/predicate_placement_rule_test.cpp, src/test/lib/sql/sql_translator_test.cpp
The `PredicatePlacementRule` pushes down predicates until it reaches a barrier node that prevents further pushdown. In this case, pushdown predicates are inserted above the barrier node, and the pushdown traversal restarts at the barrier node.
Our `_push_down_traversal` subroutine takes a given node and processes the inputs. However, in some cases, the given node (a barrier from a previous pushdown) is also a predicate eligible for pushdown. Currently, these barrier predicates (having multiple outputs) cannot be pushed down.
This PR fixes the implementation so that predicate barriers are pushed down as well. As a result, the TPC-DS and Join Order benchmarks profit. In addition, this PR streamlines the code for pushdowns through Union-diamonds.
---
**System**
<details>
<summary>pella - …
=> Enable pushdown of predicate barriers

src/test/lib/import_export/binary/binary_writer_test.cpp
Minor change to the BinaryWriterTest with regard to Issue #2472:
- Removed unnecessary file removal in test setup
The tests still run successful and no files exist after finishing the tests.
=> Removed superfluous file removal during `SetUp `

CMakeLists.txt
This PR fixes a spammy Cmake output when using link time optimization.
```
CMake Warning (dev) at third_party/benchmark/src/CMakeLists.txt:20 (add_library):
Policy CMP0069 is not set: INTERPROCEDURAL_OPTIMIZATION is enforced when
enabled.  Run "cmake --help-policy CMP0069" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
INTERPROCEDURAL_OPTIMIZATION property will be ignored for target
'benchmark'.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
=> Remove LTO builds warning

src/lib/storage/chunk_encoder.cpp, src/test/lib/storage/chunk_encoder_test.cpp
This PR fixes bug in the ´SegmentEncoder´.
I'm not sure if there is a corresponding issue.
The error was that when a not nullable encoded segment was passed to the segment encoder and `Unencoded` was selected as the target encoding, the new `ValueSegment` is created with an empty, but initialized `null_values` vector.
Because of that, the `_null_values` optional is set and `is_nullable` returned true, which resulted in errors.
A way to recreate this error on the master branch is to lead encoded tables in an unencoded benchmark:
First run `./hyriseBenchmarkTPCH -s 0.01 -r 1`, after that run `./hyriseBenchmarkTPCH -s 0.01 -r 1 -e Unencoded`.
=> Fix SegmentEncoder issue wrongly initializing the _null_values optional of ValueSegments

scripts/test/hyriseServer_test.py
On sidon (Ubuntu 20.04, psql 12.7) I got the following error when running the `hyriseServerTest.py` script/connecting to a `hyriseServer` with psql:
```
psql: error: could not connect to server: Connection refused
Is the server running on host "localhost" (::1) and accepting
TCP/IP connections on port 41963?
received invalid response to GSSAPI negotiation: R
```
When applying this suggestion [1], everything worked fine. Basically, we disable encrypted connections to the server for the test [2]. Since we do not perform user authentication/encryption by any means, this should be okay. Though I could not reproduce the error on macOS/psql 14.05, I adapted the test file. 
[1] https://github.com/psycopg/psycopg2/issues/1084#issuecomment-656778107
[2] …
=> Disable encrypted connections in server tests

src/lib/expression/evaluation/expression_functors.hpp, src/lib/operators/join_hash.cpp, src/lib/operators/join_hash/join_hash_steps.hpp
Two issues I found when using clang9. I have no idea why they appear right now, but `pow` and `fmod` (both C lib functions) require both `double` values. Using their C++ pendants works fine.
The `fmod` issue could be caused by clang instantiating the function for differnet types of `a_value` and `b_value`.
Further, this PR sets a maximum to the number of radix bits which was beneficial for large scale factors (> SF 100).
=> Mini fixes

resources/benchmark/jcch/part.csv.json, resources/test_data/tbl/tpch/minimal/part.tbl, resources/test_data/tbl/tpch/sf-0.001/part.tbl, resources/test_data/tbl/tpch/sf-0.002/part.tbl, resources/test_data/tbl/tpch/sf-0.01/part.tbl, resources/test_data/tbl/tpch/sf-0.02/part.tbl, src/benchmarklib/tpch/tpch_table_generator.cpp
According to the TPC-H schema [1, p. 15], the column's name is `p_retailprice` (which also makes more sense). The mistake did not show since the column is not queried. This PR replaces the incorrect column name with the correct one.
[1] https://www.tpc.org/tpc_documents_current_versions/pdf/tpc-h_v3.0.1.pdf
=> Rename column `p_retailsize` in TPC-H's `part` table to `p_retailprice`

src/lib/operators/abstract_operator.cpp, src/lib/operators/maintenance/create_table.cpp, src/lib/operators/maintenance/create_view.cpp, src/lib/operators/maintenance/drop_table.cpp, src/lib/operators/maintenance/drop_view.cpp, src/test/lib/operators/maintenance/create_table_test.cpp, src/test/lib/operators/maintenance/create_view_test.cpp, src/test/lib/operators/maintenance/drop_table_test.cpp, src/test/lib/operators/maintenance/drop_view_test.cpp
Just stumbled across table creation and noticed that some maintenance operators return a dummy table. Since others don't (`Insert/Delete`, `Import/Export`, ...) and this is also nothing SQL standardish, this PR removes this behavior.
=> Remove dummy table output from maintenance operators

README.md, scripts/test/hyriseServer_test.py, src/benchmarklib/abstract_table_generator.cpp, src/lib/storage/reference_segment/reference_segment_iterable.hpp
This tiny PR does two things:
- change a text during benchmark loading
- adds contributors
**Badge**:
The coverage badge URL remains the same (Jenkin's badget) but we internally rewrite the header caching information with the HPI to ensure that badges are not cached. This has been the reason for the previous solution on heroku.
**Benchmark information**:
Change the text for table encoding and stats generation from `Encoding 'lineitem' - no encoding necessary (12 s 248 ms)` to `Processing 'lineitem' - no encoding necessary (12 s 248 ms)`. Since there are stats generated, I am always curious what a lot cores can do for 12 seconds, when no re-encoding is necessary.
=> Avoid coverage badge caching and change info text

src/benchmarklib/encoding_config.cpp, src/benchmarklib/synthetic_table_generator.cpp, src/benchmarklib/table_builder.hpp, src/lib/expression/between_expression.cpp, src/lib/expression/between_expression.hpp, src/lib/expression/evaluation/expression_evaluator.cpp, src/lib/expression/in_expression.cpp, src/lib/expression/in_expression.hpp, src/lib/operators/abstract_operator.cpp, src/lib/operators/aggregate_sort.cpp, src/lib/operators/table_scan.cpp, src/lib/optimizer/strategy/in_expression_rewrite_rule.cpp, src/lib/optimizer/strategy/subquery_to_join_rule.cpp, src/lib/server/postgres_protocol_handler.cpp, src/lib/server/result_serializer.cpp, src/lib/sql/sql_translator.cpp, src/lib/statistics/cardinality_estimator.cpp, src/lib/statistics/join_graph_statistics_cache.cpp, src/lib/statistics/statistics_objects/range_filter.cpp, src/plugins/mvcc_delete_plugin.cpp, src/test/lib/expression/evaluation/like_matcher_test.cpp, src/test/lib/operators/import_test.cpp, src/test/lib/operators/join_hash/join_hash_types_test.cpp, src/test/lib/operators/table_scan_test.cpp, src/test/lib/optimizer/strategy/column_pruning_rule_test.cpp, src/test/lib/server/transaction_handling_test.cpp, src/test/lib/storage/storage_manager_test.cpp
The arguments reference expressions to which the predicate should be applied. Thus, these are operands, not values (triggered my inner Monk, also see the other predicate expressions: BinaryPredicateExpression and IsNullExpression). Furthermore, as I grepped the codebase for `value()`, I removed some superfluous calls to `value()` and `has_value()` when dealing with `std::optional`s.
=> Rename `BetweenExpression` and `InExpression`s' `value()` to `operand()`

Jenkinsfile, src/bin/console/console.cpp, src/bin/console/console.hpp, src/bin/console/pagination.cpp, src/lib/operators/aggregate_hash.cpp, src/lib/operators/aggregate_hash.hpp, src/lib/operators/join_hash.cpp, src/lib/operators/join_hash.hpp, src/plugins/ucc_discovery_plugin.cpp, src/plugins/ucc_discovery_plugin.hpp, src/test/lib/operators/join_hash_test.cpp
We recently figured out ([again](https://gitlab.kitware.com/cmake/cmake/-/issues/20058)) that clang-tidy does not find all flaws in unity builds. However, the clang-tidy stage already runs quite long in the CI pipeline, so we do not want remove the unity option there. Thus, I re-ran a tidy build on nemea (clang-14) without unity build and fixed the errors.
=> Fix some clang-tidy issues

CONTRIBUTING.md
Guideline as discussed at the roundtable. [Click for preview](https://github.com/hyrise/hyrise/blob/dey4ss/test_variables_guideline/CONTRIBUTING.md#formatting-and-naming).
=> Add guideline for declaring member variables of test classes

src/lib/optimizer/strategy/dependent_group_by_reduction_rule.cpp, src/lib/optimizer/strategy/dependent_group_by_reduction_rule.hpp, src/lib/sql/sql_translator.cpp, src/test/lib/optimizer/strategy/dependent_group_by_reduction_rule_test.cpp
Thanks to @Bouncner, I read the following note in [a paper](https://www.vldb.org/pvldb/vol16/p1208-liu.pdf):
> It took more than two years for PostgreSQL developers to implement a pattern that
removes the DISTINCT clause if the result is unique by definition, and this feature is
yet to be merged [26].
That's true and it does not look like they will even merge it soon: https://commitfest.postgresql.org/35/2433/
Thus, I was triggered to implement it in Hyrise and prove we can do this in less than half an hour. It does not change anything in benchmarks, but now, we have it.
(To be fair: The Postgres contributors had to implement passing UCCs in the LQP and tried multiple versions. Also, I needed more than half an hour with all tests and an edge case I forgot to cover.)
=> Remove superfluous DISTINCT

src/benchmark/star_schema_benchmark.cpp, src/benchmark/tpcds_benchmark.cpp
TPC-DS verification uses fixed result sets for some queries that are not supported by SQLite, which are only valid for SF 1. Some SSB queries `SUM` integers, which lead to `int` overfloaws in SQLite (and thus, wrong results) for SF > 0.1. This PR ensures that the two benchmark binaries crash when invoked with unfitting SFs and `--verify`.
=> Limit scale factors for TPC-DS and SSB verification

src/benchmarklib/benchmark_table_encoder.cpp, src/benchmarklib/benchmark_table_encoder.hpp
This PR uses a `std::stringstream` to encapsulate writing the default-type encoding message to `std::cout` to prevent messages from multiple threads being mangled.
Example output line without this change:
```
orders.o_totalprice' of type float cannot be encoded as FixedStringDictionary and is - Column 'left Unencoded.lineitem
```
=> Use `std::stringstream` for default-type encoding message

src/CMakeLists.txt, src/benchmarklib/random_generator.hpp, src/benchmarklib/tpcc/procedures/tpcc_new_order.cpp, src/benchmarklib/tpcc/procedures/tpcc_payment.cpp, src/benchmarklib/tpch/tpch_benchmark_item_runner.cpp, src/bin/console/console.cpp, src/lib/expression/evaluation/like_matcher.hpp, src/lib/operators/join_hash.cpp, src/lib/operators/join_sort_merge.cpp, src/lib/operators/sort.cpp, src/lib/optimizer/join_ordering/enumerate_ccp.cpp, src/lib/optimizer/optimizer.cpp, src/lib/storage/lz4_segment.cpp, src/lib/utils/meta_tables/meta_system_information_table.cpp, src/plugins/mvcc_delete_plugin.cpp
This PR makes small changes to support builds with clang 16. Notably, we suppress the `-Wunsafe-buffer-usage` check since we access buffers via pointers / pointer arithmetic in some cases when we know what we do (e.g., uninitialized vector works like this). The rest are mainly changes to silence clang-tidy-16. However, currently encounter build errors for tidy builds (see #258), so we do not update the CI yet.
=> Support Clang-16

CMakeLists.txt, DEPENDENCIES.md, src/lib/CMakeLists.txt, src/test/CMakeLists.txt
Closes #2572
Notably, LLD is not required anymore, but a warning is shown if the default linker is used on Linux.
I also added the option to use another linker by specifying `HYRISE_LINKER` (for example `mold`) - `CMAKE_LINKER` was actually already set to `/bin/ld`.
=> Make linker configurable and emit useful messages about linker choice

Jenkinsfile, scripts/test/hyriseBenchmarkJCCH_test.py, src/benchmarklib/abstract_table_generator.cpp, src/benchmarklib/jcch/jcch_benchmark_item_runner.cpp, src/lib/scheduler/node_queue_scheduler.cpp, src/test/lib/scheduler/scheduler_test.cpp
Planned work on Hyrise might recursively add tasks to the scheduler. This PR adds a test doing exactly that (a simple merge sort).
This test triggered a minor issue when shutting down the scheduler. This issue should be fixed with the PR.
Minor:
- changes to Jenkins are solely to avoid starting multiple Hyrise instances using all the threads of the system (the tests are using small scale factors, but we still spawns (partially spinning) worker threads on each core).
- changes in the benchmarklib are solely minor stuff as auto-to-stick
=> Recursive Scheduler Test and Scheduler Shutdown Fix

scripts/test/hyriseConsole_test.py, src/lib/operators/difference.cpp, src/lib/operators/join_index.cpp, src/lib/operators/join_nested_loop.cpp, src/lib/operators/product.cpp, src/lib/operators/table_scan/abstract_table_scan_impl.hpp, src/lib/statistics/cardinality_estimator.cpp, src/test/lib/operators/join_test_runner.cpp, src/test/lib/operators/sort_test.cpp, src/test/lib/operators/table_scan_test.cpp, src/test/lib/operators/union_positions_test.cpp, src/test/lib/operators/validate_test.cpp, src/test/lib/storage/encoded_segment_test.cpp, src/test/lib/storage/encoded_string_segment_test.cpp, src/test/lib/storage/reference_segment_test.cpp, src/test/lib/storage/segment_iterators_test.cpp
Just PR just applies the "best practice" of avoiding temporaries when using `emplace_back()`.
All cases should be trivial for compilers to optimize and I thus don't expect any performance changes. ~Going to measure anyways. Benchmarks are running right now.~
Nothing surprising in terms of performance.
This PR increases the timeouts for the Python `pexpect` scripts as they often timed out when the load on the CI server was high.
**System**
<details>
<summary>node-17 - click to expand</summary>
| -- | -- |
| Hostname | node-17 |
| CPU | AMD EPYC 7742 64-Core Processor |
| Memory | 492GB |
| numactl | nodebind: 0  |
| numactl | membind: 0 1  |
</details>
| 8114ddda7 | 22.06.2023 …
=> No RowID temporaries for emplace_back()

scripts/plot_performance_breakdown.py
This PR updates the `plot_performance_breakdown.py` script:
- address Python warnings (see log below)
- generated PDF instead of PNG
- remove manual mangling handling (no longer necessary; tested with GCC and Clang)
- move legend to better show long rule names
<details>
<summary>Python warnings</summary>
```/hyrise/./scripts/plot_performance_breakdown.py:81: UserWarning: FixedFormatter should only be used together with FixedLocator
ax.set_yticklabels(["{:,.0%}".format(x) for x in ax.get_yticks()])
/hyrise/./scripts/plot_performance_breakdown.py:111: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
for rule_name, rule_duration in benchmark.iteritems():
/hyrise/./scripts/plot_performance_breakdown.py:121: UserWarning: FixedFormatter should …
```
=> Update plot_performance_breakdown.py Script

src/lib/storage/table_column_definition.cpp, src/lib/storage/table_column_definition.hpp, src/test/lib/operators/difference_test.cpp, src/test/lib/operators/operator_scan_predicate_test.cpp
We first tried to add coverage to `TableColumnDefinition`, but found `concatenated` as unsused an also not working function. Hence we removed it to increase coverage this way.
Next we added a simple test for the `Difference` operator's `getName()` function.
Last we added a varying test for the `<<` operator of the `OperatorScanPredicate`
=> [DYOD] Team 3 - Sprint 4

Jenkinsfile
The mac x86 CI node shows a pretty low network stability. As if it executed in the last CI group, we regularly fail jobs perfectly fine jobs after 3h or more.
This change simply tells Jenkins to repeat the step several times before failing. As long as we do not get the network under control, I am afraid that this is the best measure at the moment.
=> Jenkins - Retry Mac x86 CI Runs

Jenkinsfile, scripts/test/hyriseBenchmarkJCCH_test.py, scripts/test/hyriseBenchmarkStarSchema_test.py, scripts/test/hyriseConsole_test.py, src/lib/logical_query_plan/stored_table_node.cpp, src/lib/logical_query_plan/stored_table_node.hpp
Recently, we encountered many CI issues with SSB tests that called the dbgen in in parallel. This PR moves execution of `hyriseBenchmarkStarSchema_test.py` to an own stage and removes SSB data generation from `hyriseConsole_test.py`. Furthermore, an issue with concurrent writes of `StoredtableNode`'s cached output expressions for cached PQPs has been resolved by @Bouncner.
=> Make CI runs more stable

scripts/test/hyriseServer_test.py, src/benchmarklib/benchmark_runner.cpp, src/lib/expression/evaluation/like_matcher.hpp, third_party/tpch-dbgen/driver.c, third_party/tpch-dbgen/dss.h, third_party/tpch-dbgen/dsstypes.h, third_party/tpch-dbgen/print.c
Clang-16 complained about missing prototypes in the TPC-DS and TPC-H data generators (deprecated in C2x). This PR adds them if necessary. Furthermore, the `experimental/functional` header is not included anymore in the like matcher. The experimental version is not provided by clang-17 (libc++) anymore, leading to a compilation error (and all CI stages use compilers where the experimental header is not necessary).
Includes hyrise-mp/tpcds-kit#1.
=> Add function prototypes in third-party DB generators

Jenkinsfile, README.md, scripts/test/hyriseConsole_test.py, src/lib/statistics/statistics_objects/range_filter.cpp, src/lib/strong_typedef.hpp, src/test/lib/statistics/statistics_objects/range_filter_test.cpp
We encountered several timeout issues with TPC-DS generation in the Console test. This PR replaces TPC-DS with TPC-C, hoping for faster generation times.
Furthermore, the SSB test is now moved to the system test stage, where it should not be executed in parallel.
Finally, this PR refactors range filters and their tests a bit, adding pruning with between exclusive predicates.
=> Use TPC-C in Console test

src/lib/expression/evaluation/like_matcher.hpp, src/lib/utils/performance_warning.hpp
Mini PR to fix an issue that Clang 14 has with `\n` in certain comments. It is a known issue with clang 14 (https://stackoverflow.com/q/25197299/1147726).
I consider this change to make sense since:
* the new lines in the examples do provide any value
* clang 14 is not that old and used on several of our servers
* modifying make files to ignore certain errors of this particular clang version is not worth it as newer versions do not complain
=> Fix for clang 14: issues with `\n` in comments

src/benchmarklib/benchmark_runner.cpp, src/benchmarklib/benchmark_runner.hpp, src/lib/scheduler/task_queue.hpp
This PR replaces the `std::counting_semaphore` with `moodycamel::LightweightSemaphore` (also used in the task queues). libc++ had an issue with semaphore wake ups (see https://reviews.llvm.org/D114119) and this change hasn't made it to the libc++ shipped with macOS so far.
On my notebook, it took several hours to reproduce the problem but on the macOS CI machine (I don't understand why to be honest), it happened quite frequently in `hyriseBenchmarkFileBased_test.py`.
I haven't tested the LLVM-shipped libc++ versions as I would like to keep Hyrise running on the default macOS setup.
=> Fix macOS wake up issues

scripts/compare_benchmarks.py
The output of `benchmark_all.sh` uses the `--github` flag (enables GitHub's diff format that shows improving queries in green, regressing queries in red).
The `compare_benchmark.py` (called by `benchmark_all.sh`) uses a post-processing step in which the color coding is checked to add GitHub markdown accordingly. But when the script is called from `benchmark_all.sh`, no color codes are emitted as the used `termcolor` package checks for a terminal that supports colors.
This PR changes the `compare_benchmark.py` script to force a colorful output in all situations.
=> Fix for benchmark_all.sh output

src/lib/server/server.cpp
This is a minimal PR that ensures that the server flushes the message "Server started at ..." when the server is starting.
We use this message in a couple of benchmarking scripts. The scripts wait for this message to be sure that the server has started. Without flushing, scripts sometimes wait forever.
=> Mini-PR: flush server start message

scripts/test/hyriseConsole_test.py, src/benchmark/file_based_benchmark.cpp, src/benchmark/join_order_benchmark.cpp, src/benchmark/star_schema_benchmark.cpp, src/benchmark/tpcc_benchmark.cpp, src/benchmark/tpcds_benchmark.cpp, src/benchmark/tpch_benchmark.cpp, src/benchmark/tpch_data_micro_benchmark.cpp, src/benchmark/tpch_table_generator_benchmark.cpp, src/benchmarklib/abstract_table_generator.cpp, src/benchmarklib/abstract_table_generator.hpp, src/benchmarklib/benchmark_config.cpp, src/benchmarklib/benchmark_config.hpp, src/benchmarklib/cli_config_parser.cpp, src/benchmarklib/cli_config_parser.hpp, src/benchmarklib/jcch/jcch_table_generator.cpp, src/benchmarklib/ssb/ssb_table_generator.cpp, src/benchmarklib/ssb/ssb_table_generator.hpp, src/benchmarklib/tpcc/tpcc_table_generator.cpp, src/benchmarklib/tpcc/tpcc_table_generator.hpp, src/benchmarklib/tpcds/tpcds_table_generator.cpp, src/benchmarklib/tpcds/tpcds_table_generator.hpp, src/benchmarklib/tpch/tpch_table_generator.cpp, src/benchmarklib/tpch/tpch_table_generator.hpp, src/bin/console/console.cpp, src/bin/console/console.hpp, src/bin/server.cpp, src/test/benchmarklib/tpcc/tpcc_test.cpp, src/test/lib/concurrency/stress_test.cpp, src/test/lib/utils/plugin_manager_test.cpp
This PR adds a config option to use binary cached benchmark tables in hyriseConsole, which is turned on by default. Furthermore, I noticed that according to the documentation, the scheduler should be turned on per default, as well. This is also fixed.
Backgroung for this was that I demoed Hyrise using the console and noticed that data generation was always triggered and running on only one core.
=> Turn on scheduler and benchmark data caching in Console

Jenkinsfile
The CI step for nix missed the check for a full CI or master run. This PR adds this check.
https://hyrise-ci.epic-hpi.de/blue/organizations/jenkins/hyrise%2Fhyrise/detail/PR-2656/6/pipeline shows what happens. The CI hangs in a non-finishing state that does not make any progress.
=> [CI] Run Nix only for full CI and master

Dockerfile
The docker build fails because a comment is misaligned. 
```
=> [internal] load build definition from Dockerfile                                                                                                                    2.2s
=> => transferring dockerfile: 1.71kB                                                                                                                                  0.0s
- ConsistentInstructionCasing: Command 'others).' should match the case of the command majority (uppercase) (line 52)
Dockerfile:52
--------------------
50 |         && ln -sf /usr/bin/llvm-symbolizer-14 /usr/bin/llvm-symbolizer \
51 |         && pip3 install --break-system-packages scipy pandas matplotlib  # preload large Python packages (installs numpy and
52 | >>> …
```
=> Docker build fails with parse error (#2660)

resources/benchmark/tpcds/schema.sql
While working on another project, I accidentally noticed that the TPC-DS schema we provide has the wrong data type for `customer`'s `c_last_review_date` column (`char(10)`instead of `integer`). There should not be any implications because it's correct in the table generator: https://github.com/hyrise/hyrise/blob/b31d65279c674f9af6b1e74e1302e97860861373/src/benchmarklib/tpcds/tpcds_table_generator.cpp#L225-L226
Source: https://www.tpc.org/TPC_Documents_Current_Versions/pdf/TPC-DS_v3.2.0.pdf (p. 32)
=> Fix column type in TPC-DS schema

scripts/test/hyriseBenchmarkTPCC_test.py, scripts/test/hyriseBenchmarkTPCH_test.py, src/benchmarklib/abstract_table_generator.cpp, src/benchmarklib/file_based_table_generator.cpp
Small PR that adds a job for each benchmark table that is loaded from a file (either cached binary or CSV file for file-based benchmarks). There should not be differences for the latter case (heavy parts of CSV parsing are already parallel).
However, parsing the binaries in single-threaded, so doing this in parallel for multiple tables is advantageous for benchmarks where not only a single table dominates the loading time. Thus, the loading times decrease significantly for TPC-DS, JOB, and TPC-C.
Though loading from binaries is by far not the slowest part of benchmark preparation, it might still be noticeable for larger SFs.
=> Parallelize loading of benchmark data

scripts/test/hyriseConsole_test.py, src/bin/console/console.cpp, src/bin/console/console.hpp
Just a small PR to restore the settings (scheduler, binary caching) and to fix the segfault when exiting the Console with scheduler.
=> Console: Restore default settings during `reset`

src/lib/scheduler/node_queue_scheduler.cpp, src/lib/server/server.cpp, src/lib/server/server.hpp, src/lib/server/session.cpp, src/lib/server/session.hpp, src/test/lib/server/mock_socket.hpp
Since boost 1.87, `io_service` is now `io_context` (more or less, there is more to it, see here: https://github.com/boostorg/asio/issues/110).
Since `brew` on macOS now ships boost 1.87, this PR addresses the deprecation.
=> Fix io_service issue with libboost 1.87

src/benchmarklib/benchmark_table_encoder.cpp, src/lib/statistics/generate_pruning_statistics.cpp, src/lib/statistics/generate_pruning_statistics.hpp, src/lib/storage/chunk_encoder.cpp
Parallelize generation of chunk pruning statistics when doing so for a full table.
Currently, statistics-generation is only fast when generating benchmark data from scratch (not when loading the cached binary files from disk).
This is because we immediately invoke the statistics generation when encoding a chunk (which is done in a parallel fashion). However, when chunks are already encoded, we fall back to the `generate_chunk_pruning_statistics(const std::shared_ptr<Table>& table)` for the whole table, which did not use any parallelization at all.
This step reduces the time required for the `encoding/statistics generation` step on loaded data from about 14.5s to 2.5s for SF 20.
=> Parallelize chunk pruning statistics generation for full table

README.md, resources/test_data/sqlite_testrunner_queries.sql, src/lib/sql/sql_translator.cpp, src/lib/sql/sql_translator.hpp, src/test/lib/sql/sql_translator_test.cpp
The PR integrates the changes to the sql-parser (see [hyrise/sql-parser #240](https://github.com/hyrise/sql-parser/pull/240)) into the Hyrise join behavior.
In short, this allows a list of identifiers (a.k.a column names) when joins name columns with USING (...). The result should only contain the columns that were used for the join once.
This behavior is in line with the SQL standard and PostgreSQL. 
Specifically, the sql-parser parses a join into the updated struct:
```C++
struct JoinDefinition {
JoinDefinition();
virtual ~JoinDefinition();
TableRef* left;
TableRef* right;
Expr* condition;
JoinType type;
std::vector<char*>* namedColumns;
};
```
We execute a `_join_using_named_columns` when only namedColumns is set and condition is not. We fail if both are set (due to ambiguity).
=> Correctly parse named columns for joins

resources/test_data/sqlite_testrunner_queries.sql, src/lib/statistics/cardinality_estimator.cpp, src/test/lib/statistics/cardinality_estimator_test.cpp
While reviewing #2675, I [noticed](https://github.com/hyrise/hyrise/pull/2675#pullrequestreview-2552850261) that segfaults occur when joining with columns that have only `DummyStatistics` (e.g., constants or aggregates). That's something I missed in #2659 🙄.
This PR fixes these segfaults. Furthermore, we did not cover certain edge cases before:
1.  When we did not have an input row count (e.g., `SELECT foo JOIN (SELECT 1 AS bar) ...`), we returned a cardinality of 0. Now, we return at least the cardinality of `foo`.
2. For aggregates without `GROUP BY` columns, we still forwarded the input row count (which is the upper bound whenever we group by something). However, aggregates without `GROUP BY` yield one row per definition.
I don't know if that changes anything in the benchmarks, but I …
=> Minor fixes in cardinality estimation

Dockerfile
Removing setting a soft link for the llvm symbolizer (added with #953) in the Dockerfile.
=> Remove llvm-symbolizer from Dockerfile

install_dependencies.sh
The `install_dependencies.sh` runs apt in the background, so the python requirements can be installed simultaneously.
This fails if `pip3` is called before it is installed via `apt-get`:
```
Processing triggers for dbus (1.14.10-4ubuntu4.1) ...
+ sudo apt-get install --no-install-recommends -y autoconf bash-completion bc clang-16 clang-17 clang-format-17 clang-tidy-17 cmake curl dos2unix g++-14 gcc-14 git graphviz libboost-all-dev libhwloc-dev libncurses5-dev libnuma-dev libnuma1 libpq-dev libreadline-dev libsqlite3-dev libtbb-dev lld-17 man parallel postgresql-server-dev-all python3 python3-pip valgrind
+ git submodule update --jobs 5 --init --recursive
+ pip3 install --break-system-packages -r requirements.txt
./install_dependencies.sh: line 64: pip3: command not found
+ echo 'Error …
```
=> Fix `install_dependencies.sh`

CMakeLists.txt, src/lib/operators/join_hash/join_hash_steps.hpp, src/test/lib/server/server_test_runner.cpp
Since there is ongoing discussion on `-Weverything`, `-Wswitch-enum`, and `-Wswitch-default` I suggest merging this PR first so Hyrise can be compiled using Clang 20.
=> Clang 20 Quickfix

src/test/.clang-tidy
Clangd highlights linter errors in VSCode (and other IDEs). It also does this for test files, which turn out very red and unreadable. This PR disables linting for the test folder, by placing a .clang-tidy file in the test folder that disables all rules.
=> Disable clang-tidy for the test folder

src/test/CMakeLists.txt, src/test/lib/memory/variable_length_key_test.cpp
Based on Coverage Report Created: 2025-05-22 14:51, we are testing the following previously uncovered member functions and operators:
1. VariableLengthKey::operator=(const VariableLengthKeyBase&)
2. VariableLengthKey::operator=(const VariableLengthKey&)
3. VariableLengthKey::operator!=(const VariableLengthKey&)
4. VariableLengthKey::operator!=(const VariableLengthKeyConstProxy&)
5. VariableLengthKey::bytes_per_key() const
6. operator<<(std::ostream&, const VariableLengthKey&)
=> add tests for variable_length_key.cpp

Jenkinsfile, src/test/benchmarklib/tpcds/tpcds_table_generator_test.cpp, src/test/lib/concurrency/stress_test.cpp, src/test/lib/sql/sqlite_testrunner/sqlite_testrunner.cpp, src/test/lib/sql/sqlite_testrunner/sqlite_testrunner.hpp, src/test/lib/sql/sqlite_testrunner/sqlite_testrunner_encodings.cpp
Our CI pipeline now runs around 3 to 3.5 hours, this PR tries to push it more to ~2.5 h.
Decrease the CI pipeline runtime by:
- Combining tests for row counts and PKs/FKs of TPCDSTableGenerator
- Omitting SQLite tests with encoded data in shuffled system tests
- Giving more resources to clang release build with TSan
- Skipping SQLite tests in valgrind stage
- Reducing the load of some stress tests (at least in sanitizer builds), skip tests for unencoded data in _encoded_ SQLite tests, cache SQLite results there
If we want to further decrease the runtime, the following ideas might be taken into account:
- skip release build on x64 Mac
- run TPC-DS verification in parallel to the pipeline, skip Nix release build 
- further look into decreasing system test runtime, e.g., TPCC tests.
=> Reduce CI pipeline runtime

CMakeLists.txt, Jenkinsfile, src/benchmarklib/tpcc/procedures/abstract_tpcc_procedure.cpp, src/benchmarklib/tpcc/procedures/abstract_tpcc_procedure.hpp
There CAN be issues when using `inline static thread-local` and LTO builds. On macOS with brew's LLVM, it happened for the past 3 versions.
This PR should hopefully fix it as we get rid of `inline`.
I will run benchmarks, just to be sure.
=> Fix LTO linking issues on macOS

README.md
As people appear to be still struggling with properly referencing Hyrise (cf. https://dl.acm.org/doi/pdf/10.1145/3677141), this PR attempts to make the bibtex reference more obvious.
Further, it removes some clutter from the entry.
=> [Readme] Make bibtex reference more obvious
